    .align 2
ProgrammableWaveData_1::
	.incbin "sound/programmable_wave_samples/01.pcm"

    .align 2
ProgrammableWaveData_2::
	.incbin "sound/programmable_wave_samples/02.pcm"

    .align 2
ProgrammableWaveData_3::
	.incbin "sound/programmable_wave_samples/03.pcm"

    .align 2
ProgrammableWaveData_4::
	.incbin "sound/programmable_wave_samples/04.pcm"

    .align 2
ProgrammableWaveData_5::
	.incbin "sound/programmable_wave_samples/05.pcm"

    .align 2
ProgrammableWaveData_6::
	.incbin "sound/programmable_wave_samples/06.pcm"

    .align 2
ProgrammableWaveData_7::
	.incbin "sound/programmable_wave_samples/07.pcm"

    .align 2
ProgrammableWaveData_8::
	.incbin "sound/programmable_wave_samples/08.pcm"

    .align 2
ProgrammableWaveData_9::
	.incbin "sound/programmable_wave_samples/09.pcm"

    .align 2
ProgrammableWaveData_10::
	.incbin "sound/programmable_wave_samples/10.pcm"

    .align 2
ProgrammableWaveData_11::
	.incbin "sound/programmable_wave_samples/11.pcm"

    .align 2
ProgrammableWaveData_12::
	.incbin "sound/programmable_wave_samples/12.pcm"

    .align 2
ProgrammableWaveData_13::
	.incbin "sound/programmable_wave_samples/13.pcm"

    .align 2
ProgrammableWaveData_14::
	.incbin "sound/programmable_wave_samples/14.pcm"

    .align 2
ProgrammableWaveData_15::
	.incbin "sound/programmable_wave_samples/15.pcm"

    .align 2
ProgrammableWaveData_16::
	.incbin "sound/programmable_wave_samples/16.pcm"

@ Unused
    .align 2
ProgrammableWaveData_17::
	.incbin "sound/programmable_wave_samples/17.pcm"

@ Unused
    .align 2
ProgrammableWaveData_18::
	.incbin "sound/programmable_wave_samples/18.pcm"

@ Unused
    .align 2
ProgrammableWaveData_19::
	.incbin "sound/programmable_wave_samples/19.pcm"

@ Unused
    .align 2
ProgrammableWaveData_20::
	.incbin "sound/programmable_wave_samples/20.pcm"

    .align 2
ProgrammableWaveData_21::
	.incbin "sound/programmable_wave_samples/21.pcm"

    .align 2
ProgrammableWaveData_22::
	.incbin "sound/programmable_wave_samples/22.pcm"

    .align 2
ProgrammableWaveData_23::
	.incbin "sound/programmable_wave_samples/23.pcm"

    .align 2
ProgrammableWaveData_24::
	.incbin "sound/programmable_wave_samples/24.pcm"

    .align 2
ProgrammableWaveData_25::
	.incbin "sound/programmable_wave_samples/25.pcm"

Crown_Wave_Sine::
//BYTE $86 $53 $21 $10 $00 $11 $23 $56 $79 $ac $de $ef $ff $ee $dc $a9
	.incbin "sound/programmable_wave_samples/26.pcm"

Crown_Wave_Saw::
//BYTE $88 $99 $aa $bb $cc $dd $ee $ff $00 $11 $22 $33 $44 $55 $66 $77
	.incbin "sound/programmable_wave_samples/27.pcm"

Crown_Wave_Triangle::
//BYTE $89 $ab $cd $ef $fe $dc $ba $98 $76 $54 $32 $10 $01 $23 $45 $67
	.incbin "sound/programmable_wave_samples/28.pcm"

Crown_Wave_SqFilter::
//BYTE $af $a7 $87 $af $50 $58 $78 $50 $af $a7 $87 $af $50 $58 $78 $50
	.incbin "sound/programmable_wave_samples/29.pcm"
