#ifndef GUARD_CONSTANTS_ACCEPT_H
#define GUARD_CONSTANTS_ACCEPT_H

enum AcceptWindows
{
    ACCEPT_WINDOW_ANIMATION,
    ACCEPT_WINDOW_EMAIL,
    ACCEPT_WINDOW_HELPBAR,
    ACCEPT_WINDOW_COUNT,
};

enum AcceptBackgrounds
{
    BG0_ACCEPT_TEXT,
    BG1_ACCEPT_DESKTOP,
    BG2_ACCEPT_BACKGROUND,
    BG_ACCEPT_COUNT,
};


#define ACCEPT_MOUSE_FIRST_APPEAR_FRAME_COUNT     1
#define ACCEPT_MOUSE_MOVE_0_FRAME_COUNT           (ACCEPT_MOUSE_FIRST_APPEAR_FRAME_COUNT + 36)
#define ACCEPT_MOUSE_MOVE_1_FRAME_COUNT           (ACCEPT_MOUSE_MOVE_0_FRAME_COUNT + 4)
#define ACCEPT_MOUSE_MOVE_2_FRAME_COUNT           (ACCEPT_MOUSE_MOVE_1_FRAME_COUNT + 4)
#define ACCEPT_MOUSE_MOVE_3_FRAME_COUNT           (ACCEPT_MOUSE_MOVE_2_FRAME_COUNT + 4)
#define ACCEPT_MOUSE_MOVE_4_FRAME_COUNT           (ACCEPT_MOUSE_MOVE_3_FRAME_COUNT + 4)
#define ACCEPT_MOUSE_MOVE_5_FRAME_COUNT           (ACCEPT_MOUSE_MOVE_4_FRAME_COUNT + 4)
#define ACCEPT_MOUSE_MOVE_6_FRAME_COUNT           (ACCEPT_MOUSE_MOVE_5_FRAME_COUNT + 4)
#define ACCEPT_MOUSE_STOP_FRAME_COUNT             (ACCEPT_MOUSE_MOVE_6_FRAME_COUNT + 10)
#define ACCEPT_MOUSE_CLICK_FRAME_COUNT            (ACCEPT_MOUSE_STOP_FRAME_COUNT + 10)
#define ACCEPT_MOUSE_SECOND_APPEAR_FRAME_COUNT    (ACCEPT_MOUSE_CLICK_FRAME_COUNT + 9)
#define ACCEPT_MOUSE_DESTROY_FRAME_COUNT          (ACCEPT_MOUSE_SECOND_APPEAR_FRAME_COUNT + 9)
#define ACCEPT_EMAIL_OPEN_0_FRAME_COUNT           (ACCEPT_MOUSE_DESTROY_FRAME_COUNT + 9)
#define ACCEPT_EMAIL_OPEN_1_FRAME_COUNT           (ACCEPT_EMAIL_OPEN_0_FRAME_COUNT + 2)
#define ACCEPT_EMAIL_OPEN_2_FRAME_COUNT           (ACCEPT_EMAIL_OPEN_1_FRAME_COUNT + 2)
#define ACCEPT_EMAIL_OPEN_3_FRAME_COUNT           (ACCEPT_EMAIL_OPEN_2_FRAME_COUNT + 2)
#define ACCEPT_EMAIL_CURSOR_WHITE_0_FRAME_COUNT   (ACCEPT_EMAIL_OPEN_3_FRAME_COUNT + 48)
#define ACCEPT_EMAIL_CURSOR_GRAY_0_FRAME_COUNT    (ACCEPT_EMAIL_CURSOR_WHITE_0_FRAME_COUNT + 10)
#define ACCEPT_EMAIL_CURSOR_WHITE_1_FRAME_COUNT   (ACCEPT_EMAIL_CURSOR_GRAY_0_FRAME_COUNT + 10)
#define ACCEPT_EMAIL_TEXT_APPEAR_FRAME_COUNT      (ACCEPT_EMAIL_CURSOR_WHITE_1_FRAME_COUNT + 72)

enum AcceptFontColors
{
    ACCEPT_FONT_COLOR_BLACK,
    ACCEPT_FONT_COLOR_WHITE,
};

#define FONT_ACCEPT_EMAIL FONT_NORMAL
#define FONT_ACCEPT_HELP_BAR FONT_SMALL_NARROW

#define PAL_ACCEPT_UI_SPRITES 123
#define ACCEPT_SPRITETAG 2512

enum AcceptSpriteTags
{
    ACCEPT_SPRITE_MOUSE,
    ACCEPT_SPRITE_SCROLLBAR,
    ACCEPT_SPRITE_COUNT,
};

#define ACCEPT_GFXTAG_MOUSE (ACCEPT_SPRITETAG + ACCEPT_SPRITE_MOUSE)
#define ACCEPT_GFXTAG_SCROLLBAR (ACCEPT_SPRITETAG + ACCEPT_SPRITE_SCROLLBAR)

#define PAL_SLOT_ACCEPT_UI BG_PLTT_ID(0)
#define PAL_SLOT_EMAIL BG_PLTT_ID(1)
#define PAL_SLOT_TEXT BG_PLTT_ID(15)

#define MAX_EMAIL_LINES 8
#define MAX_DEV_LINES 9

#define MIN_ACCEPT_SCROLLBAR_Y 36
#define MOVEABLE_AREA_ACCEPT_SCROLLBAR 104

#define ACCEPT_EMAIL_PALETTE_BLACK 10
#define ACCEPT_EMAIL_TEXT_WHITE 6

#endif // GUARD_CONSTANTS_ACCEPT_H
