#ifndef GUARD_ADVENTURE_GUIDES_H
#define GUARD_ADVENTURE_GUIDES_H

enum AdventureGuideList
{
    GUIDE_YOUR_ADVENTURE_GUIDE,
    GUIDE_WILD_POKEMON,
    GUIDE_YOUR_ROTOM_PHONE,
    GUIDE_AUTO_HEAL,
    GUIDE_OPENING_POKEDEX,
    GUIDE_LETS_GO,
    GUIDE_YOUR_POKEMON_BOXES,
    GUIDE_LOCKING_ON,
    GUIDE_CROUCHING,
    GUIDE_NO_IDEA_1,
    GUIDE_CATCHING_POKEMON,
    GUIDE_NO_IDEA_2,
    GUIDE_SOMETHING_1,
    GUIDE_SOMETHING_2,
    GUIDE_SOMETHING_3,
    GUIDE_SOMETHING_4,
    GUIDE_SOMETHING_5,
    GUIDE_SOMETHING_6,
    NUM_GUIDES,
};

#define MAX_ADVENTURE_GUIDE_ROWS_ON_SCREEN 8
#define MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW  2
#define MAX_ADVENTURE_GUIDE_ITEMS          MAX_ADVENTURE_GUIDE_ROWS_ON_SCREEN * MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW
#define MAX_ADVENTURE_GUIDE_ROWS           NUM_GUIDES / MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW
#define VAR_ADVENTURE_GUIDE_TO_OPEN        VAR_TEMP_0 // To change

#endif //GUARD_ADVENTURE_GUIDES_H
