
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

// Start siliconFrontier
/*
#define PARTNER_NONE 0
#define PARTNER_STEVEN 1
#define PARTNER_COUNT 2
*/

enum
{
    PARTNER_NONE,
    PARTNER_STEVEN,
    PARTNER_BAIYA,
    PARTNER_CHARLOTTE,
    PARTNER_TALA,
    PARTNER_FRANK,
    PARTNER_ELEANOR,
    PARTNER_MAGNUS,
    PARTNER_ADAORA,
    PARTNER_OLIVER,
    PARTNER_DOYLE,
    PARTNER_IMELDA,
    PARTNER_KEI_YING,
    PARTNER_BELEN,
    PARTNER_SHINZO,
    PARTNER_EMRYS,
    PARTNER_PUA,
    PARTNER_NERIENE,
    PARTNER_DIMU,
    PARTNER_BD,
    PARTNER_AMIARGENTO,
    PARTNER_COUNT,
};
// End siliconFrontier

#endif  // GUARD_CONSTANTS_BATTLE_PARTNERS_H
