#ifndef GUARD_CONSTANTS_BUZZR_H
#define GUARD_CONSTANTS_BUZZR_H

enum BuzzrUserIds
{
    BUZZR_USER_PLAYER,
    BUZZR_USER_PLACEHOLDER,
    BUZZR_USER_OLIVER,
    BUZZR_USER_FRANK,
    BUZZR_USER_RAMESH,
    BUZZR_USER_BAIYA,
    BUZZR_USER_VAUGHN,
    BUZZR_USER_BELEN,
    BUZZR_USER_SHINZO,
    BUZZR_USER_EMRYS,
    BUZZR_USER_PUA,
    BUZZR_USER_NERIENE,
    BUZZR_USER_DIMU,
    BUZZR_USER_BD,
    BUZZR_USER_AMI,
    BUZZR_USER_GRUNT,
    BUZZR_USER_NEWS,
    BUZZR_USER_TIDE_EVENT_BOT,
    BUZZR_USER_RSPCP,
    BUZZR_USER_SHARPRISECAPTIAL,
    BUZZR_USER_TALA,
    BUZZR_USER_MAGNUS,
    BUZZR_USER_VIGRIM,
    BUZZR_USER_DOYLE,
    BUZZR_USER_IMELDA,
    BUZZR_USER_ELEANOR,
    BUZZR_USER_KEI_YING,
    BUZZR_USER_ADAORA,
    BUZZR_USER_CHARLOTTE,
    BUZZR_USER_LUCREZIA,
    BUZZR_USER_COUNT,
};

// Constants for Tweet
// constant naming convention
// TWEET_context_author_summary
// example:
// TWEET_STORY_KEI_YING_LUCREZIADIDIT
// TWEET_QUESTS_NPC_HELPME
// TWEET_FLAVOR_NPC_TOPPERCENT

enum BuzzrZapIds
{
    TWEET_NONE,
    TWEET_QUEST_NPC_RABIES,
    TWEET_SAMPLE_2,
    TWEET_QUEST_NPC_SMOOTHIE,
    TWEET_QUEST_NPC_DEOXYS,
    TWEET_QUEST_NPC_TUNNELS,
    TWEET_QUEST_NPC_FRESHWATER,
    TWEET_QUEST_NPC_STONE,
    TWEET_GYM_MERMEREZA_CITY_BADGE,
    TWEET_GYM_TORA_TOWN_BADGE,
    TWEET_GYM_PERLACIA_CITY_BADGE,
    TWEET_GYM_CHASILLA_BADGE,
    TWEET_GYM_FORT_YOBU_BADGE,
    TWEET_GYM_HALERBA_CITY_BADGE,
    TWEET_GYM_TIRABUDIN_PLACE_BADGE,
    TWEET_GYM_IRISINA_TOWN_BADGE,
    TWEET_STORY_GRUNT_RESTORED,
    TWEET_STORY_STRIKE_BEGIN_1,
    TWEET_STORY_STRIKE_BEGIN_2,
    TWEET_STORY_WAREHOUSE_RAVE,
    TWEET_STORY_EPILOGUE,
    TWEET_QUEST_NOPODMOD_1,
    TWEET_QUEST_NOPODMOD_2,
    TWEET_QUEST_NPC_RABIES_COMPLETE,
    TWEET_QUEST_NPC_SMOOTHIE_COMPLETE,
    TWEET_QUEST_NPC_PSYOP,
    TWEET_QUEST_NPC_PSYOP_ACTIVE_A,
    TWEET_QUEST_NPC_PSYOP_ACTIVE_B,
    TWEET_QUEST_NPC_PSYOP_ACTIVE_C,
    TWEET_QUEST_NPC_PSYOP_COMPLETE,
    TWEET_STORY_FALSETIMELINE,
    TWEET_COUNT,
};

#define USER_MAX_LENGTH 40
#define MAX_NUM_TWEETS_SHOWN 3

#define FONT_BUZZR_BAR FONT_SMALL_NARROW
#define FONT_BUZZR_TWEET FONT_SMALL
#define FONT_BUZZR_METRICS FONT_NORMAL
#define FONT_BUZZR_USER FONT_NORMAL

#define ICON_SPACING 3
#define BAR_LEFT_PADDING 4
#define BAR_TOP_PADDING 1
#define TWEET_HEADER_LEFT_PADDING 6
#define TWEET_HEADER_TOP_PADDING 16
#define TWEET_ICON_HEIGHT 11
#define TWEET_ICON_WIDTH TWEET_ICON_HEIGHT
#define VERIFIED_ICON_WIDTH 16
#define TWEET_ICON_PADDING_TOP 33
#define UP_DOWN_ARROW_X 110
#define BUZZR_UP_ARROW_Y 6
#define BUZZR_DOWN_ARROW_Y 135
#define CURSOR_X 5
#define CURSOR_Y 36
#define TWEET_MARGIN_BOTTOM 10
#define TWEET_CURSOR_MARGIN_TOP 22
#define TWEET_INDICATOR_X_POSITION 224
#define TWEET_MIN_NUM_LINES 2
#define TWEET_MAX_NUM_LINES 7
#define TIMELINE_PRINT_HEIGHT 146
#define MILLISECOND_400 48
#define BUZZR_TIMELINE_TOP 0
#define SORT_MODE_TEXT_X_POSITION 80
#define TWEET_TOP_LEFT_OFFSET 60
#define TWEET_LAST_TILE_OFFSET 540
#define TWEET_BYTES_PER_ROW (DISPLAY_TILE_WIDTH * TILE_SIZE_4BPP)
#define BUZZR_QUEST_SPRITE_INITAL_POSITION -64
#define BUZZR_QUEST_SPRITE_MOVEMENT_SPEED 32
#define BUZZR_QUESTS_SPRITE_TIMER 40

#define FLAG_QUEST_FANFARE FLAG_TEMP_1

#define TWEET_BITS 32
#define NUM_TWEET_BITS (TWEET_COUNT / TWEET_BITS)

#define BUZZR_HEADER_FRAME(name) (BUZZR_SPRITE_FILTER_ ## name * 4)

enum BuzzrZapActions
{
    GET_READ,
    MARK_READ,
    SHOW_TWEET,
    HIDE_TWEET,
    CHECK_PIC,
    SHOW_PIC,
};

enum BuzzrZapMode
{
    MODE_OVERWORLD,
    MODE_TIMELINE,
};

#define TWEET_SOCIAL_MEDIA_STEPS 20
#define TWEET_WINDOW_WIDTH 219

#endif // GUARD_CONSTANTS_BUZZR_H
