#ifndef GUARD_CONSTANTS_BUZZR_H
#define GUARD_CONSTANTS_BUZZR_H

enum BuzzrUserIds
{
    BUZZR_USER_PLAYER,
    BUZZR_USER_OLIVER,
    BUZZR_USER_FRANK,
    BUZZR_USER_RAMESH,
    BUZZR_USER_BAIYA,
    BUZZR_USER_BELEN,
    BUZZR_USER_SHINZO,
    BUZZR_USER_EMRYS,
    BUZZR_USER_PUA,
    BUZZR_USER_NERIENE,
    BUZZR_USER_DIMU,
    BUZZR_USER_BD,
    BUZZR_USER_AMI,
    BUZZR_USER_GRUNT,
    BUZZR_USER_NEWS,
    BUZZR_USER_TIDE_EVENT_BOT,
    BUZZR_USER_RSPCP,
    BUZZR_USER_SHARPRISECAPTIAL,
    BUZZR_USER_TALA,
    BUZZR_USER_MAGNUS,
    BUZZR_USER_VIGRIM,
    BUZZR_USER_DOYLE,
    BUZZR_USER_IMELDA,
    BUZZR_USER_ELEANOR,
    BUZZR_USER_KEI_YING,
    BUZZR_USER_ADAORA,
    BUZZR_USER_CHARLOTTE,
    BUZZR_USER_LUCREZIA,
    BUZZR_USER_RESTAURANTEXPANSIONBUSSER,
    BUZZR_USER_JOHNNY,
    BUZZR_USER_SOCIETY,
    BUZZR_USER_WATCHVIBES,
    BUZZR_USER_LEAVERRA_RNGRS,
    BUZZR_USER_INSTALLNATUREPROBESWORKER,
    BUZZR_USER_SHARPRISE_EMPLOYEE_A,
    BUZZR_USER_ELDERLY,
    BUZZR_USER_ELDERLY_B,
    BUZZR_USER_RANDOM_MIDDLE_AGED,
    BUZZR_USER_SHARPRISE_LEAGUE_A,
    BUZZR_USER_GIRL,
    BUZZR_USER_PLACEHOLDER,
    BUZZR_USER_COUNT,
};

// Constants for Zap
// constant naming convention
// ZAP_context_author_summary
// example:
// ZAP_STORY_KEI_YING_LUCREZIADIDIT
// ZAP_QUESTS_NPC_HELPME
// ZAP_FLAVOR_NPC_TOPPERCENT

enum BuzzrZapIds // CANNOT EXCEED 254
{
    ZAP_NONE,
    ZAP_SHARPRISE_FLOWN,
    ZAP_INVASIVE_POKEMON,
    ZAP_NEW_TRAINERS,
    ZAP_LEAGUE_PROSPECTS,
    ZAP_STARTING_GUN,
    ZAP_QUEST_RETURNDOLL,
    ZAP_GYM_MERMEREZA_CITY_BADGE,
    ZAP_BELEN_BYSTANDER,
    ZAP_BAIYA_CHEWING,
    ZAP_CAPHE_QUEUE,
    ZAP_GYM_TORA_TOWN_BADGE,
    ZAP_SHINZO_BYSTANDER,
    ZAP_CHARLOTTE_PRODIGY,
    ZAP_POPIDORA_FREAKS,
    ZAP_PLAYER_POLICE,
    ZAP_GO_GOGGLES,
    ZAP_GYM_PERLACIA_CITY_BADGE,
    ZAP_EMRYS_BYSTANDER,
    ZAP_LUCREZIA_EMRYS,
    ZAP_BAIYA_CUSTOMS,
    ZAP_RAMESH_THANKS,
    ZAP_CURENO_TIDE,
    ZAP_QUEST_DIGGINGUPADAORASDIRT_2,
    ZAP_STORY_GRUNT_RESTORED,
    ZAP_QUEST_CULTURAL_PURITY_READYA, // lifestyle
    ZAP_CHARLOTTE_WINNING,
    ZAP_POMEG_SPICY, // lifestyle
    ZAP_GYM_CHASILLA_BADGE,
    ZAP_NEEDLES_REVIEW, // lifestyle
    ZAP_PUA_BYSTANDER,
    ZAP_COLD_COAST, // lifestyle
    ZAP_ADAORA_TRUST,
    ZAP_QUEST_RESTAURANTEXPANSION1_1,
    ZAP_QUEST_RESTAURANTEXPANSION1_2,
    ZAP_QUEST_RESTAURANTEXPANSION1_3,
    ZAP_QUEST_RESTAURANTEXPANSION2,
    ZAP_QUEST_KITCHENVOLUNTEERING,
    ZAP_QUEST_CULTURAL_PURITY_READYD_CHAMPION,
    ZAP_QUEST_CULTURAL_PURITY_READYD,
    ZAP_SHEER_COLD, // lifestyle
    ZAP_QUEST_HYBRID_CULTURE_LISTICLE_INTRO,
    ZAP_QUEST_HYBRID_CULTURE_LISTICLE_1,
    ZAP_QUEST_HYBRID_CULTURE_LISTICLE_2,
    ZAP_QUEST_HYBRID_CULTURE_LISTICLE_3,
    ZAP_QUEST_HYBRID_CULTURE_LISTICLE_4,
    ZAP_QUEST_HYBRID_CULTURE_LISTICLE_5,
    ZAP_QUEST_HYBRID_CULTURE_SHINZO_1,
    ZAP_RAMESH_ANDROID, // lifestyle
    ZAP_QUEST_HYBRID_CULTURE_SHINZO_2,
    ZAP_QUEST_NPC_PSYOP_ACTIVE_A, // lifestyle
    ZAP_QUEST_HYBRID_CULTURE_SHINZO_3,
    ZAP_QUEST_DIGGINGUPADAORASDIRT_4, // lifestyle
    ZAP_QUEST_HYBRID_CULTURE_SHINZO_4,
    ZAP_QUEST_FREETHEINNOCENT_3, // lifestyle
    ZAP_QUEST_HYBRID_CULTURE_SHINZO_5,
    ZAP_QUEST_NOPODMOD_2, // lifestyle
    ZAP_GYM_FORT_YOBU_BADGE,
    ZAP_IRISINA_QUEER, // lifestyle
    ZAP_NERIENE_BYSTANDER,
    ZAP_QUEST_NPC_STONE, // lifestyle
    ZAP_KEIYING_YOBU,
    ZAP_BURN_HEAL, // lifestyle
    ZAP_KEIYING_COMPETITIVE,
    ZAP_SHINJI_BUDGET, // lifestyle
    ZAP_QUEST_IMPROVBATTLING_ACTIVE,
    ZAP_LUCREZIA_JOB, // lifestyle
    ZAP_CHARLOTTE_PLAYER,
    ZAP_ALT_GIRL, // lifestyle
    ZAP_GYM_HALERBA_CITY_BADGE,
    ZAP_CLUTCH_PRIORITY, // lifestyle
    ZAP_DIMU_BYSTANDER,
    ZAP_CAPHE_ESPULEE, // lifestyle
    ZAP_STORY_STRIKE_BEGIN_1,
    ZAP_QUEST_CULTURAL_PURITY_AD2, // lifestyle
    ZAP_STORY_STRIKE_BEGIN_2,
    ZAP_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_1, // lifestyle
    ZAP_TALA_FIRED,
    ZAP_DEVON_CORP, // lifestyle
    ZAP_BAIYA_TALA,
    ZAP_QUEST_NOPODMOD_1, // lifestyle
    ZAP_GYM_TIRABUDIN_PLACE_BADGE,
    ZAP_GALAR_LEG, // lifestyle
    ZAP_BD_BYSTANDER,
    ZAP_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_2, // lifestyle
    ZAP_PLAYER_PRESENCE,
    ZAP_QUEST_NPC_RABIES, // lifestyle
    ZAP_GYM_IRISINA_TOWN_BADGE,
    ZAP_QUEST_NPC_RABIES_COMPLETE, // lifestyle
    ZAP_AMI_BYSTANDER,
    ZAP_IRISINA_BALL, // lifestyle
    ZAP_TIDE_CONSTRUCTION,
    ZAP_BD_POPPERS, // lifestyle
    ZAP_CHAMPIONSHIP_DELAYED,
    ZAP_BATON_PASS, // lifestyle
    ZAP_CHARLOTTE_RANDOM,
    ZAP_PIOCA_FIREWORKS, // lifestyle
    ZAP_BAIYA_WINNING,
    ZAP_QUEST_NPC_PSYOP_ACTIVE_C, // lifestyle
    ZAP_STORY_SUMMON,
    ZAP_CURENO_ANKLE, // lifestyle
    ZAP_SUMMON_RESPONSE,
    ZAP_CAPHE_MORRIS, // lifestyle
    ZAP_QUEST_NPC_RANGERS_HIRING,
    ZAP_QUEST_FREETHEINNOCENT_4, // lifestyle
    ZAP_QUEST_NPC_INSTALLNATUREPROBESWORKER_JOBHUNTING,
    ZAP_ELEANOR_REMEMBER, // lifestyle
    ZAP_HACK_PSA,
    ZAP_ADAORA_ZODIAC, // lifestyle
    ZAP_SHAPRRISE_HACK,
    ZAP_QUEST_CULTURAL_PURITY_READYB, // lifestyle
    ZAP_SHAPRIRSE_HACK_2,
    ZAP_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_4, // lifestyle
    ZAP_SHAPRRISE_HACK_3,
    ZAP_QUEST_CULTURAL_PURITY_AD, // lifestyle
    ZAP_SHAPRRISE_HACK_4,
    ZAP_QUEST_NPC_FRESHWATER, // lifestyle
    ZAP_SHARPRISE_HACK_5,
    ZAP_ARANTRAZ_SCANDAL, // lifestyle
    ZAP_SHARPRISE_HACK_6,
    ZAP_QUEST_NPC_SMOOTHIE, // lifestyle
    ZAP_RAID_PSA,
    ZAP_QUEST_NPC_SMOOTHIE_COMPLETE, // lifestyle
    ZAP_POLICE_TIDE,
    ZAP_QUEST_DIGGINGUPADAORASDIRT_1, // lifestyle
    ZAP_MEGACROSS_DEFENSE,
    ZAP_TIRABUDIN_ZINES2, // lifestyle
    ZAP_CHAMPIONSHIP_START,
    ZAP_KALOS_TOURIST, // lifestyle
    ZAP_BAIYA_TIDE,
    ZAP_QUEST_HANG20_ROCKY_COASTS, // lifestyle
    ZAP_PLAYER_SHARP,
    ZAP_BITE_MEGA, // lifestyle
    ZAP_SHARPRISE_FAN,
    ZAP_INKAY_HYPNOSIS, // lifestyle
    ZAP_FANTASY_LEAGUE,
    ZAP_QUEST_IMPROVBATTLING_COMPLETE, // lifestyle
    ZAP_PLAYER_CHAMPION,
    ZAP_LONG_BATTLE, // lifestyle
    ZAP_OUTSIDER_CHAMPION,
    ZAP_QUEST_FREETHEINNOCENT_2, // lifestyle
    ZAP_SICK_FINALS,
    ZAP_QUEST_CULTURAL_PURITY_AD3, // lifestyle
    ZAP_PLAYER_BREAK,
    ZAP_QUEST_NPC_PSYOP_ACTIVE_B, // lifestyle
    ZAP_PLAYER_BAIYA,
    ZAP_BAIYA_MAINCHARACTER, // lifestyle
    ZAP_ESPULEE_SHELL,
    ZAP_OLD_BUZZR, // lifestyle
    ZAP_QUEST_RESTOREESPULEEGYM_ACTIVE,
    ZAP_MIME_WALLS, // lifestyle
    ZAP_QUEST_RESTOREESPULEEGYM_COMPLETE_BAIYA,
    ZAP_TIRABUDIN_ZINES, // lifestyle
    ZAP_QUEST_RESTOREESPULEEGYM_COMPLETE_IMELDA,
    ZAP_PRESTO_CREEPY, // lifestyle
    ZAP_QUEST_RESTOREZENZUISLAND_ACTIVE,
    ZAP_QUEST_NPC_DEOXYS, // lifestyle
    ZAP_ZENZU_MOVING,
    ZAP_TORA_MOCHI, // lifestyle
    ZAP_QUEST_RESTOREZENZUISLAND_COMPLETE_BAIYA,
    ZAP_QUEST_DIGGINGUPADAORASDIRT_3, // lifestyle
    ZAP_QUEST_RESTOREZENZUISLAND_COMPLETE_DOYLE,
    ZAP_CHARLOTTE_TRASH, // lifestyle
    ZAP_QUEST_RESTOREHODOUCITY_ASSIGNED_RESTORATION,
    ZAP_ADAORA_MIDRIFF, // lifestyle
    ZAP_QUEST_RESTOREHODOUCITY_FOUND_LEADER,
    ZAP_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_3, // lifestyle
    ZAP_HODOU_JOHNNY,
    ZAP_QUEST_NPC_PSYOP_COMPLETE, // lifestyle
    ZAP_QUEST_RESTOREHODOUCITY_COMPLETE_JOHNNY,
    ZAP_VICTORY_TACO, // lifestyle
    ZAP_QUEST_RESTOREHODOUCITY_COMPLETE_RANDOM,
    ZAP_FRANK_CASUAL, // lifestyle
    ZAP_TRAINING_VIBE,
    ZAP_EARTHQUAKE_PANIC, // lifestyle
    ZAP_ARANTRAZ_UNSETTLING,
    ZAP_ASSES_TEAM, // lifestyle
    ZAP_STORY_FALSETIMELINE,
    ZAP_STORY_FALSETIMELINE_2,
    ZAP_PINTILLION_SPEWPA, // lifestyle
    ZAP_HODOU_FIGHT,
    ZAP_QUEST_CULTURAL_PURITY_READYC, // lifestyle
    ZAP_POLICE_BRUTE,
    ZAP_BD_MULTITASK, // lifestyle
    ZAP_TIDE_RIOTS,
    ZAP_DOYLE_CRINGE, // lifestyle
    ZAP_SHARPRISE_FAR,
    ZAP_QUEST_TEACHATRAINERTOFISH_FISHERFOLK, // lifestyle
    ZAP_TIDE_DONE,
    ZAP_QUEST_NPC_TUNNELS, // lifestyle
    ZAP_TIDE_RUBBISH,
    ZAP_DUSK_STONE, // lifestyle
    ZAP_PLAYER_RANCID,
    ZAP_QUEST_NPC_PSYOP, // lifestyle
    ZAP_CREEPY_LADY,
    ZAP_BUZZR_MISINFORMATION, // lifestyle
    ZAP_TORGEOT_CHILLS,
    ZAP_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_5, // lifestyle
    ZAP_STORY_WAREHOUSE_RAVE,
    ZAP_HANO_BEACH, // lifestyle
    ZAP_QUEST_FREETHEINNOCENT_5,
    ZAP_QUEST_TEACHATRAINERTOFISH_DOCUMENTARY, // lifestyle
    ZAP_QUEST_FINDTHEGUILTY_1,
    ZAP_DRILBUR_EVOLVE, // lifestyle
    ZAP_SHARPRISE_BOYCOTT,
    ZAP_STAT_CHANGE, // lifestyle
    ZAP_CHAMP_CHEATED,
    ZAP_QUEST_FREETHEINNOCENT_1, // lifestyle
    ZAP_E4_WATCH,
    ZAP_DIMU_DISCOURSE, // lifestyle
    ZAP_BAIYA_BUDDY,
    ZAP_GOLD_BREEDING, // lifestyle
    ZAP_BODEGA_SHOUTOUT,
    ZAP_YOBU_PIOCA, // lifestyle
    ZAP_HALAI_NIGHTMARE,
    ZAP_FRANK_CAREFREE, // lifestyle
    ZAP_BAD_EARTHQUAKE,
    ZAP_BAIYA_RUDE, // lifestyle
    ZAP_HALAI_RECONSTRUCTION,
    ZAP_QUEST_HANG20_WARNING, // lifestyle
    ZAP_CHASILLA_EARTHQUAKE,
    ZAP_HALAI_AID,
    ZAP_OLD_E4,
    ZAP_FIRST_PROTEST,
    ZAP_HUGE_TURNOUT,
    ZAP_STORY_EPILOGUE,
    ZAP_CHAMP_STORMED,
    ZAP_COUNT,
}; // CANNOT EXCEED 254

#define USER_MAX_LENGTH 40
#define MAX_NUM_ZAPS_SHOWN 3

#define FONT_BUZZR_BAR FONT_SMALL_NARROW
#define FONT_BUZZR_ZAP FONT_SMALL
#define FONT_BUZZR_METRICS FONT_NORMAL
#define FONT_BUZZR_USER FONT_NORMAL

#define ICON_SPACING 3
#define BAR_LEFT_PADDING 4
#define BAR_TOP_PADDING 1
#define ZAP_HEADER_LEFT_PADDING 6
#define ZAP_HEADER_TOP_PADDING 16
#define ZAP_ICON_HEIGHT 11
#define ZAP_ICON_WIDTH ZAP_ICON_HEIGHT
#define VERIFIED_ICON_WIDTH 16
#define ZAP_ICON_PADDING_TOP 33
#define UP_DOWN_ARROW_X 110
#define BUZZR_UP_ARROW_Y 6
#define BUZZR_DOWN_ARROW_Y 135
#define CURSOR_X 5
#define CURSOR_Y 36
#define ZAP_MARGIN_BOTTOM 10
#define ZAP_CURSOR_MARGIN_TOP 22
#define ZAP_INDICATOR_X_POSITION 224
#define ZAP_MIN_NUM_LINES 2
#define ZAP_MAX_NUM_LINES 7
#define TIMELINE_PRINT_HEIGHT 146
#define MILLISECOND_400 48
#define BUZZR_TIMELINE_TOP 0
#define SORT_MODE_TEXT_X_POSITION 80
#define ZAP_TOP_LEFT_OFFSET 60
#define ZAP_LAST_TILE_OFFSET 540
#define ZAP_BYTES_PER_ROW (DISPLAY_TILE_WIDTH * TILE_SIZE_4BPP)
#define BUZZR_QUEST_SPRITE_INITAL_POSITION -64
#define BUZZR_QUEST_SPRITE_MOVEMENT_SPEED 32
#define BUZZR_QUESTS_SPRITE_TIMER 40

#define FLAG_QUEST_FANFARE FLAG_TEMP_1

#define ZAP_BITS 32
#define NUM_ZAP_BITS ((ZAP_COUNT + ZAP_BITS - 1) / ZAP_BITS)

#define BUZZR_HEADER_FRAME(name) (BUZZR_SPRITE_FILTER_ ## name * 4)

enum BuzzrZapActions
{
    GET_READ,
    MARK_READ,
    SHOW_ZAP,
    HIDE_ZAP,
    CHECK_PIC,
    SHOW_PIC,
};

enum BuzzrZapMode
{
    MODE_OVERWORLD,
    MODE_TIMELINE,
};

#define ZAP_SOCIAL_MEDIA_STEPS 20
#define ZAP_CHATTER_STEPS 500
#define ZAP_WINDOW_WIDTH 219

#define ZAP_METRIC_WIDTH 21
#define ZAP_USERNAME_WIDTH 160


#endif // GUARD_CONSTANTS_BUZZR_H
