#ifndef GUARD_CONSTANTS_BUZZR_H
#define GUARD_CONSTANTS_BUZZR_H

enum BuzzrUserIds
{
    BUZZR_USER_PLAYER,
    BUZZR_USER_PLACEHOLDER,
    BUZZR_USER_OLIVER,
    BUZZR_USER_FRANK,
    BUZZR_USER_RAMESH,
    BUZZR_USER_BAIYA,
    BUZZR_USER_VAUGHN,
    BUZZR_USER_BELEN,
    BUZZR_USER_SHINZO,
    BUZZR_USER_EMRYS,
    BUZZR_USER_PUA,
    BUZZR_USER_NERIENE,
    BUZZR_USER_DIMU,
    BUZZR_USER_BD,
    BUZZR_USER_AMI,
    BUZZR_USER_GRUNT,
    BUZZR_USER_NEWS,
    BUZZR_USER_TIDE_EVENT_BOT,
    BUZZR_USER_RSPCP,
    BUZZR_USER_SHARPRISECAPTIAL,
    BUZZR_USER_TALA,
    BUZZR_USER_MAGNUS,
    BUZZR_USER_VIGRIM,
    BUZZR_USER_DOYLE,
    BUZZR_USER_IMELDA,
    BUZZR_USER_ELEANOR,
    BUZZR_USER_KEI_YING,
    BUZZR_USER_ADAORA,
    BUZZR_USER_CHARLOTTE,
    BUZZR_USER_LUCREZIA,
    BUZZR_USER_RESTAURANTEXPANSIONBUSSER,
    BUZZR_USER_JOHNNY,
    BUZZR_USER_SOCIETY,
    BUZZR_USER_WATCHVIBES,
    BUZZR_USER_LEAVERRA_RNGRS,
    BUZZR_USER_INSTALLNATUREPROBESWORKER,
    BUZZR_USER_SHARPRISE_EMPLOYEE_A,
    BUZZR_USER_ELDERLY,
    BUZZR_USER_ELDERLY_B,
    BUZZR_USER_RANDOM_MIDDLE_AGED,
    BUZZR_USER_SHARPRISE_LEAGUE_A,
    BUZZR_USER_GIRL,
    BUZZR_USER_COUNT,
};

// Constants for Tweet
// constant naming convention
// TWEET_context_author_summary
// example:
// TWEET_STORY_KEI_YING_LUCREZIADIDIT
// TWEET_QUESTS_NPC_HELPME
// TWEET_FLAVOR_NPC_TOPPERCENT

enum BuzzrZapIds
{
    TWEET_NONE,
    TWEET_QUEST_NPC_RABIES,
    TWEET_STORY_EPILOGUE,
    TWEET_QUEST_NPC_SMOOTHIE,
    TWEET_QUEST_NPC_DEOXYS,
    TWEET_QUEST_NPC_TUNNELS,
    TWEET_QUEST_NPC_FRESHWATER,
    TWEET_QUEST_NPC_STONE,
    TWEET_GYM_MERMEREZA_CITY_BADGE,
    TWEET_GYM_TORA_TOWN_BADGE,
    TWEET_GYM_PERLACIA_CITY_BADGE,
    TWEET_GYM_CHASILLA_BADGE,
    TWEET_GYM_FORT_YOBU_BADGE,
    TWEET_GYM_HALERBA_CITY_BADGE,
    TWEET_GYM_TIRABUDIN_PLACE_BADGE,
    TWEET_GYM_IRISINA_TOWN_BADGE,
    TWEET_STORY_GRUNT_RESTORED,
    TWEET_STORY_STRIKE_BEGIN_1,
    TWEET_STORY_STRIKE_BEGIN_2,
    TWEET_STORY_WAREHOUSE_RAVE,
    TWEET_QUEST_NOPODMOD_1,
    TWEET_QUEST_NOPODMOD_2,
    TWEET_QUEST_NPC_RABIES_COMPLETE,
    TWEET_QUEST_NPC_SMOOTHIE_COMPLETE,
    TWEET_QUEST_NPC_PSYOP,
    TWEET_QUEST_NPC_PSYOP_ACTIVE_A,
    TWEET_QUEST_NPC_PSYOP_ACTIVE_B,
    TWEET_QUEST_NPC_PSYOP_ACTIVE_C,
    TWEET_QUEST_NPC_PSYOP_COMPLETE,
    TWEET_STORY_FALSETIMELINE,
    TWEET_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_1,
    TWEET_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_2,
    TWEET_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_3,
    TWEET_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_4,
    TWEET_QUEST_BETWEENASTONEANDAHARDPLACE_NPC_5,
    TWEET_QUEST_RESTAURANTEXPANSION1_1,
    TWEET_QUEST_RESTAURANTEXPANSION1_2,
    TWEET_QUEST_RESTAURANTEXPANSION1_3,
    TWEET_QUEST_DIGGINGUPADAORASDIRT_1,
    TWEET_QUEST_DIGGINGUPADAORASDIRT_2,
    TWEET_QUEST_DIGGINGUPADAORASDIRT_3,
    TWEET_QUEST_DIGGINGUPADAORASDIRT_4,
    TWEET_QUEST_RETURNDOLL,
    TWEET_QUEST_FREETHEINNOCENT_1,
    TWEET_QUEST_FREETHEINNOCENT_2,
    TWEET_QUEST_FREETHEINNOCENT_3,
    TWEET_QUEST_FREETHEINNOCENT_4,
    TWEET_QUEST_FREETHEINNOCENT_5,
    TWEET_QUEST_FINDTHEGUILTY_1,
    TWEET_QUEST_RESTAURANTEXPANSION2,
    TWEET_QUEST_KITCHENVOLUNTEERING,
    TWEET_QUEST_RESTOREESPULEEGYM_ACTIVE,
    TWEET_QUEST_RESTOREESPULEEGYM_COMPLETE_BAIYA,
    TWEET_QUEST_RESTOREESPULEEGYM_COMPLETE_IMELDA,
    TWEET_QUEST_RESTOREZENZUISLAND_ACTIVE,
    TWEET_QUEST_RESTOREZENZUISLAND_COMPLETE_BAIYA,
    TWEET_QUEST_RESTOREZENZUISLAND_COMPLETE_DOYLE,
    TWEET_QUEST_RESTOREHODOUCITY_ASSIGNED_RESTORATION,
    TWEET_QUEST_RESTOREHODOUCITY_FOUND_LEADER,
    TWEET_QUEST_RESTOREHODOUCITY_COMPLETE_RANDOM,
    TWEET_QUEST_RESTOREHODOUCITY_COMPLETE_JOHNNY,
    TWEET_QUEST_IMPROVBATTLING_ACTIVE,
    TWEET_QUEST_IMPROVBATTLING_COMPLETE,
    TWEET_QUEST_TEACHATRAINERTOFISH_FISHERFOLK,
    TWEET_QUEST_TEACHATRAINERTOFISH_DOCUMENTARY,
    TWEET_QUEST_HANG20_WARNING,
    TWEET_QUEST_HANG20_ROCKY_COASTS,
    TWEET_QUEST_CULTURAL_PURITY_AD,
    TWEET_QUEST_CULTURAL_PURITY_AD2,
    TWEET_QUEST_CULTURAL_PURITY_AD3,
    TWEET_QUEST_CULTURAL_PURITY_READYA,
    TWEET_QUEST_CULTURAL_PURITY_READYB,
    TWEET_QUEST_CULTURAL_PURITY_READYC,
    TWEET_QUEST_CULTURAL_PURITY_READYD,
    TWEET_QUEST_CULTURAL_PURITY_READYD_CHAMPION,
    TWEET_QUEST_HYBRID_CULTURE_LISTICLE_INTRO,
    TWEET_QUEST_HYBRID_CULTURE_LISTICLE_1,
    TWEET_QUEST_HYBRID_CULTURE_LISTICLE_2,
    TWEET_QUEST_HYBRID_CULTURE_LISTICLE_3,
    TWEET_QUEST_HYBRID_CULTURE_LISTICLE_4,
    TWEET_QUEST_HYBRID_CULTURE_LISTICLE_5,
    TWEET_QUEST_HYBRID_CULTURE_SHINZO_1,
    TWEET_QUEST_HYBRID_CULTURE_SHINZO_2,
    TWEET_QUEST_HYBRID_CULTURE_SHINZO_3,
    TWEET_QUEST_HYBRID_CULTURE_SHINZO_4,
    TWEET_QUEST_HYBRID_CULTURE_SHINZO_5,
    TWEET_QUEST_NPC_RANGERS_HIRING,
    TWEET_QUEST_NPC_INSTALLNATUREPROBESWORKER_JOBHUNTING,
    TWEET_ADAORA_MIDRIFF,
    TWEET_ADAORA_ZODIAC,
    TWEET_LUCREZIA_JOB,
    TWEET_ADAORA_TRUST,
    TWEET_ELEANOR_REMEMBER,
    TWEET_FRANK_CAREFREE,
    TWEET_BD_POPPERS,
    TWEET_NEEDLES_REVIEW,
    TWEET_CHARLOTTE_TRASH,
    TWEET_DIMU_DISCOURSE,
    TWEET_DOYLE_CRINGE,
    TWEET_BAIYA_RUDE,
    TWEET_BAIYA_MAINCHARACTER,
    TWEET_MEGACROSS_DEFENSE,
    TWEET_PLAYER_PRESENCE,
    TWEET_RAMESH_ANDROID,
    TWEET_BD_MULTITASK,
    TWEET_CAPHE_MORRIS,
    TWEET_YOBU_PIOCA,
    TWEET_IRISINA_QUEER,
    TWEET_TIRABUDIN_ZINES,
    TWEET_TIRABUDIN_ZINES2,
    TWEET_TORA_MOCHI,
    TWEET_BELEN_BYSTANDER,
    TWEET_SHINZO_BYSTANDER,
    TWEET_EMRYS_BYSTANDER,
    TWEET_PUA_BYSTANDER,
    TWEET_NERIENE_BYSTANDER,
    TWEET_DIMU_BYSTANDER,
    TWEET_BD_BYSTANDER,
    TWEET_AMI_BYSTANDER,
    TWEET_SHARPRISE_FLOWN,
    TWEET_INVASIVE_POKEMON,
    TWEET_NEW_TRAINERS,
    TWEET_LEAGUE_PROSPECTS,
    TWEET_STARTING_GUN,
    TWEET_BAIYA_CHEWING,
    TWEET_CAPHE_QUEUE,
    TWEET_CHARLOTTE_PRODIGY,
    TWEET_POPIDORA_FREAKS,
    TWEET_GO_GOGGLES,
    TWEET_SHINJI_BUDGET,
    TWEET_LUCREZIA_EMRYS,
    TWEET_BAIYA_CUSTOMS,
    TWEET_RAMESH_THANKS,
    TWEET_CURENO_TIDE,
    TWEET_CHARLOTTE_WINNING,
    TWEET_BAIYA_WINNING,
    TWEET_PLAYER_POLICE,
    TWEET_GOLD_BREEDING,
    TWEET_EARTHQUAKE_PANIC,
    TWEET_ARANTRAZ_SCANDAL,
    TWEET_LONG_BATTLE,
    TWEET_KEIYING_YOBU,
    TWEET_KEIYING_COMPETITIVE,
    TWEET_CHARLOTTE_PLAYER,
    TWEET_TALA_FIRED,
    TWEET_BAIYA_TALA,
    TWEET_TIDE_CONSTRUCTION,
    TWEET_GALAR_LEG,
    TWEET_CHAMPIONSHIP_DELAYED,
    TWEET_CHARLOTTE_RANDOM,
    TWEET_FRANK_CASUAL,
    TWEET_HACK_PSA,
    TWEET_SHAPRRISE_HACK,
    TWEET_RAID_PSA,
    TWEET_CHAMPIONSHIP_START,
    TWEET_POLICE_TIDE,
    TWEET_BAIYA_TIDE,
    TWEET_PLAYER_SHARP,
    TWEET_SHARPRISE_FAN,
    TWEET_SHAPRIRSE_HACK_2,
    TWEET_SHAPRRISE_HACK_3,
    TWEET_SHAPRRISE_HACK_4,
    TWEET_SHARPRISE_HACK_5,
    TWEET_SHARPRISE_HACK_6,
    TWEET_FANTASY_LEAGUE,
    TWEET_PLAYER_CHAMPION,
    TWEET_PLAYER_BREAK,
    TWEET_PLAYER_BAIYA,
    TWEET_HODOU_JOHNNY,
    TWEET_ZENZU_MOVING,
    TWEET_ESPULEE_SHELL,
    TWEET_TRAINING_VIBE,
    TWEET_ARANTRAZ_UNSETTLING,
    TWEET_HODOU_FIGHT,
    TWEET_POLICE_BRUTE,
    TWEET_TIDE_RIOTS,
    TWEET_SHARPRISE_FAR,
    TWEET_PLAYER_RANCID,
    TWEET_CREEPY_LADY,
    TWEET_TORGEOT_CHILLS,
    TWEET_SHARPRISE_BOYCOTT,
    TWEET_IRISINA_BALL,
    TWEET_E4_WATCH,
    TWEET_BAIYA_BUDDY,
    TWEET_CHAMP_CHEATED,
    TWEET_BUZZR_MISINFORMATION,
    TWEET_BODEGA_SHOUTOUT,
    TWEET_HALAI_NIGHTMARE,
    TWEET_HALAI_RECONSTRUCTION,
    TWEET_HALAI_AID,
    TWEET_OLD_E4,
    TWEET_FIRST_PROTEST,
    TWEET_HUGE_TURNOUT,
    TWEET_CHAMP_STORMED,
    TWEET_INKAY_HYPNOSIS,
    TWEET_ALT_GIRL,
    TWEET_CURENO_ANKLE,
    TWEET_KALOS_TOURIST,
    TWEET_BITE_MEGA,
    TWEET_TIDE_DONE,
    TWEET_TIDE_RUBBISH,
    TWEET_BAD_EARTHQUAKE,
    TWEET_CHASILLA_EARTHQUAKE,
    TWEET_OUTSIDER_CHAMPION,
    TWEET_SICK_FINALS,
    TWEET_PIOCA_FIREWORKS,
    TWEET_HANO_BEACH,
    TWEET_MIME_WALLS,
    TWEET_CAPHE_ESPULEE,
    TWEET_COLD_COAST,
    TWEET_DEVON_CORP,
    TWEET_VICTORY_TACO,
    TWEET_SHEER_COLD,
    TWEET_BURN_HEAL,
    TWEET_OLD_BUZZR,
    TWEET_PRESTO_CREEPY,
    TWEET_POMEG_SPICY,
    TWEET_DRILBUR_EVOLVE,
    TWEET_PINTILLION_SPEWPA,
    TWEET_BATON_PASS,
    TWEET_CLUTCH_PRIORITY,
    TWEET_ASSES_TEAM,
    TWEET_DUSK_STONE,
    TWEET_STAT_CHANGE,
    TWEET_COUNT,
};

#define USER_MAX_LENGTH 40
#define MAX_NUM_TWEETS_SHOWN 3

#define FONT_BUZZR_BAR FONT_SMALL_NARROW
#define FONT_BUZZR_TWEET FONT_SMALL
#define FONT_BUZZR_METRICS FONT_NORMAL
#define FONT_BUZZR_USER FONT_NORMAL

#define ICON_SPACING 3
#define BAR_LEFT_PADDING 4
#define BAR_TOP_PADDING 1
#define TWEET_HEADER_LEFT_PADDING 6
#define TWEET_HEADER_TOP_PADDING 16
#define TWEET_ICON_HEIGHT 11
#define TWEET_ICON_WIDTH TWEET_ICON_HEIGHT
#define VERIFIED_ICON_WIDTH 16
#define TWEET_ICON_PADDING_TOP 33
#define UP_DOWN_ARROW_X 110
#define BUZZR_UP_ARROW_Y 6
#define BUZZR_DOWN_ARROW_Y 135
#define CURSOR_X 5
#define CURSOR_Y 36
#define TWEET_MARGIN_BOTTOM 10
#define TWEET_CURSOR_MARGIN_TOP 22
#define TWEET_INDICATOR_X_POSITION 224
#define TWEET_MIN_NUM_LINES 2
#define TWEET_MAX_NUM_LINES 7
#define TIMELINE_PRINT_HEIGHT 146
#define MILLISECOND_400 48
#define BUZZR_TIMELINE_TOP 0
#define SORT_MODE_TEXT_X_POSITION 80
#define TWEET_TOP_LEFT_OFFSET 60
#define TWEET_LAST_TILE_OFFSET 540
#define TWEET_BYTES_PER_ROW (DISPLAY_TILE_WIDTH * TILE_SIZE_4BPP)
#define BUZZR_QUEST_SPRITE_INITAL_POSITION -64
#define BUZZR_QUEST_SPRITE_MOVEMENT_SPEED 32
#define BUZZR_QUESTS_SPRITE_TIMER 40

#define FLAG_QUEST_FANFARE FLAG_TEMP_1

#define TWEET_BITS 32
#define NUM_TWEET_BITS ((TWEET_COUNT + TWEET_BITS - 1) / TWEET_BITS)

#define BUZZR_HEADER_FRAME(name) (BUZZR_SPRITE_FILTER_ ## name * 4)

enum BuzzrZapActions
{
    GET_READ,
    MARK_READ,
    SHOW_TWEET,
    HIDE_TWEET,
    CHECK_PIC,
    SHOW_PIC,
};

enum BuzzrZapMode
{
    MODE_OVERWORLD,
    MODE_TIMELINE,
};

#define TWEET_SOCIAL_MEDIA_STEPS 20
#define TWEET_WINDOW_WIDTH 219

#endif // GUARD_CONSTANTS_BUZZR_H
