#ifndef GUARD_COLOR_VARIATION_CONSTANTS_H
#define GUARD_COLOR_VARIATION_CONSTANTS_H

#define HUE_SHIFT_RANGE_NORMAL  40
#define HUE_SHIFT_RANGE_SHINY  30

enum NormalHueColors
{
    NORMAL_HUE_NEGATIVE_SHINY_HUE_POSITIVE = -1,
    NORMAL_HUE_BOTH_WAYS_SHINY_HUE_BOTH_WAYS,
    NORMAL_HUE_POSITIVE_SHINY_HUE_NEGATIVE,
    NORMAL_RGB_MODULATION_SHINY_HUE_BOTH_WAYS,
    NORMAL_HUE_BOTH_WAYS_SHINY_RGB_MODULATION,
    NORMAL_RGB_MODULATION_SHINY_RGB_MODULATION,
};


enum ColorVariationSource
{
    SOURCE_PID,
    SOURCE_IVS,
    SOURCE_NICKNAME_OT,
};

#endif // GUARD_COLOR_VARIATION_CONSTANTS_H
