#ifndef GUARD_CONSTANTS_DEXNAV_H
#define GUARD_CONSTANTS_DEXNAV_H

enum DexNavStars
{
    DEXNAV_STAR_0,
    DEXNAV_STAR_1,
    DEXNAV_STAR_2,
    DEXNAV_STAR_COUNT,
};

enum DexNavModes
{
    DEXNAV_MODE_MENU,
    DEXNAV_MODE_OVERWORLD,
    DEXNAV_MODE_SCAN,
};

#endif // GUARD_CONSTANTS_DEXNAV_H
