#ifndef GUARD_CONSTANTS_FERRY_H
#define GUARD_CONSTANTS_FERRY_H

#define FERRY_PORT_HALAI_ISLAND HEAL_LOCATION_FERRY_PORT_HALAI_ISLAND
#define FERRY_PORT_FERRYBUILDING HEAL_LOCATION_FERRY_PORT_FERRYBUILDING
#define FERRY_PORT_ARANTRAZ HEAL_LOCATION_ARANTRAZ
#define FERRY_PORT_POPIDORA_PIER HEAL_LOCATION_POPIDORA_PIER
#define FERRY_PORT_ESPULEE_OUTSKIRTS HEAL_LOCATION_FERRY_PORT_ESPULEE_OUTSKIRTS
#define FERRY_PORT_CHASILLA HEAL_LOCATION_FERRY_PORT_CHASILLA

#define FERRY_PORT_ID 0
#define FERRY_STATE 1
//#define FERRY_MAPGROUP 2
//#define FERRY_MAPNUM 3
#define FERRY_DESTINATION 2

#endif // GUARD_CONSTANTS_FERRY_H
