#ifndef GUARD_CONSTANTS_GIVE_NATIVE_ITEM_H
#define GUARD_CONSTANTS_GIVE_NATIVE_ITEM_H

#define NATIVE_ITEM_AMOUNT_DEFAULT 1
#define NATIVE_ITEM_AMOUNT_MAX 3

#define NATIVE_ITEM_BERRY_THRESHOLD 4

#define NATIVE_ITEM_GROUP_SIZE_MAX 23

#endif  // GUARD_CONSTANTS_GIVE_NATIVE_ITEM_H
