#ifndef GUARD_CONSTANTS_GLASS_H
#define GUARD_CONSTANTS_GLASS_H

#define GLASS_LOCATIONS_MAX_SHOWED 7

#define GLASS_TRAINER_TYPE_CONST    1000
#define GLASS_TRAINER_REMATCH_CONST 100
#define GLASS_TRAINER_HOVER_CONST   10
#define GLASS_TRAINER_STATE_CONST   1

#define GLASS_BOSS_CONST (GLASS_TRAINER_TYPE_CONST * GLASS_TRAINER_TYPE_BOSS)
#define GLASS_GYM_CONST (GLASS_TRAINER_TYPE_CONST * GLASS_TRAINER_TYPE_GYM)
#define GLASS_REGULAR_CONST (GLASS_TRAINER_TYPE_CONST * GLASS_TRAINER_TYPE_REGULAR)

#define GLASS_MARK_BOSS (GLASS_BOSS_CONST)
#define GLASS_MARK_BOSS_COMPLETE (GLASS_BOSS_CONST + GLASS_TRAINER_STATE_COMPLETE)
#define GLASS_MARK_BOSS_REMATCH (GLASS_BOSS_CONST + GLASS_TRAINER_REMATCH_CONST)
#define GLASS_MARK_BOSS_REMATCH_COMPLETE (GLASS_BOSS_CONST + GLASS_TRAINER_REMATCH_CONST + GLASS_TRAINER_STATE_COMPLETE)
#define GLASS_MARK_GYM (GLASS_GYM_CONST)
#define GLASS_MARK_GYM_COMPLETE (GLASS_GYM_CONST + GLASS_TRAINER_STATE_COMPLETE)
#define GLASS_MARK_GYM_REMATCH (GLASS_GYM_CONST + GLASS_TRAINER_REMATCH_CONST)
#define GLASS_MARK_GYM_REMATCH_COMPLETE (GLASS_GYM_CONST + GLASS_TRAINER_REMATCH_CONST + GLASS_TRAINER_STATE_COMPLETE)
#define GLASS_MARK_REGULAR (GLASS_REGULAR_CONST)
#define GLASS_MARK_REGULAR_COMPLETE (GLASS_REGULAR_CONST + GLASS_TRAINER_STATE_COMPLETE)
#define GLASS_MARK_REGULAR_REMATCH (GLASS_REGULAR_CONST + GLASS_TRAINER_REMATCH_CONST)
#define GLASS_MARK_REGULAR_REMATCH_COMPLETE (GLASS_REGULAR_CONST + GLASS_TRAINER_REMATCH_CONST + GLASS_TRAINER_STATE_COMPLETE)

#define PAL_GLASS_UI_SPRITES 123
#define GLASS_SPRITETAG 2512

#define GLASS_GFXTAG_LOCATION_UP_ARROW (GLASS_SPRITETAG + GLASS_SPRITE_LOCATION_UP_ARROW)
#define GLASS_GFXTAG_LOCATION_DOWN_ARROW (GLASS_SPRITETAG + GLASS_SPRITE_LOCATION_DOWN_ARROW)

#define GLASS_GFXTAG_TRAINER_UP_ARROW (GLASS_SPRITETAG + GLASS_SPRITE_TRAINER_UP_ARROW)
#define GLASS_GFXTAG_TRAINER_DOWN_ARROW (GLASS_SPRITETAG + GLASS_SPRITE_TRAINER_DOWN_ARROW)

#define GLASS_GFXTAG_MAP_CURSOR (GLASS_SPRITETAG + GLASS_SPRITE_MAP_CURSOR)
#define GLASS_GFXTAG_TRAINER_CURSOR (GLASS_SPRITETAG + GLASS_SPRITE_TRAINER_CURSOR)
#define GLASS_GFXTAG_TRAINER_NAMEPLATE (GLASS_SPRITETAG + GLASS_SPRITE_TRAINER_NAMEPLATE)
#define GLASS_GFXTAG_MON_CURSOR (GLASS_SPRITETAG + GLASS_SPRITE_MON_CURSOR)

#define FONT_GLASS_BAR FONT_SMALL_NARROW
#define FONT_GLASS_METRICS FONT_NORMAL
#define FONT_GLASS_TRAINER_NAME FONT_SMALL

#define PARTY_HEIGHT 32
#define PARTY_VERTICAL_OFFSET (((PARTY_HEIGHT /  4) *  3) + 5)

#define GLASS_NO_LOCATION_SAVED -1

#define GLASS_SCREEN_ROW_BUFFER (GLASS_TRAINER_MAX_SHOWED / 2)

#define GLASS_SCREEN_ROW_LAST (GLASS_TRAINER_MAX_SHOWED - 1)

#define GLASS_SPRITE_ICON_SIZE (16 * 16)

#define GLASS_TRAINER_NAMEPLATE_WIDTH 48
#define GLASS_TRAINER_NAMEPLATE_VERTICAL_PADDING 4
#define GLASS_TRAINER_NAMEPLATE_HORIZOTNAL_PADDING 3
#define GLASS_TRAINER_NAMEPLATE_MOVEMENT 5
#define GLASS_MOVE_TRAINER_BACK -1
#define GLASS_MOVE_TRAINER 1

#define GLASS_MON_CURSOR_PADDING     6

#define GLASS_LOCATION_TOTAL         0
#define GLASS_LOCATION_DEFEATED      1
#define GLASS_LOCATION_UNDEFEATED    2
#define GLASS_LOCATION_DISCOVERED    3
#define GLASS_LOCATION_UNDISCOVERED  4
#define GLASS_LOCATION_INCOMPLETE    5
#define GLASS_LOCATION_RATE          6
#define GLASS_LOCATION_STAT_COUNT    7

#define GLASS_EMPTY_TRAINER_ROW 99

#endif // GUARD_CONSTANTS_GLASS_H
