#ifndef GUARD_CONSTANTS_HIDDENGROTTO_H
#define GUARD_CONSTANTS_HIDDENGROTTO_H

enum HiddenGrottoId 
{
  GROTTO_NONE,
  GROTTO_ROUTE1,
  GROTTO_ROUTE2,
  GROTTO_ROUTE3,
  GROTTO_ROUTE4,
  GROTTO_ROUTE5,
  GROTTO_ROUTE6,
  GROTTO_ROUTE7,
  GROTTO_ROUTE8,
  GROTTO_ROUTE9,
  GROTTO_ROUTE10,
  GROTTO_ROUTE11,
  GROTTO_ROUTE12,
  GROTTO_ROUTE13,
  GROTTO_ROUTE14,
  GROTTO_ROUTE16,
  GROTTO_ROUTE18,
  GROTTO_ROUTE20,
  GROTTO_ROUTE22,
  GROTTO_ROUTE98,
  GROTTO_ROUTE99,
  GROTTO_ROUTE100,
  GROTTO_ROUTE_A,
  GROTTO_ROUTE_B,
  GROTTO_ROUTE_C,
  GROTTO_ROUTE_D,
  GROTTO_ROUTE_E,
  NUM_HIDDEN_GROTTO,
};

enum HiddenGrottoSecretsId
{
  GROTTO_NORMAL_ITEM_1, 
  GROTTO_NORMAL_ITEM_2, 
  GROTTO_NORMAL_ITEM_3, 
  GROTTO_NORMAL_ITEM_4, 
  GROTTO_NORMAL_ITEM_5, 
  GROTTO_NORMAL_ITEM_6, 
  GROTTO_NORMAL_ITEM_7, 
  GROTTO_NORMAL_ITEM_8, 
  GROTTO_NORMAL_ITEM_9, 
  GROTTO_RARE_ITEM_1, 
  GROTTO_RARE_ITEM_2, 
  GROTTO_RARE_ITEM_3, 
  GROTTO_RARE_ITEM_4, 
  GROTTO_RARE_ITEM_5, 
  GROTTO_RARE_ITEM_6, 
  GROTTO_RARE_ITEM_7, 
  GROTTO_RARE_ITEM_8, 
  GROTTO_RARE_ITEM_9, 
  GROTTO_RARE_ITEM_10, 
  GROTTO_RARE_ITEM_11, 
  GROTTO_RARE_ITEM_12, 
  GROTTO_RARE_ITEM_13, 
  GROTTO_RARE_ITEM_14, 
  GROTTO_ITEM_COUNT,
  GROTTO_POKEMON_1 = GROTTO_ITEM_COUNT,
  GROTTO_POKEMON_2,
  GROTTO_POKEMON_3,
  GROTTO_POKEMON_4,
  GROTTO_SECRET_COUNT,
};

#define GROTTO_POKEMON_COUNT                          (GROTTO_POKEMON_4 - GROTTO_RARE_ITEM_14)

#define GROTTO_NORMAL_ITEM_1_CHANCE                   1250
#define GROTTO_NORMAL_ITEM_2_CHANCE                   (500 + GROTTO_NORMAL_ITEM_1_CHANCE)
#define GROTTO_NORMAL_ITEM_3_CHANCE                   (200 + GROTTO_NORMAL_ITEM_2_CHANCE)
#define GROTTO_NORMAL_ITEM_4_CHANCE                   (625 + GROTTO_NORMAL_ITEM_3_CHANCE)
#define GROTTO_NORMAL_ITEM_5_CHANCE                   (250 + GROTTO_NORMAL_ITEM_4_CHANCE)
#define GROTTO_NORMAL_ITEM_6_CHANCE                   (100 + GROTTO_NORMAL_ITEM_5_CHANCE)
#define GROTTO_NORMAL_ITEM_7_CHANCE                   (625 + GROTTO_NORMAL_ITEM_6_CHANCE)
#define GROTTO_NORMAL_ITEM_8_CHANCE                   (250 + GROTTO_NORMAL_ITEM_7_CHANCE)
#define GROTTO_NORMAL_ITEM_9_CHANCE                   (100 + GROTTO_NORMAL_ITEM_8_CHANCE)
#define GROTTO_RARE_ITEM_1_CHANCE                     (625 + GROTTO_NORMAL_ITEM_9_CHANCE)
#define GROTTO_RARE_ITEM_2_CHANCE                     (625 + GROTTO_RARE_ITEM_1_CHANCE)
#define GROTTO_RARE_ITEM_3_CHANCE                     (625 + GROTTO_RARE_ITEM_2_CHANCE)
#define GROTTO_RARE_ITEM_4_CHANCE                     (625 + GROTTO_RARE_ITEM_3_CHANCE)
#define GROTTO_RARE_ITEM_5_CHANCE                     (750 + GROTTO_RARE_ITEM_4_CHANCE)
#define GROTTO_RARE_ITEM_6_CHANCE                     (250 + GROTTO_RARE_ITEM_5_CHANCE)
#define GROTTO_RARE_ITEM_7_CHANCE                     (100 + GROTTO_RARE_ITEM_6_CHANCE)
#define GROTTO_RARE_ITEM_8_CHANCE                     (100 + GROTTO_RARE_ITEM_7_CHANCE)
#define GROTTO_RARE_ITEM_9_CHANCE                     (100 + GROTTO_RARE_ITEM_8_CHANCE)
#define GROTTO_RARE_ITEM_10_CHANCE                    (100 + GROTTO_RARE_ITEM_9_CHANCE)
#define GROTTO_RARE_ITEM_11_CHANCE                    (25 + GROTTO_RARE_ITEM_10_CHANCE)
#define GROTTO_RARE_ITEM_12_CHANCE                    (50 + GROTTO_RARE_ITEM_11_CHANCE)
#define GROTTO_RARE_ITEM_13_CHANCE                    (25 + GROTTO_RARE_ITEM_12_CHANCE)
#define GROTTO_RARE_ITEM_14_CHANCE                    (25 + GROTTO_RARE_ITEM_13_CHANCE)
#define GROTTO_POKEMON_1_CHANCE                       (25 + GROTTO_RARE_ITEM_14_CHANCE)
#define GROTTO_POKEMON_2_CHANCE                       (25 + GROTTO_POKEMON_1_CHANCE)
#define GROTTO_POKEMON_3_CHANCE                       (25 + GROTTO_POKEMON_2_CHANCE)
#define GROTTO_POKEMON_4_CHANCE                       (25 + GROTTO_POKEMON_3_CHANCE)

#define HIDDEN_GROTTO_STEPS 250
#define HIDDEN_GROTTO_SECRET_CHANCE 5

#endif // GUARD_CONSTANTS_HIDDENGROTTO_H
