#ifndef GUARD_CONSTANTS_INVENTORY_H
#define GUARD_CONSTANTS_INVENTORY_H

enum InventoryModes
{
    INVENTORY_MODE_FIELD,
    INVENTORY_MODE_BATTLE,
    INVENTORY_MODE_GIVE_ITEM,
    INVENTORY_MODE_COUNT,
};

enum InventoryRegisterDirection
{
    INVENTORY_REGISTER_DIRECTION_UP,
    INVENTORY_REGISTER_DIRECTION_RIGHT,
    INVENTORY_REGISTER_DIRECTION_DOWN,
    INVENTORY_REGISTER_DIRECTION_LEFT,
    INVENTORY_REGISTER_NUM_DIRECTIONS,
    MAX_REGISTERED_ITEMS = INVENTORY_REGISTER_NUM_DIRECTIONS,
};

enum{
    FAVORITE_ITEM_ID,
    FAVORITE_ITEM_QUANTITY,
    FAVORITE_ITEM_POCKET_INDEX,
    FAVORITE_ITEM_POCKET,
    NUM_FAVORITE_ITEMS_ARRAY_SIZE,
};

enum InventoryBackgrounds {
    INVENTORY_BG_TEXT,
    INVENTORY_BG_NORMAL,
    INVENTORY_BG_SHADOWS,
    INVENTORY_BG_WALLPAPER,
    INVENTORY_BG_COUNT,
};

enum{
    INVENTORY_SPRITE_UP_ARROW,
    INVENTORY_SPRITE_DOWN_ARROW,
    INVENTORY_SPRITE_LEFT_ARROW,
    INVENTORY_SPRITE_RIGHT_ARROW,
    INVENTORY_SPRITE_ITEM_ICON,
    INVENTORY_SPRITE_REGISTERED_ITEM_UP,
    INVENTORY_SPRITE_REGISTERED_ITEM_DOWN,
    INVENTORY_SPRITE_REGISTERED_ITEM_LEFT,
    INVENTORY_SPRITE_REGISTERED_ITEM_RIGHT,
    NUM_INVENTORY_SPRITES,
};

enum{
    INVENTORY_ITEM_OPTION_CANCEL,
    INVENTORY_ITEM_OPTION_USE,
    INVENTORY_ITEM_OPTION_GIVE,
    INVENTORY_ITEM_OPTION_TOSS,
    INVENTORY_ITEM_OPTION_FAVORITE,
    INVENTORY_ITEM_OPTION_REGISTER,
    NUM_INVENTORY_ITEM_OPTIONS,
    INVENTORY_ITEM_OPTION_UNFAVORITE,
};

enum InventoryWindowIds
{
    INVENTORY_WINDOW_HEADER,
    INVENTORY_WINDOW_PARTY_DISPLAY,
    INVENTORY_WINDOW_ITEM_LIST,
    INVENTORY_WINDOW_DESC,
    INVENTORY_WINDOW_FOOTER,
    INVENTORY_WINDOW_COUNT,
};

enum SelectModes
{
    INVENTORY_MODE_DEFAULT,
    INVENTORY_MODE_MOVE_ITEMS,
    INVENTORY_MODE_REGISTER,
    INVENTORY_MODE_USE_OPTIONS,
    INVENTORY_MODE_REORDER,
    INVENTORY_MODE_TOSS_HOW_MANY,
    INVENTORY_MODE_TOSS_CONFIRMATION,
    INVENTORY_MESSAGE_CANT_MOVE_FAVORITE,
    INVENTORY_MESSAGE_SORTED_ITEMS_BY,
    INVENTORY_MESSAGE_CANT_USE_ITEM,
    INVENTORY_MESSAGE_CANT_TOSS_ITEM,
    INVENTORY_MESSAGE_USED_ITEM,
};

#define INVENTORY_MODE_COUNT INVENTORY_MODE_TOSS_CONFIRMATION + 1

enum InventoryColors
{
    INVENTORY_FONT_BLACK,
    INVENTORY_FONT_WHITE,
    INVENTORY_FONT_OUTLINE_COLOR,
    INVENTORY_FONT_RED,
    INVENTORY_FONT_BLUE,
};

enum Silicon_BagSortOptions
{
    ITEM_SORT_ALPHABETICALLY,
    ITEM_SORT_BY_TYPE,
    ITEM_SORT_BY_AMOUNT, //greatest -> least
    ITEM_SORT_CANCEL,
    NUM_SORT_OPTIONS
};

enum
{
    INVENTORY_STATUS_NONE,
    INVENTORY_STATUS_BURN,
    INVENTORY_STATUS_PARALYSIS,
    INVENTORY_STATUS_FREEZE,
    INVENTORY_STATUS_POISON,
    INVENTORY_STATUS_SLEEP,
    NUM_INVENTORY_STATUS
};

#define STRINGLIST_MAX_LENGHT 20
#define NUM_REGISTER_ITEMS 4
#define MAX_INVENTORY_FAVORITE_ITEMS  5
#define MAX_INVENTORY_ITEMS           255
#define DISABLE_REGISTER_NON_KEY_ITEMS FALSE
#define INVENTORY_TRANSPARENCY_STRENGTH 7
#define NUM_TOSS_CONFIRMATION_OPTIONS 2
#define INVENTORY_MAX_ITEMS_SHOWN     5
#define Y_VALUE_REGISTERED (8 * 19) << 8
#define INVENTORY_ACTION_BY_NAME   0
#define INVENTORY_ACTION_BY_TYPE   1
#define INVENTORY_ACTION_BY_AMOUNT 2
#define INVENTORY_ACTION_CANCEL    3
#define INVENTORY_ACTION_DUMMY     4
#define PAL_UI_SPRITES 0
#define INVENTORY_UP_ARROW_X 160
#define INVENTORY_UP_ARROW_Y 12
#define INVENTORY_DOWN_ARROW_X INVENTORY_UP_ARROW_X
#define INVENTORY_DOWN_ARROW_Y 96
#define GFX_STATUS_MINUS_X 24
#define GFX_HP_MINUS_X 20
#define GFX_HP_PLUS_Y 7
#define MON_STARTING_PALETTE_NUM 6
#define INVENTORY_ICON_FRAME_COUNT  4
#define INVENTORY_ICON_FRAME_SCROLL (32 * 8 / 2)
#define INVENTORY_ICON_SPRITE_SIZE  (32 * 16 / 2)
#define TAG_ITEM_INVENTORY_ICON            4133
#define TAG_ITEM_INVENTORY_REGISTERED_ICON TAG_ITEM_INVENTORY_ICON + 1
#define REGISTERED_ITEM_ICON_X_UP 42
#define REGISTERED_ITEM_ICON_Y_UP 37
#define REGISTERED_ITEM_ICON_X_DOWN REGISTERED_ITEM_ICON_X_UP
#define REGISTERED_ITEM_ICON_Y_DOWN 85
#define REGISTERED_ITEM_ICON_X_LEFT 18
#define REGISTERED_ITEM_ICON_Y_LEFT 61
#define REGISTERED_ITEM_ICON_X_RIGHT 66
#define REGISTERED_ITEM_ICON_Y_RIGHT REGISTERED_ITEM_ICON_Y_LEFT
#define INVENTORY_TEST_ITEM ITEM_VENUSAURITE
#define INVENTORY_CURSOR_SQUARES 10
#define NUM_PICK_MENU_OPTIONS       6
#define INVENTORY_PICK_MENU_SQUARES 4
#define INTERFACE_PALETTE_NUM 1
#define PAL_SLOT_INVENTORY_INTERFACE BG_PLTT_ID(INTERFACE_PALETTE_NUM)
#define INTERFACE_TMHM_COLOR_FIRST_SLOT 9
#define INVENTORY_TMHM_PAL_COLOR_ADDRESS (PAL_SLOT_INVENTORY_INTERFACE + INTERFACE_TMHM_COLOR_FIRST_SLOT)
#define INTERFACE_RGB_COLORS 3
#define NUM_ITEMS_MAX_DIGITS 5
#define MAX_CURSOR_NUM_X    2
#define MAX_CURSOR_NUM_Y    8
#define NUM_LR_CURSOR_MOVES 5
#define INVENTORY_FONT_HEADER FONT_NARROW
#define INVENTORY_FONT_LIST   FONT_OUTLINED
#define INVENTORY_FONT_QUANTITY FONT_NARROW
#define INVENTORY_FONT_MENU FONT_NORMAL
#define INVENTORY_DPAD_WIDTH 24
#define INVENTORY_DPAD_HEIGHT INVENTORY_DPAD_WIDTH

#endif // GUARD_CONSTANTS_INVENTORY_H
