#ifndef GUARD_CONSTANTS_INVENTORY_H
#define GUARD_CONSTANTS_INVENTORY_H

enum InventoryModes
{
    INVENTORY_MODE_FIELD,
    INVENTORY_MODE_BATTLE,
    INVENTORY_MODE_GIVE_ITEM,
    INVENTORY_MOE_COUNT,
};

enum InventoryRegisterDirection
{
    INVENTORY_REGISTER_DIRECTION_UP,
    INVENTORY_REGISTER_DIRECTION_RIGHT,
    INVENTORY_REGISTER_DIRECTION_DOWN,
    INVENTORY_REGISTER_DIRECTION_LEFT,
    INVENTORY_REGISTER_NUM_DIRECTIONS,
    MAX_REGISTERED_ITEMS = INVENTORY_REGISTER_NUM_DIRECTIONS,
};

#define STRINGLIST_MAX_LENGHT 20
#define NUM_REGISTER_ITEMS 4

#endif // GUARD_CONSTANTS_INVENTORY_H
