#ifndef GUARD_ITEM_CONSTANTS_H
#define GUARD_ITEM_CONSTANTS_H

// These constants are used in gItemsInfo
// Start inventory
/*
#define POCKET_NONE        0
#define POCKET_ITEMS       1
#define POCKET_POKE_BALLS  2
#define POCKET_TM_HM       3
#define POCKET_BERRIES     4
#define POCKET_KEY_ITEMS   5

#define ITEMS_POCKET       0
#define BALLS_POCKET       1
#define TMHM_POCKET        2
#define BERRIES_POCKET     3
#define KEYITEMS_POCKET    4
#define POCKETS_COUNT      5
*/

enum PocketList
{
    MEDICINE_POCKET,
    BALLS_POCKET,
    BATTLE_ITEMS_POCKET,
    POWERUP_POCKET,
    BERRIES_POCKET,
    OTHER_POCKET,
    TMHM_POCKET,
    TREASURE_POCKET,
    Z_CRYSTALS_POCKET,
    MEGA_STONES_POCKET,
    KEYITEMS_POCKET,
    POCKETS_COUNT,
};

enum PocketEnum
{
    POCKET_NONE,
    POCKET_MEDICINE,
    POCKET_POKE_BALLS,
    POCKET_BATTLE_ITEMS,
    POCKET_POWERUP,
    POCKET_BERRIES,
    POCKET_OTHER,
    POCKET_TM_HM,
    POCKET_TREASURE,
    POCKET_Z_CRYSTALS,
    POCKET_MEGA_STONES,
    POCKET_KEY_ITEMS,
};
// End inventory

#define REPEL_LURE_MASK         (1 << 15)
#define IS_LAST_USED_LURE(var)  (var & REPEL_LURE_MASK)
#define REPEL_LURE_STEPS(var)   (var & (REPEL_LURE_MASK - 1))
#define LURE_STEP_COUNT         (IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)
#define REPEL_STEP_COUNT        (!IS_LAST_USED_LURE(VarGet(VAR_REPEL_STEP_COUNT)) ? REPEL_LURE_STEPS(VarGet(VAR_REPEL_STEP_COUNT)) : 0)

#endif // GUARD_ITEM_CONSTANTS_H
