#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

enum NameplateAttributes
{
    NAMEPLATE_SPEAKER_ATTRIBUTE_NAME,
    NAMEPLATE_SPEAKER_ATTRIBUTE_TITLE,
    NAMEPLATE_SPEAKER_ATTRIBUTE_COUNT,
};

enum NamePlateColors
{
    FONT_BLACK,
    FONT_WHITE,
};

enum NameplateSpeaker
{
    SPEAKER_DEFAULT,
    SPEAKER_TEST,
    SPEAKER_DIMU,
    SPEAKER_BLAINE,
    SPEAKER_BROCK,
    SPEAKER_BRUNO,
    SPEAKER_BUG_CATCHER,
    SPEAKER_SHINZO,
    SPEAKER_NERIENE,
    SPEAKER_AMIARGENTO,
    SPEAKER_ELM,
    SPEAKER_ERIKA,
    SPEAKER_BELEN,
    SPEAKER_FISHERMAN,
    SPEAKER_ALCMENE,
    SPEAKER_ALCMENE_UNKNOWN,
    SPEAKER_GIRL,
    SPEAKER_GREEN,
    SPEAKER_JANINE,
    SPEAKER_KAREN,
    SPEAKER_KID,
    SPEAKER_KEIYING,
    SPEAKER_KEIYING_GYM,
    SPEAKER_KURT,
    SPEAKER_LANCE,
    SPEAKER_LT_SURGE,
    SPEAKER_MAN,
    SPEAKER_MISTY,
    SPEAKER_KAUNA,
    SPEAKER_OLD_MAN,
    SPEAKER_OLD_WOMAN,
    SPEAKER_POLICEMAN,
    SPEAKER_BD,
    SPEAKER_RED,
    SPEAKER_ROCKET_GRUNT_MALE,
    SPEAKER_ROCKET_GRUNT_FEMALE,
    SPEAKER_RAMESH,
    SPEAKER_SILVER,
    SPEAKER_STEVEN,
    SPEAKER_SWIMMER_MALE,
    SPEAKER_EMRYS,
    SPEAKER_WILL,
    SPEAKER_WOMAN,
    SPEAKER_YOUNGSTER,
    SPEAKER_FIREBREATHER,
    SPEAKER_BEAUTY,
    SPEAKER_BIRD_KEEPER,
    SPEAKER_BLACK_BELT,
    SPEAKER_EUSINE,
    SPEAKER_WAITER,
    SPEAKER_PROTON,
    SPEAKER_PETREL,
    SPEAKER_ADAORA,
    SPEAKER_ADAORA_FIRST_INTRO,
    SPEAKER_KAI,
    SPEAKER_KAI_TIDE,
    SPEAKER_COLLECTOR,
    SPEAKER_BILL,
    SPEAKER_BOARDER,
    SPEAKER_JUGGLER,
    SPEAKER_KIMONO_GIRL,
    SPEAKER_LASS,
    SPEAKER_MEDIUM,
    SPEAKER_MEDIUM_2,
    SPEAKER_POKE_MANIAC,
    SPEAKER_SAGE,
    SPEAKER_SUPER_NERD,
    SPEAKER_ACE_TRAINER_M,
    SPEAKER_ACE_TRAINER_F,
    SPEAKER_LI,
    SPEAKER_AROMA_LADY,
    SPEAKER_BATTLE_GIRL,
    SPEAKER_MOM,
    SPEAKER_NEWS,
    SPEAKER_ALICIA,
    SPEAKER_CHARLOTTE,
    SPEAKER_CHARLOTTE_SHARPRISE,
    SPEAKER_GRUNT,
    SPEAKER_MARKETING_STAFF,
    SPEAKER_ANNOUNCER,
    SPEAKER_TALA,
    SPEAKER_CROWD_A,
    SPEAKER_CROWD_B,
    SPEAKER_CROWD_C,
    SPEAKER_CROWD_D,
    SPEAKER_RUPERT,
    SPEAKER_OLIVER,
    SPEAKER_RESIDENT_A,
    SPEAKER_RESIDENT_B,
    SPEAKER_RESIDENT_C,
    SPEAKER_RESIDENT_D,
    SPEAKER_SIARL,
    SPEAKER_ARMANDO,
    SPEAKER_DAGMAR,
    SPEAKER_GURL,
    SPEAKER_LEAGUE_STAFF_A,
    SPEAKER_ROCKET_MEMBER_A,
    SPEAKER_ROCKET_MEMBER_B,
    SPEAKER_DAVID,
    SPEAKER_ISHAN,
    SPEAKER_ADELAIDE,
    SPEAKER_PROTEST_A,
    SPEAKER_PROTEST_B,
    SPEAKER_PROTEST_C,
    SPEAKER_PROTEST_D,
    SPEAKER_VITOMIR,
    SPEAKER_RABIA,
    SPEAKER_LANDLORD,
    SPEAKER_JULIUS,
    SPEAKER_MADISON,
    SPEAKER_STRANDED_A,
    SPEAKER_STRANDED_B,
    SPEAKER_RESIDENT_E,
    SPEAKER_RESIDENT_F,
    SPEAKER_MAGNUS,
    SPEAKER_ELLEN,
    SPEAKER_ALEKSANDER,
    SPEAKER_SUMMER,
    SPEAKER_MAID,
    SPEAKER_NEWS_B,
    SPEAKER_ARNAV,
    SPEAKER_TECH,
    SPEAKER_CHIEF,
    SPEAKER_DOYLE,
    SPEAKER_IMELDA,
    SPEAKER_DOOR,
    SPEAKER_TEODORO,
    SPEAKER_DUDLEY,
    SPEAKER_CHERIE,
    SPEAKER_MATTHEW,
    SPEAKER_FANNY,
    SPEAKER_CRAIG,
    SPEAKER_ANTONE,
    SPEAKER_ORI,
    SPEAKER_HIKO,
    SPEAKER_POLICE,
    SPEAKER_MACK,
    SPEAKER_TYZONN,
    SPEAKER_WILL2,
    SPEAKER_RONNY,
    SPEAKER_DAX,
    SPEAKER_BRENNAN,
    SPEAKER_ATTENDANT,
    SPEAKER_SPEAKER,
    SPEAKER_GHOST,
    SPEAKER_ISMAIL,
    SPEAKER_STAN_PERLACIA_CITY,
    SPEAKER_STAN_PERLACIA_CITYB,
    SPEAKER_STAN_PERLACIA_CITYC,
    SPEAKER_STAN_PERLACIA_CITYD,
    SPEAKER_STAN_PERLACIA_CITYE,
    SPEAKER_SERGEY,
    SPEAKER_REPORTER,
    SPEAKER_TROLLEY_GUY,
    SPEAKER_HESTER,
    SPEAKER_SHARPRISECAPITAL_STAFF,
    SPEAKER_TONALLI,
    SPEAKER_DRUMMER_B,
    SPEAKER_DRUMMER_C,
    SPEAKER_DRUMMER_D,
    SPEAKER_LIIDIA,
    SPEAKER_RAINER,
    SPEAKER_BRONSON,
    SPEAKER_SHASHI,
    SPEAKER_LEAH,
    SPEAKER_GUARD,
    SPEAKER_SHOPKEEPER,
    SPEAKER_ELIOR,
    SPEAKER_LELAND,
    SPEAKER_AMBROGIO,
    SPEAKER_JORIS,
    SPEAKER_NURSE,
    SPEAKER_AUGUSTE,
    SPEAKER_JULIA,
    SPEAKER_ALICE,
    SPEAKER_FERRAN,
    SPEAKER_ANTHONY,
    SPEAKER_SEVENSISTERS_TINA,
    SPEAKER_SEVENSISTERS_PAUL,
    SPEAKER_SEVENSISTERS_JON,
    SPEAKER_SEVENSISTERS_BRADLEY,
    SPEAKER_SEVENSISTERS_JO,
    SPEAKER_SEVENSISTERS_HANNAH,
    SPEAKER_SEVENSISTERS_RACHEL,
    SPEAKER_KATHARINA,
    SPEAKER_OFFICIANT,
    SPEAKER_HELEN,
    SPEAKER_RUSTY,
    SPEAKER_WILLOW,
    SPEAKER_GRIFF,
    SPEAKER_LUNA,
    SPEAKER_MAX,
    SPEAKER_BLAZE,
    SPEAKER_KIKI,
    SPEAKER_EJ,
    SPEAKER_WAITE,
    SPEAKER_DEBRA,
    SPEAKER_WALDRON,
    SPEAKER_ISIDORE,
    SPEAKER_FILIP,
    SPEAKER_GERTRUDE,
    SPEAKER_KHALEEL,
    SPEAKER_KITVOL,
    SPEAKER_NANCY,
    SPEAKER_PANNEN,
    SPEAKER_MADRONE,
    SPEAKER_BUZZR_CEO,
    SPEAKER_PRESTO_CEO,
    SPEAKER_ARRIBA_DRIVER1,
    SPEAKER_ARRIBA_DRIVER2,
    SPEAKER_ARRIBA_DRIVER3,
    SPEAKER_PERSUASIVE_LANDLORD,
    SPEAKER_PERSUASIVE_SIBLING,
    SPEAKER_ARRIBA_GRUNT1,
    SPEAKER_ARRIBA_GRUNT2,
    SPEAKER_ARRIBA_CEO,
    SPEAKER_GYM_ATTENDANT,
    SPEAKER_IMPROV_1,
    SPEAKER_IMPROV_2,
    SPEAKER_IMPROV_3,
    SPEAKER_CHRIS,
    SPEAKER_LEE_PYRON,
    SPEAKER_PROF_TRACHY,
    SPEAKER_VSDEOGUY,
    SPEAKER_VSDEORESEARCHER,
    SPEAKER_DRUG_HELMET_TESTER,
    SPEAKER_ANGELDELIVERYBIKERA,
    SPEAKER_ANGELDELIVERYBIKERB,
    SPEAKER_ANGELDELIVERYBIKERC,
    SPEAKER_ANGELDELIVERYBIKERD,
    SPEAKER_MELISSA,
    SPEAKER_UNHOUSED,
    SPEAKER_BREEDINGPARENT,
    SPEAKER_BREEDINGEGG,
    SPEAKER_BREEDINGGENE,
    SPEAKER_PARKRANGER,
    NUM_SPEAKERS,
};

enum NameplateTail
{
    TAIL_DEFAULT,
    TAIL_WHISPER,
    TAIL_SHOUT,
    TAIL_THOUGHT,
    TAIL_TALK,
    TAIL_COUNT,
};

enum NameplateEmotes
{
    EMOTE_DEFAULT,
    EMOTE_ANGRY,
    EMOTE_SAD,
    EMOTE_HAPPY,
    EMOTE_LAUGH,
    EMOTE_SWEAT,
    EMOTE_SHOCK,
    EMOTE_CONFUSE,
    EMOTE_LOVE,
    EMOTE_COUNT,
};

enum NameplatePhone
{
    PHONE_OFF,
    PHONE_ON,
    PHONE_COUNT,
};

#define MUGSHOT_PALETTE_NUM                            13

#define PHONE_WIDTH                                    16
#define PHONE_HEIGHT                                   16

#define PHONE_LEFT_MARGIN                              32
#define PHONE_Y                                        14

#define EMOTES_WIDTH                                   48
#define EMOTES_HEIGHT                                  32
#define EMOTES_Y                                       0
#define EMOTES_LEFT_MARGIN                             35
#define EMOTES_SIZE                                    TILE_OFFSET_4BPP((EMOTES_WIDTH * EMOTES_HEIGHT)/(TILE_WIDTH * TILE_HEIGHT))

#define FONT_SPEAKER_NAME                              FONT_NARROW
#define FONT_SPEAKER_TITLE                             FONT_SMALL_NARROW

#define TAILS_WIDTH                                    48
#define TAILS_HEIGHT                                   48
#define TAILS_Y                                        0
#define TAILS_TALK_RIGHT_PADDING                       36
#define TAILS_RIGHT_PADDING                            3
#define TAILS_SIZE                                     TILE_OFFSET_4BPP((TAILS_WIDTH * TAILS_HEIGHT)/(TILE_WIDTH * TILE_HEIGHT))

#define SPEAKER_NAME_LENGTH                            20
#define SPEAKER_NAME_X                                 4
#define SPEAKER_NAME_Y                                 12
#define SPEAKER_TITLE_Y                                1

#define GFXTAG_SPEAKER_ICON                            10019
#define SPEAKER_ICON_PAL_NUM                           5
#define SPEAKER_ICON_Y                                 76
#define SPEAKER_ICON_RIGHT_PADDING                     24
#define SPEAKER_ICON_SHORTER_LEFT_PADDING              (48 + SPEAKER_NAME_X)
#define SPEAKER_ICON_LONGER_LEFT_PADDING               (27 + SPEAKER_NAME_X)

#define MSGBOX_TILE_WIDTH                              (DISPLAY_TILE_WIDTH - 2)
#define MSGBOX_TOP_FIRST_TILE_OFFSET                   90
#define MSGBOX_MIDDLE_TILE_OFFSET                      (MSGBOX_TOP_FIRST_TILE_OFFSET + 1)
#define MSGBOX_LAST_TILE_OFFSET                        (MSGBOX_MIDDLE_TILE_OFFSET + MSGBOX_TILE_WIDTH)

#define MSGBOX_TILE_HEIGHT                             4
#define WINDOW_TILETOP                                 73
#define WINDOW_TILELEFT                                0
#define NAMEPLATE_WINDOW_TEMPLATE                      64

#define NAMEPLATE_TOP_FIRST_TILE_OFFSET                0
#define NAMEPLATE_TOP_MIDDLE_TILE_OFFSET               (NAMEPLATE_TOP_FIRST_TILE_OFFSET + 1)
#define NAMEPLATE_TOP_SECOND_ROW_TILE_OFFSET           30
#define NAMEPLATE_MIDDLE_SECOND_ROW_TILE_OFFSET        (NAMEPLATE_TOP_SECOND_ROW_TILE_OFFSET + 1)
#define NAMEPLATE_TOP_THIRD_ROW_TILE_OFFSET            60
#define NAMEPLATE_MIDDLE_THIRD_ROW_TILE_OFFSET         (NAMEPLATE_TOP_THIRD_ROW_TILE_OFFSET +1)

#endif
