#ifndef GUARD_GAME_OPTIONS_H
#define GUARD_GAME_OPTIONS_H

#define GAME_OPTION_RUN_ALWAYS 0
#define GAME_OPTION_RUN_TOGGLE 1
#define GAME_OPTION_RUN_MANUAL 2

#define GAME_OPTION_CUTSCENE_PLAY 0
//#define GAME_OPTION_CUTSCENE_ASK  1
//#define GAME_OPTION_CUTSCENE_HOLD 2
#define GAME_OPTION_CUTSCENE_SKIP 1
#define GAME_OPTION_CUTSCENE_COUNT 2

#define SKIP_CUTSCENE_HELD_KEYS (START_BUTTON)
#define SKIP_CUTSCENE_FRAME_COUNT 30

#define GAME_OPTION_PUZZLES_OFF 0
#define GAME_OPTION_PUZZLES_ON 1
#define GAME_OPTION_PUZZLES_COUNT 2

#define GAME_OPTION_AUTOSAVE_OFF 0
#define GAME_OPTION_AUTOSAVE_ON 1
#define GAME_OPTION_AUTOSAVE_COUNT 2

#define AUTOSAVE_THRESHOLD 10

#endif //GUARD_GAME_OPTIONS_H
