#ifndef GUARD_BATTLE_OPTIONS_H
#define GUARD_BATTLE_OPTIONS_H

// Constant labels for the Options UI's features for use in files
// that cannot read labels off an enum.

#define BATTLE_SCRIPT_OPTION_TAKE_WILD_ITEMS_NEVER   0
#define BATTLE_SCRIPT_OPTION_TAKE_WILD_ITEMS_ASK     1
#define BATTLE_SCRIPT_OPTION_TAKE_WILD_ITEMS_ALWAYS  2

enum optionBattleNicknameValues
{
    BATTLE_OPTION_NICKNAME_ASK,
    BATTLE_OPTION_NICKNAME_FORCED,
    BATTLE_OPTION_NICKNAME_NONE,
};

#define LEVEL_CAP_VALUE_0 25
#define LEVEL_CAP_VALUE_1 28
#define LEVEL_CAP_VALUE_2 31
#define LEVEL_CAP_VALUE_3 34
#define LEVEL_CAP_VALUE_4 37
#define LEVEL_CAP_VALUE_5 40
#define LEVEL_CAP_VALUE_6 43
#define LEVEL_CAP_VALUE_7 46
#define LEVEL_CAP_VALUE_8 49
#define LEVEL_CAP_VALUE_9 52
#define LEVEL_CAP_VALUE_10 55
#define LEVEL_CAP_VALUE_11 58
#define LEVEL_CAP_VALUE_12 61
#define LEVEL_CAP_VALUE_13 64
#define LEVEL_CAP_VALUE_14 67
#define LEVEL_CAP_VALUE_15 70
#define LEVEL_CAP_VALUE_16 73
#define LEVEL_CAP_VALUE_17 74
#define LEVEL_CAP_VALUE_18 75
#define LEVEL_CAP_VALUE_19 76
#define LEVEL_CAP_VALUE_20 77
#define LEVEL_CAP_VALUE_21 79
#define LEVEL_CAP_VALUE_22 81
#define LEVEL_CAP_VALUE_23 83
#define LEVEL_CAP_VALUE_24 85
#define LEVEL_CAP_VALUE_25 87
#define LEVEL_CAP_VALUE_26 89

#endif //GUARD_BATTLE_OPTIONS_H
