#ifndef GUARD_CONSTANTS_PHENOMENON_H
#define GUARD_CONSTANTS_PHENOMENON_H

#define VAR_PHENOMENON_TYPE     VAR_TEMP_E
#define VAR_PHENOMENON_ARGUMENT VAR_TEMP_F

enum
{
    PHENOMENON_TYPE_ENCOUNTER,
    PHENOMENON_TYPE_ITEM,
    PHENOMENON_TYPES
};

enum
{
    PHENOMENON_ENCOUNTER_ENVIROMENT_LAND,  //PHENOMENON_ENVIROMENT_UNDERGROUND
    PHENOMENON_ENCOUNTER_ENVIROMENT_WATER,
    PHENOMENON_ENCOUNTER_ENVIROMENT_BRIDGE,
    NUM_PHENOMENON_ENVIROMENTS
};

#define PHENOMENON_SOUND_DELAY_GRASS 100
#define PHENOMENON_SOUND_DELAY_DUST 150
#define PHENOMENON_SOUND_DELAY_WATER 200
#define PHENOMENON_SOUND_DELAY_BRIDGE 150

#define MAX_PHENOMENON_DISTANCE            19
#define PHENOMENON_RADIUS                  8
#define PHENOMENON_LAND_RATE_MULTIPLIER    5
#define PHENOMENON_WATER_RATE_MULTIPLIER   3
#define PHENOMENON_BRIDGE_ENCOUNTER_CHANCE 10
#define PHENOMENON_MAX_ATTEMPTS            40

#endif // GUARD_CONSTANTS_PHENOMENON_H
