#ifndef GUARD_QUEST_LOGIC_CONSTANTS_H
#define GUARD_QUEST_LOGIC_CONSTANTS_H

#define FALSE_TIMELINE_NONE_COMPLETE 0
#define FALSE_TIMELINE_MAN_COMPLETE 1
#define FALSE_TIMELINE_HOW_COMPLETE 2
#define FALSE_TIMELINE_BURN_COMPLETE 3
#define FALSE_TIMELINE_HOW_BURN_COMPLETE 4
#define FALSE_TIMELINE_MAN_BURN_COMPLETE 5
#define FALSE_TIMELINE_MAN_HOW_COMPLETE 6
#define FALSE_TIMELINE_MAN_HOW_BURN_COMPLETE 7

#endif // GUARD_QUEST_LOGIC_CONSTANTS_H
