#ifndef GUARD_CONSTANTS_QUEST_OW_H
#define GUARD_CONSTANTS_QUEST_OW_H

#define VRAM_ANIMATION_START 1

enum QuestOverworldWindows
{
    QUEST_OVERWORLD_WINDOW_HEADER,
    QUEST_OVERWORLD_WINDOW_CTA,
    QUEST_OVERWORLD_WINDOW_COUNT,
};

#define BG0_QUEST_OVERWORLD 0

enum QuestOverworldFontColor
{
    QUEST_OVERWORLD_FONT_COLOR_BLACK,
    QUEST_OVERWORLD_FONT_COLOR_WHITE,
    QUEST_OVERWORLD_FONT_COLOR_COUNT,
};

#define FONT_QUEST_OVERWORLD_HEADER FONT_NORMAL
#define FONT_QUEST_OVERWORLD_CTA FONT_NORMAL

enum QuestOverworldPaletteColors
{
    QUEST_OVERWORLD_PALETTE_TRANSPERANT,
    QUEST_OVERWORLD_PALETTE_WHITE,
    QUEST_OVERWORLD_PALETTE_BLACK,
    QUEST_OVERWORLD_PALETTE_BLUE,
    QUEST_OVERWORLD_PALETTE_LIGHT_GRAY,
    QUEST_OVERWORLD_PALETTE_GRAY,
    QUEST_OVERWORLD_PALETTE_DARK_GRAY,
    QUEST_OVERWORLD_PALETTE_ICON_RED,
    QUEST_OVERWORLD_PALETTE_CHECK_GREEN,
};

#define QUEST_OVERWORLD_PALETTE_INTERFACE_ID   13
#define QUEST_OVERWORLD_PALETTE_INTERFACE_SLOT BG_PLTT_ID(QUEST_OVERWORLD_PALETTE_INTERFACE_ID)

#define QUEST_OVERWORLD_FIRST_ROW_OFFSET 0
#define QUEST_OVERWORLD_TILES_IN_ROW 15
#define QUEST_OVERWORLD_SECOND_ROW_OFFSET (QUEST_OVERWORLD_FIRST_ROW_OFFSET + QUEST_OVERWORLD_TILES_IN_ROW)
#define QUEST_OVERWORLD_THIRD_ROW_OFFSET (QUEST_OVERWORLD_FIRST_ROW_OFFSET + 0)
#define QUEST_OVERWORLD_FOURTH_ROW_OFFSET (QUEST_OVERWORLD_FIRST_ROW_OFFSET + QUEST_OVERWORLD_TILES_IN_ROW)

#define QUEST_OVERWORLD_THIRD_ROW_D_TILE_OFFSET (QUEST_OVERWORLD_THIRD_ROW_OFFSET + 3)
#define QUEST_OVERWORLD_THIRD_ROW_E_TILE_OFFSET (QUEST_OVERWORLD_THIRD_ROW_OFFSET + 4)
#define QUEST_OVERWORLD_FOURTH_ROW_G_TILE_OFFSET (QUEST_OVERWORLD_FOURTH_ROW_OFFSET + 1)
#define QUEST_OVERWORLD_FOURTH_ROW_H_TILE_OFFSET (QUEST_OVERWORLD_FOURTH_ROW_OFFSET + 3)
#define QUEST_OVERWORLD_FOURTH_ROW_I_TILE_OFFSET (QUEST_OVERWORLD_FOURTH_ROW_OFFSET + 4)


#define TAG_QUEST_ICON 4096

#define QUEST_OVERWORLD_FRAME_0 (0 * 16)
#define QUEST_OVERWORLD_FRAME_1 (1 * 16)
#define QUEST_OVERWORLD_FRAME_2 (2 * 16)
#define QUEST_OVERWORLD_FRAME_3 (3 * 16)
#define QUEST_OVERWORLD_FRAME_4 (4 * 16)
#define QUEST_OVERWORLD_FRAME_5 (5 * 16)
#define QUEST_OVERWORLD_FRAME_6 (6 * 16)
#define QUEST_OVERWORLD_FRAME_7 (7 * 16)
#define QUEST_OVERWORLD_FRAME_8 (8 * 16)

#define QUEST_OVERWORLD_ANIMATION_SLIDE_STOP 14
#define QUEST_OVERWORLD_ANIMATION_SLIDE_TEXT_START 5
#define QUEST_OVERWORLD_ANIMATION_DISAPPEAR_START 100
#define QUEST_OVERWORLD_ANIMATION_DISAPPEAR_STOP (QUEST_OVERWORLD_ANIMATION_DISAPPEAR_START + 8)
#define QUEST_OVERWORLD_ANIMATION_ICON_DISAPPEAR_POINT (DISPLAY_HEIGHT + 8)

#define QUEST_OVERWORLD_BACKGROUND_HALF_TILE -1024

#define QUEST_OVERWORLD_ICON_X_DESTINATION 135
#define QUEST_OVERWORLD_ICON_LEFT_BUFFER 30

#endif // GUARD_CONSTANTS_QUEST_OW_H
