#ifndef GUARD_CONSTANTS_QUESTS_H
#define GUARD_CONSTANTS_QUESTS_H

enum QuestMenuScriptCommandParameters
{
    QUEST_MENU_OPEN,               //opens the quest menu (questId = 0)
    QUEST_MENU_UNLOCK_QUEST,       //questId = QUEST_X (0-indexed)
    QUEST_MENU_SET_ACTIVE,         //questId = QUEST_X (0-indexed)
    QUEST_MENU_SET_REWARD,         //questId = QUEST_X (0-indexed)
    QUEST_MENU_COMPLETE_QUEST,     //questId = QUEST_X (0-indexed)
    QUEST_MENU_CHECK_UNLOCKED,     //checks if questId has been unlocked. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_INACTIVE,     //check if a questID is inactive. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_ACTIVE,       //checks if questId has been unlocked. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_REWARD,       //checks if questId is in Reward state. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_COMPLETE,     //checks if questId has been completed. Returns result to gSpecialVar_Result
    QUEST_MENU_BUFFER_QUEST_NAME,  //buffers a quest name to gStringVar1
    QUEST_MENU_SET_FAVORITE,
    QUEST_MENU_UNCOMPLETE_QUEST,
};

enum QuestIdList
{
    QUEST_PLAYERSADVENTURE,
    QUEST_MANHUNT,
    QUEST_HOWDISAPPOINTING,
    QUEST_LETSBURNTHISMOTHERDOWN,
    QUEST_RESTOREESPULEEGYM,
    QUEST_RESTOREZENZUGYM,
    QUEST_RESTOREHODOUGYM,
    QUEST_RESTORETIRABUDINGYM,
    QUEST_IMPROVBATTLING,
    QUEST_BATTLEARCADEMINIQUEST,
    QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP,
    QUEST_CHALLENGEOFTHE7SISTERS,
    QUEST_STRESSCUP,
    QUEST_DRUGHELMETTEST,
    QUEST_RPS,
    QUEST_RABIESOUTBREAK,
    QUEST_VSDEOXYS,
    QUEST_FRESHWATEREVOLUTION,
    QUEST_SMOOTHIECRAFTING,
    QUEST_HODOUTUNNELS,
    QUEST_PSYOP,
    QUEST_BREAKTHEINTERNET,
    QUEST_BETWEENASTONEANDAHARDPLACE,
    QUEST_ROCKCOLLECTOR,
    QUEST_TAXICABTURNAROUND,
    QUEST_PERSUASIVEPASSENGER,
    QUEST_BODEGABURNOUT,
    QUEST_WAREHOUSEWARFARE,
    QUEST_ANGELDELIVERY,
    QUEST_GETTHEBANDBACKTOGETHER,
    QUEST_TEACHATRAINERTOFISH,
    QUEST_WILDFIRERISK,
    QUEST_IBELIEVEICANFLY,
    QUEST_HUNKYJESUS,
    QUEST_ALLTHATGLITTERSMIGHTBEGOLD,
    QUEST_HANG20,
    QUEST_WHIRLPOOLFERRY,
    QUEST_RESTAURANTEXPANSION1,
    QUEST_RESTAURANTEXPANSION2,
    QUEST_CULTURALPURITY,
    QUEST_HYBRIDCULTURE,
    QUEST_ALOHAFROMALOLA,
    QUEST_BUILDINGANEXHIBIT,
    QUEST_STEALTHEAXE,
    QUEST_NERIENEQUEST2,
    QUEST_ECOSYSTEMIMPACTSTUDY,
    QUEST_POISONEDLAKEINVESTIGATION,
    QUEST_SHUTDOWNMEDICINEMAN,
    QUEST_INVERSEHALLUCINOGENIC,
    QUEST_FRANCHISEDRAG,
    QUEST_POPUPEVENT,
    QUEST_DIGGINGUPADAORASDIRT,
    QUEST_FREETHEINNOCENT,
    QUEST_FINDTHEGUILTY,
    QUEST_RETURNDOLL,
    QUEST_KITCHENVOLUNTEERING,
    QUEST_THEBOYWHOCRIESWITHWOLVES,
    QUEST_FLIGHTPATTERNS,
    QUEST_INSTALLNATUREPROBES,
    QUEST_MANOFMANYHATS,
    QUEST_CUTEPOKEMON,
    QUEST_ARTISANBALLS1,
    QUEST_ARTISANBALLS2,
    QUEST_ARTISANBALLS3,
    QUEST_STOLENTRADE,
    QUEST_FOODTRUCKBUREACRACY,
    QUEST_CONTRACTORPORYGON,
    QUEST_LASTMUSICVENUEINRESIDO,
    QUEST_RECRUITLOCALARTISTS,
    QUEST_REDOMUGGING,
    QUEST_WALLACEARMY,
    QUEST_BUILDINGSCOPE,
    QUEST_BUTONLYINMYBACKYARD,
    QUEST_NEIGHBORHOODCLEANUP,
    QUEST_NEIGHBORHOODCLEANUP2,
    QUEST_NEIGHBORHOODCLEANUP3,
    QUEST_MUTUALAIDFUND,
    QUEST_MUTUALAIDOUTREACH,
    QUEST_GARDENCLEANUP,
    QUEST_THELEANINGTOWER,
    QUEST_HIDDENGROTTOMAPPING,
    QUEST_ULTRAWORMHOLERESEARCH,
    QUEST_GF_ROUNDUP,
    QUEST_GF_STRIDER,
    QUEST_GF_PSF,
    QUEST_GF_MM,
    QUEST_GF_LITTLESPARROW,
    QUEST_GF_JACKIECAT,
    QUEST_GF_CRIM,
    QUEST_DEXCOMPLETION,
    QUEST_SKILLLIBRARY,
    QUEST_COUNT,
};

enum SubQuestDefines
{
    SUB_QUEST_1,
    SUB_QUEST_2,
    SUB_QUEST_3,
    SUB_QUEST_4,
    SUB_QUEST_5,
    SUB_QUEST_6,
    SUB_QUEST_7,
    SUB_QUEST_8,
    SUB_QUEST_9,
    SUB_QUEST_10,
    SUB_QUEST_11,
    SUB_QUEST_12,
    SUB_QUEST_13,
    SUB_QUEST_14,
    SUB_QUEST_15,
    SUB_QUEST_16,
    SUB_QUEST_17,
    SUB_QUEST_18,
    SUB_QUEST_19,
    SUB_QUEST_20,
    SUB_QUEST_21,
    SUB_QUEST_22,
    SUB_QUEST_23,
    SUB_QUEST_24,
    SUB_QUEST_25,
    SUB_QUEST_26,
    SUB_QUEST_27,
    SUB_QUEST_28,
    SUB_QUEST_29,
    SUB_QUEST_30,
};

#define QUEST_FOODTRUCKBUREACRACY_SUB_COUNT       4
#define QUEST_BREAKTHEINTERNET_SUB_COUNT          3
#define QUEST_INSTALLNATUREPROBES_SUB_COUNT       3
#define QUEST_RESTAURANTEXPANSION1_SUB_COUNT      4
#define QUEST_RESTAURANTEXPANSION2_SUB_COUNT      5
#define QUEST_HYBRIDCULTURE_SUB_COUNT             3
#define QUEST_BUILDINGANEXHIBIT_SUB_COUNT         4
#define QUEST_CONTRACTORPORYGON_SUB_COUNT         3
#define QUEST_GETTHEBANDBACKTOGETHER_SUB_COUNT    5
#define QUEST_CHALLENGEOFTHE7SISTERS_SUB_COUNT    7
#define QUEST_CUTEPOKEMON_SUB_COUNT               4
#define QUEST_WALLACEARMY_SUB_COUNT               5
#define QUEST_DEXCOMPLETION_SUB_COUNT             2
#define QUEST_KITCHENVOLUNTEERING_SUB_COUNT       5
#define QUEST_ARTISANBALLS_SUB_COUNT              7
#define QUEST_ARTISANBALLS2_SUB_COUNT             3
#define QUEST_NEIGHBORHOODCLEANUP_SUB_COUNT       5
#define QUEST_NEIGHBORHOODCLEANUP2_SUB_COUNT      4
#define QUEST_NEIGHBORHOODCLEANUP3_SUB_COUNT      3
#define QUEST_ROCKCOLLECTOR_SUB_COUNT             5
#define QUEST_HIDDENGROTTOMAPPING_SUB_COUNT       3
#define QUEST_ULTRAWORMHOLERESEARCH_SUB_COUNT     10
#define QUEST_WILDFIRERISK_SUB_COUNT              3
#define QUEST_THEBOYWHOCRIESWITHWOLVES_SUB_COUNT  9
#define QUEST_TAXICABTURNAROUND_SUB_COUNT         19
#define QUEST_PERSUASIVEPASSENGER_SUB_COUNT       3
#define QUEST_BODEGABURNOUT_SUB_COUNT             19
#define QUEST_WAREHOUSEWARFARE_SUB_COUNT          3
#define QUEST_RESTOREESPULEEGYM_SUB_COUNT              2
#define QUEST_RESTOREHODOUGYM_SUB_COUNT          7
#define QUEST_RESTOREZENZUGYM_SUB_COUNT     4
#define QUEST_RECRUITLOCALARTISTS_SUB_COUNT       3

#define SUB_QUEST_COUNT (\
        QUEST_FOODTRUCKBUREACRACY_SUB_COUNT + \
        QUEST_BREAKTHEINTERNET_SUB_COUNT + \
        QUEST_INSTALLNATUREPROBES_SUB_COUNT + \
        QUEST_RESTAURANTEXPANSION1_SUB_COUNT + \
        QUEST_RESTAURANTEXPANSION2_SUB_COUNT + \
        QUEST_HYBRIDCULTURE_SUB_COUNT + \
        QUEST_BUILDINGANEXHIBIT_SUB_COUNT + \
        QUEST_CONTRACTORPORYGON_SUB_COUNT + \
        QUEST_GETTHEBANDBACKTOGETHER_SUB_COUNT + \
        QUEST_CHALLENGEOFTHE7SISTERS_SUB_COUNT + \
        QUEST_CUTEPOKEMON_SUB_COUNT + \
        QUEST_WALLACEARMY_SUB_COUNT + \
        QUEST_DEXCOMPLETION_SUB_COUNT + \
        QUEST_KITCHENVOLUNTEERING_SUB_COUNT + \
        QUEST_ARTISANBALLS_SUB_COUNT + \
        QUEST_ARTISANBALLS2_SUB_COUNT + \
        QUEST_NEIGHBORHOODCLEANUP_SUB_COUNT + \
        QUEST_NEIGHBORHOODCLEANUP2_SUB_COUNT + \
        QUEST_NEIGHBORHOODCLEANUP3_SUB_COUNT + \
        QUEST_ROCKCOLLECTOR_SUB_COUNT + \
        QUEST_HIDDENGROTTOMAPPING_SUB_COUNT + \
        QUEST_ULTRAWORMHOLERESEARCH_SUB_COUNT + \
        QUEST_WILDFIRERISK_SUB_COUNT + \
        QUEST_THEBOYWHOCRIESWITHWOLVES_SUB_COUNT + \
        QUEST_TAXICABTURNAROUND_SUB_COUNT + \
        QUEST_PERSUASIVEPASSENGER_SUB_COUNT + \
        QUEST_BODEGABURNOUT_SUB_COUNT + \
        QUEST_WAREHOUSEWARFARE_SUB_COUNT + \
        QUEST_RESTOREESPULEEGYM_SUB_COUNT + \
        QUEST_RESTOREHODOUGYM_SUB_COUNT + \
        QUEST_RESTOREZENZUGYM_SUB_COUNT + \
        QUEST_RECRUITLOCALARTISTS_SUB_COUNT \
)

#define QUEST_ARRAY_COUNT (SUB_QUEST_COUNT > QUEST_COUNT ? SUB_QUEST_COUNT : QUEST_COUNT)

// ***********************************************************************
// Quest:Cute Pokémon
// ***********************************************************************

enum
{
    STATE_QUEST_CUTEPOKEMON_QUEST_NOT_STARTED,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_EISCUE,
    STATE_QUEST_CUTEPOKEMON_GAVE_EISCUE,
    STATE_QUEST_CUTEPOKEMON_WON_BATTLE_1,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_CORSOLA,
    STATE_QUEST_CUTEPOKEMON_GAVE_CORSOLA,
    STATE_QUEST_CUTEPOKEMON_WON_BATTLE_2,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_DUSKULL,
    STATE_QUEST_CUTEPOKEMON_GAVE_DUSKULL,
    STATE_QUEST_CUTEPOKEMON_WON_BATTLE_3,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_SCRAFTY,
    STATE_QUEST_CUTEPOKEMON_QUEST_COMPLETE,
};

#define ITEM_QUEST_CUTEPOKEMON_1 1
#define ITEM_QUEST_CUTEPOKEMON_2 2

// ***********************************************************************
// Quest: Angel Delivery
// ***********************************************************************
enum
{
    STATE_QUEST_ANGELDELIVERY_QUEST_NOT_STARTED,
    STATE_QUEST_ANGELDELIVERY_RECIEVED_BIKE,
    STATE_QUEST_ANGELDELIVERY_ABOUT_TO_DELIVER_ITEM,
    STATE_QUEST_ANGELDELIVERY_DELIVERED_ITEM,
    STATE_QUEST_ANGELDELIVERY_BEFORE_BATTLE,
    STATE_QUEST_ANGELDELIVERY_HAS_LOST_BATTLE,
    STATE_QUEST_ANGELDELIVERY_COMPLETED_QUEST,
};

#define ITEM_QUEST_ANGELDELIVERY_1 ITEM_MACH_BIKE
#define ITEM_QUEST_ANGELDELIVERY_2 ITEM_SCANNER

// ***********************************************************************
// Quest: VS Deoxys
// ***********************************************************************

enum
{
    STATE_QUEST_VSDEOXYS_NOT_STARTED,
    STATE_QUEST_VSDEOXYS_RECIVED_ROCK_SMASH_TM,
    STATE_QUEST_VSDEOXYS_AFTER_MINIOR_BATTLE,
    STATE_QUEST_VSDEOXYS_HAS_ENTERED_RESEARCH,
    STATE_QUEST_VSDEOXYS_COMPLETE_QUEST
};

// ***********************************************************************
// Quest: RPS
// ***********************************************************************

enum
{
    STATE_QUEST_RPS_NOT_STARTED,
    STATE_QUEST_RPS_STARTED,
    STATE_QUEST_RPS_COMPLETE,
    STATE_QUEST_RPS_STREAK_0,
    STATE_QUEST_RPS_STREAK_1,
    STATE_QUEST_RPS_STREAK_2,
    STATE_QUEST_RPS_STREAK_3,
    STATE_QUEST_RPS_STREAK_4,
    STATE_QUEST_RPS_STREAK_5,
    STATE_QUEST_RPS_STREAK_6,
    STATE_QUEST_RPS_STREAK_7,
    STATE_QUEST_RPS_STREAK_8,
    STATE_QUEST_RPS_STREAK_9,
    STATE_QUEST_RPS_STREAK_10,
    STATE_QUEST_RPS_REWARD,
    STATE_QUEST_RPS_DICE_GIVEN,
};

#define QUEST_RPS_BASE_WAGER          200
#define QUEST_RPS_WAGER               (QUEST_RPS_BASE_WAGER / 2)

#define QUEST_RPS_MAX_STREAK_LENGTH   10
#define QUEST_RPS_GIVE_REWARD         (QUEST_RPS_MAX_STREAK_LENGTH + 1)
#define QUEST_RPS_REWARD_GIVEN        (QUEST_RPS_GIVE_REWARD + 1)

// ***********************************************************************
// Quest: Drug Helmet Test
// ***********************************************************************

enum
{
    STATE_QUEST_DRUGHELMETTEST_NOT_STARTED,
    STATE_QUEST_DRUGHELMETTEST_LOST_BATTLE,
    STATE_QUEST_DRUGHELMETTEST_DEFEATED_ALL_THREE,
    STATE_QUEST_DRUGHELMETTEST_COMPLETED_QUEST,
};

#define ITEM_QUEST_DRUGHELMETTEST_REWARD 1

// ***********************************************************************
// Quest: Restore Tirabudin Gym
// ***********************************************************************

enum {
    STATE_QUEST_RESTORETIRABUDINGYM_NOT_STARTED,
    STATE_QUEST_RESTORETIRABUDINGYM_COMPLETED,
};

// ***********************************************************************
// Quest: Ultra Wormhole Research
// ***********************************************************************

enum
{
    TOTEM_POKEMON_0,
    TOTEM_POKEMON_1,
    TOTEM_POKEMON_2,
    TOTEM_POKEMON_3,
    TOTEM_POKEMON_4,
    TOTEM_POKEMON_5,
    TOTEM_POKEMON_6,
    TOTEM_POKEMON_7,
    TOTEM_POKEMON_8,
    TOTEM_POKEMON_9,
    TOTEM_POKEMON_10,
};

// ***********************************************************************
// Quest: Compulsive Healing Peer Support Group
// ***********************************************************************

enum
{
    STATE_QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP_NOT_STARTED,
    STATE_QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP_STARTED_QUEST,
    STATE_QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP_COMPLETE_QUEST
};

// ***********************************************************************
// Quest: Stress Cup
// ***********************************************************************

enum
{
    STATE_QUEST_STRESSCUP_NOT_STARTED,
    STATE_QUEST_STRESSCUP_STARTED_QUEST,
    STATE_QUEST_STRESSCUP_COMPLETE_QUEST,
};

// ***********************************************************************
// Quest: Rabies Outbreak
// ***********************************************************************

#define QUEST_RABIES_OUTBREAK_SPECIES SPECIES_PURRLOIN
#define QUEST_RABIES_OUTBREAK_MAP     MAP_GLAVEZ_HEIGHTS
#define QUEST_RABIES_OUTBREAK_COUNT   10
#define ITEM_QUEST_RABIES_OUTBREAK_REWARD ITEM_REPEL

enum
{
    STATE_QUEST_RABIES_NOT_STARTED,
    STATE_QUEST_RABIES_STARTED,
    STATE_QUEST_RABIES_DEFEATED_1,
    STATE_QUEST_RABIES_DEFEATED_2,
    STATE_QUEST_RABIES_DEFEATED_3,
    STATE_QUEST_RABIES_DEFEATED_4,
    STATE_QUEST_RABIES_DEFEATED_5,
    STATE_QUEST_RABIES_DEFEATED_6,
    STATE_QUEST_RABIES_DEFEATED_7,
    STATE_QUEST_RABIES_DEFEATED_8,
    STATE_QUEST_RABIES_DEFEATED_9,
    STATE_QUEST_RABIES_REWARD,
    STATE_QUEST_RABIES_COMPLETE,
};

// ***********************************************************************
// Quest: Smoothie Crafting
// ***********************************************************************

#define QUEST_SMOOTHIE_CRAFTING_BERRY_1 ITEM_PECHA_BERRY
#define QUEST_SMOOTHIE_CRAFTING_BERRY_2 ITEM_NANAB_BERRY
#define QUEST_SMOOTHIE_CRAFTING_BERRY_3 ITEM_RABUTA_BERRY
#define QUEST_SMOOTHIE_CRAFTING_QUANTITY_1 3
#define QUEST_SMOOTHIE_CRAFTING_QUANTITY_2 2
#define QUEST_SMOOTHIE_CRAFTING_QUANTITY_3 1
#define QUEST_SMOOTHIE_CRAFTING_PRODUCT ITEM_SHERBET_SURPRISE
#define QUEST_SMOOTHIE_CRAFTING_MAP MAP_CHASILLA_ICE_CREAM_SHOP

enum
{
    STATE_QUEST_SMOOTHIECRAFTING_NOT_STARTED,
    STATE_QUEST_SMOOTHIECRAFTING_STARTED,
    STATE_QUEST_SMOOTHIECRAFTING_HAS_ITEMS,
    STATE_QUEST_SMOOTHIECRAFTING_REWARD,
    STATE_QUEST_SMOOTHIECRAFTING_COMPLETE,
};

// ***********************************************************************
// Quest: Freshwater Evolution
// ***********************************************************************

#define QUEST_FRESHWATER_EVOLUTION_SPECIES SPECIES_OCTILLERY
#define QUEST_FRESHWATER_EVOLUTION_MAP     MAP_HALERBA_WILDS_SPRING
#define QUEST_FRESHWATER_EVOLUTION_ITEM    ITEM_SOOTHE_BELL

enum
{
    STATE_QUEST_FRESHWATER_NOT_STARTED,
    STATE_QUEST_FRESHWATER_STARTED,
    STATE_QUEST_FRESHWATER_REWARD,
    STATE_QUEST_FRESHWATER_COMPLETE,
};

// ***********************************************************************
// Quest: Hodou Tunnels
// ***********************************************************************

#define MAP_QUEST_HODOUTUNNELS           MAP_HODOU_CITY_TUNNEL
#define MAP_QUEST_HODOUTUNNELS_PARENT    MAP_HODOU_CITY
#define ITEM_QUEST_HODOUTUNNELS_REWARD   ITEM_REPEL
#define ITEM_QUEST_HODOUTUNNELS_TREASURE ITEM_N_SOLARIZER

enum
{
    STATE_QUEST_HODOUTUNNELS_NOT_STARTED,
    STATE_QUEST_HODOUTUNNELS_STARTED,
    STATE_QUEST_HODOUTUNNELS_TALKED_TO_ELDER,
    STATE_QUEST_HODOUTUNNELS_DISCOVERED_SCROLL,
    STATE_QUEST_HODOUTUNNELS_HAS_TREASURE,
    STATE_QUEST_HODOUTUNNELS_REWARD,
    STATE_QUEST_HODOUTUNNELS_COMPLETE,
};

// ***********************************************************************
// Quest: Hashtag Psyop
// ***********************************************************************

#define MAP_QUEST_PSYOP MAP_ROUTE_A
#define SPECIES_QUEST_PSYOP_TARGET SPECIES_SINISTEA_PHONY
#define SPECIES_QUEST_PSYOP_REWARD SPECIES_SINISTEA_ANTIQUE
#define ITEM_QUEST_PSYOP_TARGET_BALL ITEM_HEAL_BALL

enum QuestPsyopErrors
{
    QUEST_PSYOP_NOT_SPECIES,
    QUEST_PSYOP_IS_REWARD_SPECIES,
    QUEST_PSYOP_NO_EFFORT_AND_BALL,
    QUEST_PSYOP_NO_EFFORT,
    QUEST_PSYOP_NO_BALL,
    QUEST_PSYOP_READY_TO_TRANSFORM,
};

enum
{
    STATE_QUEST_PSYOP_NOT_STARTED,
    STATE_QUEST_PSYOP_STARTED,
    STATE_QUEST_PSYOP_COMPLETE,
};

// ***********************************************************************
// Quest: Between A Stone and A Hard Place
// ***********************************************************************

#define MAP_QUEST_BETWEENASTONEANDAHARDPLACE MAP_CAPHE_CITY_GRUNTOFFICE
#define NUM_QUEST_BETWEENASTONEANDAHARDPLACE_TROLLEY_RIDES 10
#define FLAG_DELAY_ROCK_COLLECTOR FLAG_TEMP_5

enum
{
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_NOT_STARTED,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_STARTED,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_1,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_2,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_3,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_4,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_5,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_6,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_7,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_8,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_GRUNT_RODE_9,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_REWARD,
    STATE_QUEST_BETWEENASTONEANDAHARDPLACE_COMPLETE,
};

// ***********************************************************************
// Quest: Rock Collector
// ***********************************************************************

#define ITEM_QUEST_ROCKCOLLECTOR_KIT ITEM_SCANNER
#define ITEM_QUEST_ROCKCOLLECTOR_NEED_1 ITEM_FIRE_STONE
#define ITEM_QUEST_ROCKCOLLECTOR_NEED_2 ITEM_WATER_STONE
#define ITEM_QUEST_ROCKCOLLECTOR_NEED_3 ITEM_THUNDER_STONE
#define ITEM_QUEST_ROCKCOLLECTOR_NEED_4 ITEM_LEAF_STONE
#define ITEM_QUEST_ROCKCOLLECTOR_NEED_5 ITEM_MOON_STONE
#define ITEM_QUEST_ROCKCOLLECTOR_REWARD ITEM_FIRE_STONE

enum
{
    STATE_QUEST_ROCKCOLLECTOR_NOT_STARTED,
    STATE_QUEST_ROCKCOLLECTOR_STARTED,
    STATE_QUEST_ROCKCOLLECTOR_REWARD,
    STATE_QUEST_ROCKCOLLECTOR_COMPLETE,
};

// ***********************************************************************
// Quest: Bodega Burnout
// ***********************************************************************

#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_CAPHE ITEM_BODEGA_DELIVERY_1
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_QIU ITEM_BODEGA_DELIVERY_2
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_HALAI ITEM_BODEGA_DELIVERY_3
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_OROLAND ITEM_BODEGA_DELIVERY_4
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_TORA ITEM_BODEGA_DELIVERY_5
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_HALERBA ITEM_BODEGA_DELIVERY_6
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_CRESALTA ITEM_BODEGA_DELIVERY_7
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_IRISINA ITEM_BODEGA_DELIVERY_8
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_HODOU ITEM_BODEGA_DELIVERY_9
#define ITEM_QUEST_BODEGABURNOUT_DELIVERY_ZENZU ITEM_BODEGA_DELIVERY_10

#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_CAPHE MAP_ROUTE10
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_QIU MAP_PIOCA_BRIDGE
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_HALAI MAP_ROUTE1
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_OROLAND MAP_NAVAL_BASE_EXTERIOR
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_TORA MAP_ROUTE13
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_HALERBA MAP_HALERBA_WILDS
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_CRESALTA MAP_ROUTE_E
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_IRISINA MAP_LANJING_TUNNEL_B2F
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_HODOU MAP_ROUTE100
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_ZENZU MAP_ROUTE3
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_CUCONU MAP_ROUTE11
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_GLAVEZ MAP_HALERBA_WILDS
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_PERLACIA MAP_ROUTE14
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_PETAROSA MAP_ARANTRAZ
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_ESPULEE MAP_ROUTE2
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_TIRABUDIN MAP_ROUTE12
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_CHASILLA MAP_ROUTE7
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_MERMEREZA MAP_ROUTE_A
#define MAP_QUEST_BODEGABURNOUT_DELIVERY_TARGET_CURENO MAP_ROUTE4

#define OBJ_EVENT_GFX_BODEGABURNOUT_SHOPUNIONREP            OBJ_EVENT_GFX_TWIN
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_STRENGTH_H      OBJ_EVENT_GFX_BOY_1
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_A               OBJ_EVENT_GFX_GIRL_1
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_B               OBJ_EVENT_GFX_BOY_2
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_CUT_C           OBJ_EVENT_GFX_GIRL_2
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_STRENGTH_I      OBJ_EVENT_GFX_LITTLE_BOY
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_ROCK_SMASH_F    OBJ_EVENT_GFX_LITTLE_GIRL
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_WHIRLPOOL_J     OBJ_EVENT_GFX_BOY_3
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_ROCK_SMASH_G    OBJ_EVENT_GFX_GIRL_3
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_CUT_D           OBJ_EVENT_GFX_RICH_BOY
#define OBJ_EVENT_GFX_BODEGABURNOUTDELIVERY_CUT_E           OBJ_EVENT_GFX_WOMAN_1
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_ROCK_SMASH_O      OBJ_EVENT_GFX_FAT_MAN
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_CUT_M             OBJ_EVENT_GFX_POKEFAN_F
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_STRENGTH_Q        OBJ_EVENT_GFX_MAN_1
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_DIVE_N            OBJ_EVENT_GFX_WOMAN_2
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_K                 OBJ_EVENT_GFX_EXPERT_M
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_ROCK_SMASH_P      OBJ_EVENT_GFX_EXPERT_F
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_L                 OBJ_EVENT_GFX_MAN_2
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_WHIRLPOOL_S       OBJ_EVENT_GFX_WOMAN_3
#define OBJ_EVENT_GFX_BODEGABURNOUTRESCUE_STRENGTH_R        OBJ_EVENT_GFX_POKEFAN_M

#define NUM_QUEST_BODEGABURNOUT_REQUIRED_SUBQUESTS 3

enum BodegaBurnoutTypes
{
    QUEST_BODEGABURNOUT_TYPE_DELIVERY,
    QUEST_BODEGABURNOUT_TYPE_RESCUE,
    QUEST_BODEGABURNOUT_TYPE_COUNT
};

#endif // GUARD_CONSTANTS_QUESTS_H
