#ifndef GUARD_CONSTANTS_QUESTS_H
#define GUARD_CONSTANTS_QUESTS_H

enum QuestMenuScriptCommandParameters
{
    QUEST_MENU_OPEN,               //opens the quest menu (questId = 0)
    QUEST_MENU_UNLOCK_QUEST,       //questId = QUEST_X (0-indexed)
    QUEST_MENU_SET_ACTIVE,         //questId = QUEST_X (0-indexed)
    QUEST_MENU_SET_REWARD,         //questId = QUEST_X (0-indexed)
    QUEST_MENU_COMPLETE_QUEST,     //questId = QUEST_X (0-indexed)
    QUEST_MENU_CHECK_UNLOCKED,     //checks if questId has been unlocked. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_INACTIVE,     //check if a questID is inactive. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_ACTIVE,       //checks if questId has been unlocked. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_REWARD,       //checks if questId is in Reward state. Returns result to gSpecialVar_Result
    QUEST_MENU_CHECK_COMPLETE,     //checks if questId has been completed. Returns result to gSpecialVar_Result
    QUEST_MENU_BUFFER_QUEST_NAME,  //buffers a quest name to gStringVar1
    QUEST_MENU_SET_FAVORITE,
    QUEST_MENU_UNCOMPLETE_QUEST,
};

enum QuestIdList
{
    QUEST_PLAYERSADVENTURE,
    QUEST_MANHUNT,
    QUEST_HOWDISAPPOINTING,
    QUEST_LETSBURNTHISMOTHERDOWN,
    QUEST_RESTOREESPULEEGYM,
    QUEST_RESTOREZENZUGYM,
    QUEST_RESTOREHODOUGYM,
    QUEST_RESTORETIRABUDINGYM,
    QUEST_IMPROVBATTLING,
    QUEST_BATTLEARCADEMINIQUEST,
    QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP,
    QUEST_CHALLENGEOFTHE7SISTERS,
    QUEST_STRESSCUP,
    QUEST_DRUGHELMETTEST,
    QUEST_RPS,
    QUEST_RABIESOUTBREAK,
    QUEST_VSDEOXYS,
    QUEST_FRESHWATEREVOLUTION,
    QUEST_SMOOTHIECRAFTING,
    QUEST_HODOUTUNNELS,
    QUEST_PSYOP,
    QUEST_BREAKTHEINTERNET,
    QUEST_BETWEENASTONEANDAHARDPLACE,
    QUEST_ROCKCOLLECTOR,
    QUEST_TAXICABTURNAROUND,
    QUEST_PERSUASIVEPASSENGER,
    QUEST_BODEGABURNOUT,
    QUEST_WAREHOUSEWARFARE,
    QUEST_ANGELDELIVERY,
    QUEST_GETTHEBANDBACKTOGETHER,
    QUEST_TEACHATRAINERTOFISH,
    QUEST_WILDFIRERISK,
    QUEST_IBELIEVEICANFLY,
    QUEST_HUNKYJESUS,
    QUEST_ALLTHATGLITTERSMIGHTBEGOLD,
    QUEST_HANG20,
    QUEST_WHIRLPOOLFERRY,
    QUEST_RESTAURANTEXPANSION1,
    QUEST_RESTAURANTEXPANSION2,
    QUEST_CULTURALPURITY,
    QUEST_HYBRIDCULTURE,
    QUEST_ALOHAFROMALOLA,
    QUEST_BUILDINGANEXHIBIT,
    QUEST_STEALTHEAXE,
    QUEST_NERIENEQUEST2,
    QUEST_ECOSYSTEMIMPACTSTUDY,
    QUEST_POISONEDLAKEINVESTIGATION,
    QUEST_SHUTDOWNMEDICINEMAN,
    QUEST_INVERSEHALLUCINOGENIC,
    QUEST_FRANCHISEDRAG,
    QUEST_POPUPEVENT,
    QUEST_DIGGINGUPADAORASDIRT,
    QUEST_FREETHEINNOCENT,
    QUEST_FINDTHEGUILTY,
    QUEST_RETURNDOLL,
    QUEST_KITCHENVOLUNTEERING,
    QUEST_THEBOYWHOCRIESWITHWOLVES,
    QUEST_FLIGHTPATTERNS,
    QUEST_INSTALLNATUREPROBES,
    QUEST_MANOFMANYHATS,
    QUEST_CUTEPOKEMON,
    QUEST_ARTISANBALLS1,
    QUEST_ARTISANBALLS2,
    QUEST_ARTISANBALLS3,
    QUEST_STOLENTRADE,
    QUEST_FOODTRUCKBUREACRACY,
    QUEST_CONTRACTORPORYGON,
    QUEST_LASTMUSICVENUEINRESIDO,
    QUEST_RECRUITLOCALARTISTS,
    QUEST_REDOMUGGING,
    QUEST_WALLACEARMY,
    QUEST_BUILDINGSCOPE,
    QUEST_BUTONLYINMYBACKYARD,
    QUEST_NEIGHBORHOODCLEANUP,
    QUEST_NEIGHBORHOODCLEANUP2,
    QUEST_NEIGHBORHOODCLEANUP3,
    QUEST_MUTUALAIDFUND,
    QUEST_MUTUALAIDOUTREACH,
    QUEST_GARDENCLEANUP,
    QUEST_THELEANINGTOWER,
    QUEST_HIDDENGROTTOMAPPING,
    QUEST_ULTRAWORMHOLERESEARCH,
    QUEST_GF_ROUNDUP,
    QUEST_GF_STRIDER,
    QUEST_GF_PSF,
    QUEST_GF_MM,
    QUEST_GF_LITTLESPARROW,
    QUEST_GF_JACKIECAT,
    QUEST_GF_CRIM,
    QUEST_DEXCOMPLETION,
    QUEST_SKILLLIBRARY,
    QUEST_COUNT,
};

enum SubQuestDefines
{
    SUB_QUEST_1,
    SUB_QUEST_2,
    SUB_QUEST_3,
    SUB_QUEST_4,
    SUB_QUEST_5,
    SUB_QUEST_6,
    SUB_QUEST_7,
    SUB_QUEST_8,
    SUB_QUEST_9,
    SUB_QUEST_10,
    SUB_QUEST_11,
    SUB_QUEST_12,
    SUB_QUEST_13,
    SUB_QUEST_14,
    SUB_QUEST_15,
    SUB_QUEST_16,
    SUB_QUEST_17,
    SUB_QUEST_18,
    SUB_QUEST_19,
    SUB_QUEST_20,
    SUB_QUEST_21,
    SUB_QUEST_22,
    SUB_QUEST_23,
    SUB_QUEST_24,
    SUB_QUEST_25,
    SUB_QUEST_26,
    SUB_QUEST_27,
    SUB_QUEST_28,
    SUB_QUEST_29,
    SUB_QUEST_30,
};

#define QUEST_BREAKTHEINTERNET_SUB_COUNT          3
#define QUEST_INSTALLNATUREPROBES_SUB_COUNT       3
#define QUEST_RESTAURANTEXPANSION1_SUB_COUNT      4
#define QUEST_RESTAURANTEXPANSION2_SUB_COUNT      5
#define QUEST_HYBRIDCULTURE_SUB_COUNT             3
#define QUEST_BUILDINGANEXHIBIT_SUB_COUNT         4
#define QUEST_CONTRACTORPORYGON_SUB_COUNT         3
#define QUEST_GETTHEBANDBACKTOGETHER_SUB_COUNT    5
#define QUEST_CHALLENGEOFTHE7SISTERS_SUB_COUNT    7
#define QUEST_CUTEPOKEMON_SUB_COUNT               4
#define QUEST_WALLACEARMY_SUB_COUNT               5
#define QUEST_DEXCOMPLETION_SUB_COUNT             2
#define QUEST_KITCHENVOLUNTEERING_SUB_COUNT       5
#define QUEST_ARTISANBALLS_SUB_COUNT              7
#define QUEST_ARTISANBALLS2_SUB_COUNT             3
#define QUEST_NEIGHBORHOODCLEANUP_SUB_COUNT       5
#define QUEST_NEIGHBORHOODCLEANUP2_SUB_COUNT      4
#define QUEST_NEIGHBORHOODCLEANUP3_SUB_COUNT      3
#define QUEST_ROCKCOLLECTOR_SUB_COUNT             10
#define QUEST_HIDDENGROTTOMAPPING_SUB_COUNT       3
#define QUEST_ULTRAWORMHOLERESEARCH_SUB_COUNT     10
#define QUEST_WILDFIRERISK_SUB_COUNT              3
#define QUEST_THEBOYWHOCRIESWITHWOLVES_SUB_COUNT  9
#define QUEST_TAXICABTURNAROUND_SUB_COUNT         19
#define QUEST_PERSUASIVEPASSENGER_SUB_COUNT       3
#define QUEST_BODEGABURNOUT_SUB_COUNT             19
#define QUEST_WAREHOUSEWARFARE_SUB_COUNT          3
#define QUEST_RESTOREESPULEEGYM_SUB_COUNT              2
#define QUEST_RESTOREHODOUGYM_SUB_COUNT          7
#define QUEST_RESTOREZENZUGYM_SUB_COUNT     4
#define QUEST_RECRUITLOCALARTISTS_SUB_COUNT       3

#define SUB_QUEST_COUNT (\
        QUEST_BREAKTHEINTERNET_SUB_COUNT \
        + QUEST_INSTALLNATUREPROBES_SUB_COUNT \
        + QUEST_RESTAURANTEXPANSION1_SUB_COUNT \
        + QUEST_RESTAURANTEXPANSION2_SUB_COUNT \
        + QUEST_HYBRIDCULTURE_SUB_COUNT \
        + QUEST_BUILDINGANEXHIBIT_SUB_COUNT \
        + QUEST_CONTRACTORPORYGON_SUB_COUNT \
        + QUEST_GETTHEBANDBACKTOGETHER_SUB_COUNT \
        + QUEST_CHALLENGEOFTHE7SISTERS_SUB_COUNT \
        + QUEST_CUTEPOKEMON_SUB_COUNT \
        + QUEST_WALLACEARMY_SUB_COUNT \
        + QUEST_DEXCOMPLETION_SUB_COUNT \
        + QUEST_KITCHENVOLUNTEERING_SUB_COUNT \
        + QUEST_ARTISANBALLS_SUB_COUNT \
        + QUEST_ARTISANBALLS2_SUB_COUNT \
        + QUEST_NEIGHBORHOODCLEANUP_SUB_COUNT \
        + QUEST_NEIGHBORHOODCLEANUP2_SUB_COUNT \
        + QUEST_NEIGHBORHOODCLEANUP3_SUB_COUNT \
        + QUEST_ROCKCOLLECTOR_SUB_COUNT \
        + QUEST_HIDDENGROTTOMAPPING_SUB_COUNT \
        + QUEST_ULTRAWORMHOLERESEARCH_SUB_COUNT \
        + QUEST_WILDFIRERISK_SUB_COUNT \
        + QUEST_THEBOYWHOCRIESWITHWOLVES_SUB_COUNT \
        + QUEST_TAXICABTURNAROUND_SUB_COUNT \
        + QUEST_PERSUASIVEPASSENGER_SUB_COUNT \
        + QUEST_BODEGABURNOUT_SUB_COUNT \
        + QUEST_WAREHOUSEWARFARE_SUB_COUNT \
        + QUEST_RESTOREESPULEEGYM_SUB_COUNT \
        + QUEST_RESTOREHODOUGYM_SUB_COUNT \
        + QUEST_RESTOREZENZUGYM_SUB_COUNT \
        + QUEST_RECRUITLOCALARTISTS_SUB_COUNT \
        )

#define QUEST_ARRAY_COUNT (SUB_QUEST_COUNT > QUEST_COUNT ? SUB_QUEST_COUNT : QUEST_COUNT)

// ***********************************************************************
// Quest:Cute Pokémon
// ***********************************************************************

enum
{
    STATE_QUEST_CUTEPOKEMON_QUEST_NOT_STARTED,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_EISCUE,
    STATE_QUEST_CUTEPOKEMON_GAVE_EISCUE,
    STATE_QUEST_CUTEPOKEMON_WON_BATTLE_1,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_CORSOLA,
    STATE_QUEST_CUTEPOKEMON_GAVE_CORSOLA,
    STATE_QUEST_CUTEPOKEMON_WON_BATTLE_2,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_DUSKULL,
    STATE_QUEST_CUTEPOKEMON_GAVE_DUSKULL,
    STATE_QUEST_CUTEPOKEMON_WON_BATTLE_3,
    STATE_QUEST_CUTEPOKEMON_GUESSING_FOR_SCRAFTY,
    STATE_QUEST_CUTEPOKEMON_QUEST_COMPLETE,
};

#define ITEM_QUEST_CUTEPOKEMON_1 1
#define ITEM_QUEST_CUTEPOKEMON_2 2

// ***********************************************************************
// Quest: Angel Delivery
// ***********************************************************************
enum
{
    STATE_QUEST_ANGELDELIVERY_QUEST_NOT_STARTED,
    STATE_QUEST_ANGELDELIVERY_RECIEVED_BIKE,
    STATE_QUEST_ANGELDELIVERY_ABOUT_TO_DELIVER_ITEM,
    STATE_QUEST_ANGELDELIVERY_DELIVERED_ITEM,
    STATE_QUEST_ANGELDELIVERY_BEFORE_BATTLE,
    STATE_QUEST_ANGELDELIVERY_HAS_LOST_BATTLE,
    STATE_QUEST_ANGELDELIVERY_COMPLETED_QUEST,
};

#define ITEM_QUEST_ANGELDELIVERY_1 ITEM_MACH_BIKE
#define ITEM_QUEST_ANGELDELIVERY_2 ITEM_SCANNER

// ***********************************************************************
// Quest: VS Deoxys
// ***********************************************************************

enum
{
    STATE_QUEST_VSDEOXYS_NOT_STARTED,
    STATE_QUEST_VSDEOXYS_RECIVED_ROCK_SMASH_TM,
    STATE_QUEST_VSDEOXYS_AFTER_MINIOR_BATTLE,
    STATE_QUEST_VSDEOXYS_HAS_ENTERED_RESEARCH,
    STATE_QUEST_VSDEOXYS_COMPLETE_QUEST
};

// ***********************************************************************
// Quest: RPS
// ***********************************************************************

enum
{
    STATE_QUEST_RPS_NOT_STARTED,
    STATE_QUEST_RPS_STARTED,
    STATE_QUEST_RPS_COMPLETE,
    STATE_QUEST_RPS_STREAK_0,
    STATE_QUEST_RPS_STREAK_1,
    STATE_QUEST_RPS_STREAK_2,
    STATE_QUEST_RPS_STREAK_3,
    STATE_QUEST_RPS_STREAK_4,
    STATE_QUEST_RPS_STREAK_5,
    STATE_QUEST_RPS_STREAK_6,
    STATE_QUEST_RPS_STREAK_7,
    STATE_QUEST_RPS_STREAK_8,
    STATE_QUEST_RPS_STREAK_9,
    STATE_QUEST_RPS_STREAK_10,
    STATE_QUEST_RPS_REWARD,
    STATE_QUEST_RPS_DICE_GIVEN,
};

#define QUEST_RPS_BASE_WAGER          200
#define QUEST_RPS_WAGER               (QUEST_RPS_BASE_WAGER / 2)

#define QUEST_RPS_MAX_STREAK_LENGTH   10
#define QUEST_RPS_GIVE_REWARD         (QUEST_RPS_MAX_STREAK_LENGTH + 1)
#define QUEST_RPS_REWARD_GIVEN        (QUEST_RPS_GIVE_REWARD + 1)

// ***********************************************************************
// Quest: Drug Helmet Test
// ***********************************************************************

enum
{
    STATE_QUEST_DRUGHELMETTEST_NOT_STARTED,
    STATE_QUEST_DRUGHELMETTEST_LOST_BATTLE,
    STATE_QUEST_DRUGHELMETTEST_DEFEATED_ALL_THREE,
    STATE_QUEST_DRUGHELMETTEST_COMPLETED_QUEST,
};

#define ITEM_QUEST_DRUGHELMETTEST_REWARD 1

// ***********************************************************************
// Quest: Restore Tirabudin Gym
// ***********************************************************************

enum {
    STATE_QUEST_RESTORETIRABUDINGYM_NOT_STARTED,
    STATE_QUEST_RESTORETIRABUDINGYM_COMPLETED,
};

// ***********************************************************************
// Quest: Ultra Wormhole Research
// ***********************************************************************

enum
{
    TOTEM_POKEMON_0,
    TOTEM_POKEMON_1,
    TOTEM_POKEMON_2,
    TOTEM_POKEMON_3,
    TOTEM_POKEMON_4,
    TOTEM_POKEMON_5,
    TOTEM_POKEMON_6,
    TOTEM_POKEMON_7,
    TOTEM_POKEMON_8,
    TOTEM_POKEMON_9,
    TOTEM_POKEMON_10,
};

// ***********************************************************************
// Quest: Compulsive Healing Peer Support Group
// ***********************************************************************

enum
{
    STATE_QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP_NOT_STARTED,
    STATE_QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP_STARTED_QUEST,
    STATE_QUEST_COMPULSIVEHEALINGPEERSUPPORTGROUP_COMPLETE_QUEST
};

// ***********************************************************************
// Quest: Stress Cup
// ***********************************************************************

enum
{
    STATE_QUEST_STRESSCUP_NOT_STARTED,
    STATE_QUEST_STRESSCUP_STARTED_QUEST,
    STATE_QUEST_STRESSCUP_COMPLETE_QUEST,
};

#endif // GUARD_CONSTANTS_QUESTS_H
