#ifndef GUARD_QUEST_LOGIC_CONSTANTS_H
#define GUARD_QUEST_LOGIC_CONSTANTS_H

#define FALSE_TIMELINE_NONE_COMPLETE 0
#define FALSE_TIMELINE_MAN_COMPLETE 1
#define FALSE_TIMELINE_HOW_COMPLETE 2
#define FALSE_TIMELINE_BURN_COMPLETE 3
#define FALSE_TIMELINE_HOW_BURN_COMPLETE 4
#define FALSE_TIMELINE_MAN_BURN_COMPLETE 5
#define FALSE_TIMELINE_MAN_HOW_COMPLETE 6
#define FALSE_TIMELINE_MAN_HOW_BURN_COMPLETE 7

#define QUEST_RABIES_OUTBREAK_SPECIES SPECIES_PURRLOIN
#define QUEST_RABIES_OUTBREAK_MAP     MAP_GLAVEZ_HEIGHTS
#define QUEST_RABIES_OUTBREAK_COUNT   10

#define SPECIES_QUEST_FLIGHT_PATTERNS SPECIES_MURKROW
#define SPECIES_QUEST_FLIGHT_PATTERNS_BOSS SPECIES_HONCHKROW
#define LEVEL_QUEST_FLIGHT_PATTERNS 16
#define LEVEL_QUEST_FLIGHT_PATTERNS_BOSS 55

#define MAPSEC_QUEST_FLIGHT_PATTERNS_1      MAPSEC_ARANTRAZ
#define MAPSEC_QUEST_FLIGHT_PATTERNS_2      MAPSEC_POPIDORA_PIER
#define MAPSEC_QUEST_FLIGHT_PATTERNS_3      MAPSEC_ROUTE_B
#define MAPSEC_QUEST_FLIGHT_PATTERNS_4      MAPSEC_ROUTE6
#define MAPSEC_QUEST_FLIGHT_PATTERNS_5      MAPSEC_ROUTE18
#define MAPSEC_QUEST_FLIGHT_PATTERNS_6      MAPSEC_ROUTE13
#define MAPSEC_QUEST_FLIGHT_PATTERNS_7      MAPSEC_ROUTE100
#define MAPSEC_QUEST_FLIGHT_PATTERNS_NONE   MAPSEC_NONE

#endif // GUARD_QUEST_LOGIC_CONSTANTS_H
