#ifndef GUARD_REGIONMAPSEC_H
#define GUARD_REGIONMAPSEC_H

#define MAPSEC_LITTLEROOT_TOWN	0x0
#define MAPSEC_OLDALE_TOWN	0x1
#define MAPSEC_DEWFORD_TOWN	0x2
#define MAPSEC_LAVARIDGE_TOWN	0x3
#define MAPSEC_FALLARBOR_TOWN	0x4
#define MAPSEC_VERDANTURF_TOWN	0x5
#define MAPSEC_PACIFIDLOG_TOWN	0x6
#define MAPSEC_PETALBURG_CITY	0x7
#define MAPSEC_SLATEPORT_CITY	0x8
#define MAPSEC_MAUVILLE_CITY	0x9
#define MAPSEC_RUSTBORO_CITY	0xA
#define MAPSEC_FORTREE_CITY	0xB
#define MAPSEC_LILYCOVE_CITY	0xC
#define MAPSEC_MOSSDEEP_CITY	0xD
#define MAPSEC_SOOTOPOLIS_CITY	0xE
#define MAPSEC_EVER_GRANDE_CITY	0xF
#define MAPSEC_ROUTE_101	0x10
#define MAPSEC_ROUTE_102	0x11
#define MAPSEC_ROUTE_103	0x12
#define MAPSEC_ROUTE_104	0x13
#define MAPSEC_ROUTE_105	0x14
#define MAPSEC_ROUTE_106	0x15
#define MAPSEC_ROUTE_107	0x16
#define MAPSEC_ROUTE_108	0x17
#define MAPSEC_ROUTE_109	0x18
#define MAPSEC_ROUTE_110	0x19
#define MAPSEC_ROUTE_111	0x1A
#define MAPSEC_ROUTE_112	0x1B
#define MAPSEC_ROUTE_113	0x1C
#define MAPSEC_ROUTE_114	0x1D
#define MAPSEC_ROUTE_115	0x1E
#define MAPSEC_ROUTE_116	0x1F
#define MAPSEC_ROUTE_117	0x20
#define MAPSEC_ROUTE_118	0x21
#define MAPSEC_ROUTE_119	0x22
#define MAPSEC_ROUTE_120	0x23
#define MAPSEC_ROUTE_121	0x24
#define MAPSEC_ROUTE_122	0x25
#define MAPSEC_ROUTE_123	0x26
#define MAPSEC_ROUTE_124	0x27
#define MAPSEC_ROUTE_125	0x28
#define MAPSEC_ROUTE_126	0x29
#define MAPSEC_ROUTE_127	0x2A
#define MAPSEC_ROUTE_128	0x2B
#define MAPSEC_ROUTE_129	0x2C
#define MAPSEC_ROUTE_130	0x2D
#define MAPSEC_ROUTE_131	0x2E
#define MAPSEC_ROUTE_132	0x2F
#define MAPSEC_ROUTE_133	0x30
#define MAPSEC_ROUTE_134	0x31
#define MAPSEC_UNDERWATER_124	0x32
#define MAPSEC_UNDERWATER_126	0x33
#define MAPSEC_UNDERWATER_127	0x34
#define MAPSEC_UNDERWATER_128	0x35
#define MAPSEC_UNDERWATER_SOOTOPOLIS	0x36
#define MAPSEC_GRANITE_CAVE	0x37
#define MAPSEC_MT_CHIMNEY	0x38
#define MAPSEC_SAFARI_ZONE	0x39
#define MAPSEC_BATTLE_FRONTIER	0x3A
#define MAPSEC_PETALBURG_WOODS	0x3B
#define MAPSEC_RUSTURF_TUNNEL	0x3C
#define MAPSEC_ABANDONED_SHIP	0x3D
#define MAPSEC_NEW_MAUVILLE	0x3E
#define MAPSEC_METEOR_FALLS	0x3F
#define MAPSEC_METEOR_FALLS2	0x40
#define MAPSEC_MT_PYRE	0x41
#define MAPSEC_AQUA_HIDEOUT_OLD	0x42
#define MAPSEC_SHOAL_CAVE	0x43
#define MAPSEC_SEAFLOOR_CAVERN	0x44
#define MAPSEC_UNDERWATER_SEAFLOOR_CAVERN	0x45
#define MAPSEC_VICTORY_ROAD	0x46
#define MAPSEC_MIRAGE_ISLAND	0x47
#define MAPSEC_CAVE_OF_ORIGIN	0x48
#define MAPSEC_SOUTHERN_ISLAND	0x49
#define MAPSEC_FIERY_PATH	0x4A
#define MAPSEC_FIERY_PATH2	0x4B
#define MAPSEC_JAGGED_PASS	0x4C
#define MAPSEC_JAGGED_PASS2	0x4D
#define MAPSEC_SEALED_CHAMBER	0x4E
#define MAPSEC_UNDERWATER_SEALED_CHAMBER	0x4F
#define MAPSEC_SCORCHED_SLAB	0x50
#define MAPSEC_ISLAND_CAVE	0x51
#define MAPSEC_DESERT_RUINS	0x52
#define MAPSEC_ANCIENT_TOMB	0x53
#define MAPSEC_INSIDE_OF_TRUCK	0x54
#define MAPSEC_SKY_PILLAR	0x55
#define MAPSEC_SECRET_BASE	0x56
#define MAPSEC_DYNAMIC	0x57
#define MAPSEC_AQUA_HIDEOUT	0x58
#define MAPSEC_MAGMA_HIDEOUT	0x59
#define MAPSEC_MIRAGE_TOWER	0x5A
#define MAPSEC_BIRTH_ISLAND	0x5B
#define MAPSEC_FARAWAY_ISLAND	0x5C
#define MAPSEC_ARTISAN_CAVE	0x5D
#define MAPSEC_MARINE_CAVE	0x5E
#define MAPSEC_UNDERWATER_MARINE_CAVE	0x5F
#define MAPSEC_TERRA_CAVE	0x60
#define MAPSEC_UNDERWATER_105	0x61
#define MAPSEC_UNDERWATER_125	0x62
#define MAPSEC_UNDERWATER_129	0x63
#define MAPSEC_DESERT_UNDERPASS	0x64
#define MAPSEC_ALTERING_CAVE	0x65
#define MAPSEC_NAVEL_ROCK	0x66
#define MAPSEC_TRAINER_HILL	0x67

enum
{
    MAPSEC_CUCONU_TOWN = (MAPSEC_TRAINER_HILL + 1),
    MAPSEC_ROUTE6,
    MAPSEC_GLAVEZ_HILL,
    MAPSEC_ROUTE8,
    MAPSEC_MERMEREZA_CITY,
    MAPSEC_ROUTE10,
    MAPSEC_CAPHE_CITY,
    MAPSEC_ROUTE9,
    MAPSEC_TORA_TOWN,
    MAPSEC_ROUTE12,
    MAPSEC_ANBEH_BEND,
    MAPSEC_POPIDORA_PIER,
    MAPSEC_ROUTE4,
    MAPSEC_HODOU_CITY,
    MAPSEC_FERRYBUILDING,
    MAPSEC_PERLACIA_CITY,
    MAPSEC_SHARPRISESPIRE,
    MAPSEC_ROUTE2,
    MAPSEC_CURENO_PORT,
    MAPSEC_ROUTE1,
    MAPSEC_ROUTE_A,
    MAPSEC_HALAI_ISLAND,
    MAPSEC_NAVAL_BASE,
    MAPSEC_ROUTE_B,
    MAPSEC_OROLAND,
    MAPSEC_OROLAND_COLISEUM,
    MAPSEC_ROUTE98,
    MAPSEC_CHASILLA,
    MAPSEC_ROUTE99,
    MAPSEC_WISHAAST_LAKE,
    MAPSEC_ARANTRAZ,
    MAPSEC_ROUTE_D,
    MAPSEC_ROUTE11,
    MAPSEC_FORT_YOBU,
    MAPSEC_PETAROSA_BOROUGH,
    MAPSEC_ROUTE13,
    MAPSEC_CRESALTA_VISTA,
    MAPSEC_ROUTE22,
    MAPSEC_HALERBA_CITY,
    MAPSEC_HALERBAWILDS,
    MAPSEC_TIRABUDIN_PLACE,
    MAPSEC_ROUTE7,
    MAPSEC_PINTILLONHOUSE,
    MAPSEC_ROUTE16,
    MAPSEC_ROUTE14,
    MAPSEC_IRISINA_TOWN,
    MAPSEC_ROUTE5,
    MAPSEC_PIOCA_BRIDGE,
    MAPSEC_ROBINWILLTUNNEL,
    MAPSEC_ESPULEE_OUTSKIRTS,
    MAPSEC_ROUTE100,
    MAPSEC_LEAVERRA_FOREST,
    MAPSEC_ROUTE_E,
    MAPSEC_ROUTE_C,
    MAPSEC_SHARPRISESTADIUM,
    MAPSEC_NONGYU_BRIDGE,
    MAPSEC_ZENZU_ISLAND,
    MAPSEC_ROUTE3,
    MAPSEC_TORGEOT_CLIMB,
    MAPSEC_SECRET_PATH,
    MAPSEC_PARC,
    MAPSEC_ROUTE18,
    MAPSEC_QIU_VILLAGE,
    MAPSEC_ROUTE20,
    MAPSEC_WAJABI_LAKE,
    MAPSEC_ORRE,
    MAPSEC_MORAGASTEPS,
    MAPSEC_DEYOUNGMUSEUM,
    MAPSEC_DUTCHWINDMILLS,
    MAPSEC_PALACEFINEARTS,
    MAPSEC_TRANSPYRAMID,
    MAPSEC_OROLANDFERRY,
    MAPSEC_PSFROUTE7E17FDD1,
    MAPSEC_PSFROUTE9F45DA86,
    MAPSEC_NONE,
};

#define METLOC_SPECIAL_EGG                  0xFD
#define METLOC_IN_GAME_TRADE                0xFE
#define METLOC_FATEFUL_ENCOUNTER            0xFF

#define RESIDO_MAPSEC_START (MAPSEC_TRAINER_HILL + 1)
#define RESIDO_MAPSEC_END (MAPSEC_ORRE)

#define KANTO_MAPSEC_START  10
#define KANTO_MAPSEC_END    10
#define KANTO_MAPSEC_COUNT (KANTO_MAPSEC_END - KANTO_MAPSEC_START + 1)

#endif //GUARD_REGIONMAPSEC_H
