#ifndef GUARD_CONSTANTS_REVEAL_H
#define GUARD_CONSTANTS_REVEAL_H

enum RevealWindows
{
    REVEAL_WINDOW_ANIMATION,
    REVEAL_WINDOW_HEADER,
    REVEAL_WINDOW_QUOTE,
    REVEAL_WINDOW_USERNAME,
    REVEAL_WINDOW_TITLE,
    REVEAL_WINDOW_BIO,
    REVEAL_WINDOW_FOOTER,
    REVEAL_WINDOW_COUNT,
};

enum RevealBackgrounds
{
    BG0_REVEAL,
    BG1_REVEAL_GLASS,
    BG_REVEAL_COUNT,
};

#define PAL_REVEAL_UI_SPRITES 123
#define REVEAL_SPRITETAG 2512

enum RevealFontColors
{
    REVEAL_FONT_COLOR_BLACK,
    REVEAL_FONT_COLOR_WHITE,
    REVEAL_FONT_COLOR_HELP,
};

enum RevealPaletteColors
{
    REVEAL_PALETTE_TRANSPERANT,
    REVEAL_PALETTE_WHITE,
    REVEAL_PALETTE_BLACK,
    REVEAL_PALETTE_BLUE,
    REVEAL_PALETTE_LIGHT_GRAY,
    REVEAL_PALETTE_GRAY,
    REVEAL_PALETTE_DARK_GRAY,
    REVEAL_PALETTE_CHARACTER,
};

#define FONT_REVEAL FONT_NORMAL

enum RevealIds
{
    REVEAL_NONE,
    REVEAL_ALICIA,
    REVEAL_CHARLOTTE,
    REVEAL_OLIVER,
    REVEAL_BELEN,
    REVEAL_BAIYA,
    REVEAL_SHINZO,
    REVEAL_EMRYS,
    REVEAL_RAMESH,
    REVEAL_LUCREZIA,
    REVEAL_PUA,
    REVEAL_ADAORA,
    REVEAL_NERIENE,
    REVEAL_KEI_YING,
    REVEAL_DIMU,
    REVEAL_TALA,
    REVEAL_BD,
    REVEAL_AMI,
    REVEAL_VIGRIM,
    REVEAL_FRANK,
    REVEAL_DOYLE,
    REVEAL_IMELDA,
    REVEAL_MAGNUS,
    REVEAL_ELEANOR,
    REVEAL_COUNT,
};

#define VRAM_ANIMATION_START 1

#define REVEAL_FRAME_COUNT 3

#define REVEAL_FRAME_ANIMATION_0 0
#define REVEAL_FRAME_ANIMATION_1 (REVEAL_FRAME_ANIMATION_0 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_2 (REVEAL_FRAME_ANIMATION_1 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_3 (REVEAL_FRAME_ANIMATION_2 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_4 (REVEAL_FRAME_ANIMATION_3 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_5 (REVEAL_FRAME_ANIMATION_4 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_6 (REVEAL_FRAME_ANIMATION_5 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_7 (REVEAL_FRAME_ANIMATION_6 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_8 (REVEAL_FRAME_ANIMATION_7 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_9 (REVEAL_FRAME_ANIMATION_8 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_10 (REVEAL_FRAME_ANIMATION_9 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_11 (REVEAL_FRAME_ANIMATION_10 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_12 (REVEAL_FRAME_ANIMATION_11 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_13 (REVEAL_FRAME_ANIMATION_12 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_14 (REVEAL_FRAME_ANIMATION_13 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_15 (REVEAL_FRAME_ANIMATION_14 + REVEAL_FRAME_COUNT)
#define REVEAL_FRAME_ANIMATION_END (REVEAL_FRAME_ANIMATION_15 + 1)

#define REVEAL_FRAME_SLIDE_END (REVEAL_FRAME_ANIMATION_13 + 1)

#define REVEAL_FRAME_ANIMATION_HEADER_FOOTER REVEAL_FRAME_ANIMATION_7
#define REVEAL_FRAME_ANIMATION_USERNAME      REVEAL_FRAME_ANIMATION_11
#define REVEAL_FRAME_ANIMATION_FLAVOR        REVEAL_FRAME_ANIMATION_13

#define REVEAL_PALETTE_SPRITE_FALLBACK 7
#define REVEAL_PALETTE_INTERFACE_ID   14
#define REVEAL_PALETTE_INTERFACE_SLOT BG_PLTT_ID(REVEAL_PALETTE_INTERFACE_ID)
#define REVEAL_PALETTE_ACCENT_COLOR_ADDRESS REVEAL_PALETTE_INTERFACE_SLOT + 7

enum RevealTrainerSpriteIds
{
    REVEAL_TRAINER_OW,
    REVEAL_TRAINER_SPRITE_TRAINER,
    REVEAL_TRAINER_SPRITE_OUTLINE_0,
    REVEAL_TRAINER_SPRITE_OUTLINE_1,
    REVEAL_TRAINER_SPRITE_OUTLINE_2,
    REVEAL_TRAINER_SPRITE_OUTLINE_3,
    REVEAL_TRAINER_END
};

#endif // GUARD_CONSTANTS_REVEAL_H
