#ifndef GUARD_SILICON_DAYCARE_CONSTANTS_H
#define GUARD_SILICON_DAYCARE_CONSTANTS_H

enum SiliconStarters
{
    SILICON_STARTER_SCYTHER,
    SILICON_STARTER_CHARCADET,
    SILICON_STARTER_PETILIL,
    SILICON_STARTER_FLAAFFY,
    SILICON_STARTER_MAREANIE,
    SILICON_STARTER_ARON,
    SILICON_STARTER_SWINUB,
    SILICON_STARTER_HATTREM,
    SILICON_STARTER_PANCHAM,
    SILICON_STARTER_COUNT,
};

#endif //GUARD_SILICON_DAYCARE_CONSTANTS_H
