#ifndef GUARD_SILICON_BATTLE_FRONTIER_CONSTANTS_H
#define GUARD_SILICON_BATTLE_FRONTIER_CONSTANTS_H

enum SiliconFrontierChallengeType
{
    SILICON_FRONTIER_CHALLENGE_TYPE_SINGLE,
    SILICON_FRONTIER_CHALLENGE_TYPE_DOUBLE,
    SILICON_FRONTIER_CHALLENGE_TYPE_MULTI,
    SILICON_FRONTIER_CHALLENGE_TYPE_COUNT,
};

enum SiliconFrontierFacility
{
    SILICON_FACILITY_TOWER,
    SILICON_FACILITY_ARCADE,
    SILICON_FACILITY_SPARRING,
    SILICON_FACILITY_FACTORY,
    SILICON_FACILITY_COUNT,
};

enum SiliconFrontierPartner
{
    SILICON_FRONTIER_PARTNER_NONE,
    SILICON_FRONTIER_PARTNER_PUA,
    SILICON_FRONTIER_PARTNER_CHARLOTTE,
    SILICON_FRONTIER_PARTNER_AMI_ARGENTO,
    SILICON_FRONTIER_PARTNER_TALA,
    SILICON_FRONTIER_PARTNER_DIMU,
    SILICON_FRONTIER_PARTNER_ADAORA,
    SILICON_FRONTIER_PARTNER_EMRYS,
    SILICON_FRONTIER_PARTNER_MAGNUS,
    SILICON_FRONTIER_PARTNER_BD,
    SILICON_FRONTIER_PARTNER_BAIYA,
    SILICON_FRONTIER_PARTNER_NERIENE,
    SILICON_FRONTIER_PARTNER_FRANK,
    SILICON_FRONTIER_PARTNER_SHINZO,
    SILICON_FRONTIER_PARTNER_KEI_YING,
    SILICON_FRONTIER_PARTNER_BELEN,
    SILICON_FRONTIER_PARTNER_ELEANOR,
    SILICON_FRONTIER_PARTNER_COUNT,
};

#define RESTRICTED_SPARRING_MAX_HEALS_COUNT 2

#endif // GUARD_SILICON_BATTLE_FRONTIER_CONSTANTS_H
