#ifndef GUARD_SILICON_DAYCARE_CONSTANTS_H
#define GUARD_SILICON_DAYCARE_CONSTANTS_H

#define SILICON_DAYCARE_PER_IV_COST 20
#define SILICON_DAYCARE_PER_EGG_COST 5
#define SILICON_DAYCARE_NO_PERK_MULTIPLIER 100

enum DaycareCostCodes
{
    SILICON_DAYCARE_NO_DISCOUNT_YES_STATS,
    SILICON_DAYCARE_NO_DISCOUNT_NO_STATS,
    SILICON_DAYCARE_YES_DISCOUNT_YES_STATS,
    SILICON_DAYCARE_YES_DISCOUNT_NO_STATS,
    SILICON_DAYCARE_COST_CODE_COUNT,
};

#endif //GUARD_SILICON_DAYCARE_CONSTANTS_H
