#ifndef GUARD_CONSTANTS_STORYJUMP_H
#define GUARD_CONSTANTS_STORYJUMP_H

#define JUMP_DEBUG                             0
#define JUMP_CUTSCENE_SKIP                     1

#define JUMPPLAYER_NONE                                0
#define JUMPPLAYER_PROLOGUE_INTRO                      1
#define JUMPPLAYER_PROLOGUE_CHAMPION                   2
#define JUMPPLAYER_PROLOGUE_ANNOUNCEMENT               3
#define JUMPPLAYER_BEGINADVENTURE                      4
#define JUMPPLAYER_STARTERCHOICE                       5
#define JUMPPLAYER_IMPROBABLYBETTERTHANYOU             6
#define JUMPPLAYER_SWAGBAG                             7
#define JUMPPLAYER_READYSETI                           8
#define JUMPPLAYER_CATCHTUTORIAL                       9
#define JUMPPLAYER_ENTERBELEN                        10
#define JUMPPLAYER_ENTERSHINZO                          11
#define JUMPPLAYER_ENTEREMRYS                        12
#define JUMPPLAYER_NEWASSHOLEAPPEARS                   13
#define JUMPPLAYER_OLDASSHOLEAPPEARS                   14
#define JUMPPLAYER_GROUPOFASSHOLESAPPEARS              15
#define JUMPPLAYER_FLYINGBLIND_NORTH                   16
#define JUMPPLAYER_FLYINGBLIND_SOUTH                   17
#define JUMPPLAYER_WOWYOURESTRONG_PERLACIA_CITY                 18
#define JUMPPLAYER_WOWYOURESTRONG_MERMEREZA_CITY              19
#define JUMPPLAYER_WOWYOURESTRONG_TORA_TOWN            20
#define JUMPPLAYER_THEGANGSALLHERE                     21
#define JUMPPLAYER_ALWAYSWATCHINGWAZOKWSKI             22
#define JUMPPLAYER_ENTERADAORA                         23
#define JUMPPLAYER_HOWDOWEGETHOME                      24
#define JUMPPLAYER_AAANDWEREBACK                       25
#define JUMPPLAYER_ASSHOLESHOME                        26
#define JUMPPLAYER_HOUSINGPROTEST                      27
#define JUMPPLAYER_SWAGBAG2                            28
#define JUMPPLAYER_ENTERKAUNA                          29
#define JUMPPLAYER_SORRYABOUTMYFRIENDS                 30
#define JUMPPLAYER_THESTORYSOFAR_A                     31
#define JUMPPLAYER_THESTORYSOFAR_B                     32
#define JUMPPLAYER_THESTORYSOFAR_C                     33
#define JUMPPLAYER_THESTORYSOFAR_D                     34
#define JUMPPLAYER_THESTORYSOFAR_E                     35
#define JUMPPLAYER_THESTORYSOFAR_F                     36
#define JUMPPLAYER_THESTORYSOFAR_ALL                   37
#define JUMPPLAYER_YOUNGPADAWAN                        38
#define JUMPPLAYER_WAITYOUWENTWHERE                    39
#define JUMPPLAYER_ENTERNERIENE                          40
#define JUMPPLAYER_FRIENDSFORDINNER                     41
#define JUMPPLAYER_KEIYINGSRAISONDETRE                    42
#define JUMPPLAYER_BEACHBATTLE                         43
#define JUMPPLAYER_ENTERDIMU                        44
#define JUMPPLAYER_ANEWSTRIKE                          45
#define JUMPPLAYER_ANDWEMARCHON                        46
#define JUMPPLAYER_ENTERBD                          47
#define JUMPPLAYER_BATTLE8                             48
#define JUMPPLAYER_ENTERAMIARGENTO                          49
#define JUMPPLAYER_THESTRIKESTRIKESBACK                50
#define JUMPPLAYER_VSGARBODOR                          51
#define JUMPPLAYER_OFFYOUGO_PHONE                      52
#define JUMPPLAYER_OFFYOUGO_BRIDGE                     53
#define JUMPPLAYER_IGUESSWESHOULDBENICENOW             54
#define JUMPPLAYER_ENTERTHEMASTER                      55
#define JUMPPLAYER_HAVEYOUSEENTHENEWS                  56
#define JUMPPLAYER_WELCOMETOTHEWARROOM                 57
#define JUMPPLAYER_SURVIVALCHANCE333                   58
#define JUMPPLAYER_WHYAREYOUHELPINGTHEM                59
#define JUMPPLAYER_WHYAREYOUHELPINGTHEMSLEEP           60
#define JUMPPLAYER_HERESHOWTHISISGOINGTOGO             61
#define JUMPPLAYER_WHYDIDNTYOURATMEOUT                 62
#define JUMPPLAYER_GROUPSTAGES                         63
#define JUMPPLAYER_FINALS                              64
#define JUMPPLAYER_WAITHEDIDWHAT                       65
#define JUMPPLAYER_WELCOMETOTHEHALLOFFAME              66
#define JUMPPLAYER_BEINGCHAMPIONISHARD                 67
#define JUMPPLAYER_LETSGRABLUNCH                       68
#define JUMPPLAYER_RESTOREHODOU_CITY                    69
#define JUMPPLAYER_RESTOREZENZU_ISLAND               70
#define JUMPPLAYER_RESTOREESPULEE_OUTSKIRTS                        71
#define JUMPPLAYER_RESTORETIRABUDIN_PLACE                72
#define JUMPPLAYER_YOUREALIZEWEREEVILRIGHT             73
#define JUMPPLAYER_YOUREALIZETHEYREEVILRIGHT_PHONE     74
#define JUMPPLAYER_YOUREALIZETHEYREEVILRIGHT_ISLAND    75
#define JUMPPLAYER_CONGRATSYOUREANASSHOLE              76
#define JUMPPLAYER_YOUHAVEYOURORDERS                   77
#define JUMPPLAYER_HOWDISAPPOINTING_RAID               78
#define JUMPPLAYER_HOWDISAPPOINTING_ARREST             79
#define JUMPPLAYER_LETSBURNTHISMOTHERDOWN              80
#define JUMPPLAYER_MANHUNT_NEWS                        81
#define JUMPPLAYER_MANHUNT_BUSINESS                    82
#define JUMPPLAYER_MANHUNT_BALL                        83
#define JUMPPLAYER_MANHUNT_ROUTE                       84
#define JUMPPLAYER_MANHUNT_ALCMENE                     85
#define JUMPPLAYER_EXHIBITIONBATTLE                    86
#define JUMPPLAYER_MAYBEIFUCKEDUP                      87
#define JUMPPLAYER_OKAYLETSFIXIT                       88
#define JUMPPLAYER_LETSGETTHEBANDBACKTOGETHER_BEFORE   89
#define JUMPPLAYER_LETSGETTHEBANDBACKTOGETHER_AFTER    90
#define JUMPPLAYER_MASKOFF_H 91
#define JUMPPLAYER_MASKOFF_F 92
#define JUMPPLAYER_MASKOFF_I 93
#define JUMPPLAYER_MASKOFF_D 94
#define JUMPPLAYER_MASKOFF_G 95
#define JUMPPLAYER_MASKOFF_ALCMENE                     96
#define JUMPPLAYER_LETSFIXTHIS                         97
#define JUMPPLAYER_LOCKEDOUT                           98
#define JUMPPLAYER_WAREHOUSERAVE                       99
#define JUMPPLAYER_SPEECHSPEECHSPEECH                  100
#define JUMPPLAYER_PERSUASIVEPASSENGER                 101
#define JUMPPLAYER_BREAKTHEINTERNET                    102
#define JUMPPLAYER_WAREHOUSEWARFARE                    103
#define JUMPPLAYER_ONEDOWN                             104
#define JUMPPLAYER_EARTHQUAKE_INSIDE                   105
#define JUMPPLAYER_EARTHQUAKE_OUTSIDE                  106
#define JUMPPLAYER_THISISNTRANDOM_DISCOVER                      107
#define JUMPPLAYER_THISISNTRANDOM_MON1                      108
#define JUMPPLAYER_THISISNTRANDOM_MON2                      109
#define JUMPPLAYER_WAITEVENTHEN                        110
#define JUMPPLAYER_LETSFINISHTHIS                      111
#define JUMPPLAYER_IMIN_BREAKIN                                112
#define JUMPPLAYER_IMIN_POSTWARP                                113
#define JUMPPLAYER_IMIN_POSTRIVAL                      114
#define JUMPPLAYER_YOUCANTSTOPME_LASTPLEA                       115
#define JUMPPLAYER_YOUCANTSTOPME_POSTBATTLE 116
#define JUMPPLAYER_WECANSTOPYOUACTUALLY                117
#define JUMPPLAYER_EPILOGUE                          118

#endif  //GUARD_CONSTANTS_STORYJUMP_H
