#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(MOVE_ABSORB) \
    F(MOVE_ACID) \
    F(MOVE_ACID_ARMOR) \
    F(MOVE_ACID_SPRAY) \
    F(MOVE_ACROBATICS) \
    F(MOVE_ACUPRESSURE) \
    F(MOVE_AERIAL_ACE) \
    F(MOVE_AFTER_YOU) \
    F(MOVE_AGILITY) \
    F(MOVE_AIR_CUTTER) \
    F(MOVE_AIR_SLASH) \
    F(MOVE_ALLURING_VOICE) \
    F(MOVE_ALLY_SWITCH) \
    F(MOVE_AMNESIA) \
    F(MOVE_ANCIENT_POWER) \
    F(MOVE_AQUA_CUTTER) \
    F(MOVE_AQUA_JET) \
    F(MOVE_AQUA_RING) \
    F(MOVE_AQUA_TAIL) \
    F(MOVE_AROMATIC_MIST) \
    F(MOVE_ASSURANCE) \
    F(MOVE_ASTONISH) \
    F(MOVE_ATTRACT) \
    F(MOVE_AURA_SPHERE) \
    F(MOVE_AURORA_BEAM) \
    F(MOVE_AURORA_VEIL) \
    F(MOVE_AVALANCHE) \
    F(MOVE_BABY_DOLL_EYES) \
    F(MOVE_BATON_PASS) \
    F(MOVE_BEAT_UP) \
    F(MOVE_BELCH) \
    F(MOVE_BELLY_DRUM) \
    F(MOVE_BIND) \
    F(MOVE_BITE) \
    F(MOVE_BLIZZARD) \
    F(MOVE_BLOCK) \
    F(MOVE_BODY_PRESS) \
    F(MOVE_BODY_SLAM) \
    F(MOVE_BOOMBURST) \
    F(MOVE_BOUNCE) \
    F(MOVE_BRAVE_BIRD) \
    F(MOVE_BREAKING_SWIPE) \
    F(MOVE_BRICK_BREAK) \
    F(MOVE_BRINE) \
    F(MOVE_BRUTAL_SWING) \
    F(MOVE_BUG_BITE) \
    F(MOVE_BUG_BUZZ) \
    F(MOVE_BULK_UP) \
    F(MOVE_BULLDOZE) \
    F(MOVE_BULLET_PUNCH) \
    F(MOVE_BULLET_SEED) \
    F(MOVE_BURNING_JEALOUSY) \
    F(MOVE_CALM_MIND) \
    F(MOVE_CHARGE) \
    F(MOVE_CHARGE_BEAM) \
    F(MOVE_CHARM) \
    F(MOVE_CHILLING_WATER) \
    F(MOVE_CIRCLE_THROW) \
    F(MOVE_CLEAR_SMOG) \
    F(MOVE_CLOSE_COMBAT) \
    F(MOVE_COACHING) \
    F(MOVE_CONFIDE) \
    F(MOVE_CONFUSE_RAY) \
    F(MOVE_CONFUSION) \
    F(MOVE_COPYCAT) \
    F(MOVE_COSMIC_POWER) \
    F(MOVE_COTTON_GUARD) \
    F(MOVE_COUNTER) \
    F(MOVE_COVET) \
    F(MOVE_CRABHAMMER) \
    F(MOVE_CROSS_CHOP) \
    F(MOVE_CROSS_POISON) \
    F(MOVE_CRUNCH) \
    F(MOVE_CURSE) \
    F(MOVE_DARK_PULSE) \
    F(MOVE_DARKEST_LARIAT) \
    F(MOVE_DAZZLING_GLEAM) \
    F(MOVE_DEFENSE_CURL) \
    F(MOVE_DEFOG) \
    F(MOVE_DESTINY_BOND) \
    F(MOVE_DETECT) \
    F(MOVE_DIG) \
    F(MOVE_DISABLE) \
    F(MOVE_DISARMING_VOICE) \
    F(MOVE_DISCHARGE) \
    F(MOVE_DIVE) \
    F(MOVE_DOUBLE_EDGE) \
    F(MOVE_DOUBLE_HIT) \
    F(MOVE_DOUBLE_KICK) \
    F(MOVE_DOUBLE_TEAM) \
    F(MOVE_DRACO_METEOR) \
    F(MOVE_DRAGON_BREATH) \
    F(MOVE_DRAGON_CHEER) \
    F(MOVE_DRAGON_CLAW) \
    F(MOVE_DRAGON_DANCE) \
    F(MOVE_DRAGON_PULSE) \
    F(MOVE_DRAGON_RUSH) \
    F(MOVE_DRAGON_TAIL) \
    F(MOVE_DRAIN_PUNCH) \
    F(MOVE_DRAINING_KISS) \
    F(MOVE_DREAM_EATER) \
    F(MOVE_DRILL_PECK) \
    F(MOVE_DRILL_RUN) \
    F(MOVE_DUAL_WINGBEAT) \
    F(MOVE_DYNAMIC_PUNCH) \
    F(MOVE_EARTH_POWER) \
    F(MOVE_EARTHQUAKE) \
    F(MOVE_ECHOED_VOICE) \
    F(MOVE_EERIE_IMPULSE) \
    F(MOVE_ELECTRIC_TERRAIN) \
    F(MOVE_ELECTRO_BALL) \
    F(MOVE_ELECTROWEB) \
    F(MOVE_ENCORE) \
    F(MOVE_ENDEAVOR) \
    F(MOVE_ENDURE) \
    F(MOVE_ENERGY_BALL) \
    F(MOVE_ENTRAINMENT) \
    F(MOVE_EXPANDING_FORCE) \
    F(MOVE_EXPLOSION) \
    F(MOVE_EXTRASENSORY) \
    F(MOVE_EXTREME_SPEED) \
    F(MOVE_FACADE) \
    F(MOVE_FAINT_ATTACK) \
    F(MOVE_FAKE_OUT) \
    F(MOVE_FAKE_TEARS) \
    F(MOVE_FALSE_SWIPE) \
    F(MOVE_FEATHER_DANCE) \
    F(MOVE_FEINT) \
    F(MOVE_FELL_STINGER) \
    F(MOVE_FINAL_GAMBIT) \
    F(MOVE_FIRE_BLAST) \
    F(MOVE_FIRE_FANG) \
    F(MOVE_FIRE_PUNCH) \
    F(MOVE_FIRE_SPIN) \
    F(MOVE_FIRST_IMPRESSION) \
    F(MOVE_FISSURE) \
    F(MOVE_FLAIL) \
    F(MOVE_FLAME_CHARGE) \
    F(MOVE_FLAMETHROWER) \
    F(MOVE_FLARE_BLITZ) \
    F(MOVE_FLATTER) \
    F(MOVE_FLING) \
    F(MOVE_FLIP_TURN) \
    F(MOVE_FLY) \
    F(MOVE_FOCUS_BLAST) \
    F(MOVE_FOCUS_ENERGY) \
    F(MOVE_FOCUS_PUNCH) \
    F(MOVE_FOLLOW_ME) \
    F(MOVE_FOUL_PLAY) \
    F(MOVE_FREEZE_DRY) \
    F(MOVE_FRENZY_PLANT) \
    F(MOVE_FURY_CUTTER) \
    F(MOVE_FUTURE_SIGHT) \
    F(MOVE_GASTRO_ACID) \
    F(MOVE_GIGA_DRAIN) \
    F(MOVE_GIGA_IMPACT) \
    F(MOVE_GLARE) \
    F(MOVE_GRASS_KNOT) \
    F(MOVE_GRASS_PLEDGE) \
    F(MOVE_GRASSY_GLIDE) \
    F(MOVE_GRASSY_TERRAIN) \
    F(MOVE_GRAVITY) \
    F(MOVE_GROWTH) \
    F(MOVE_GUARD_SPLIT) \
    F(MOVE_GUARD_SWAP) \
    F(MOVE_GUNK_SHOT) \
    F(MOVE_GUST) \
    F(MOVE_GYRO_BALL) \
    F(MOVE_HAMMER_ARM) \
    F(MOVE_HARD_PRESS) \
    F(MOVE_HARDEN) \
    F(MOVE_HAZE) \
    F(MOVE_HEAD_SMASH) \
    F(MOVE_HEADBUTT) \
    F(MOVE_HEAL_BELL) \
    F(MOVE_HEAL_PULSE) \
    F(MOVE_HEALING_WISH) \
    F(MOVE_HEAT_CRASH) \
    F(MOVE_HEAT_WAVE) \
    F(MOVE_HEAVY_SLAM) \
    F(MOVE_HELPING_HAND) \
    F(MOVE_HEX) \
    F(MOVE_HIGH_HORSEPOWER) \
    F(MOVE_HIGH_JUMP_KICK) \
    F(MOVE_HORN_DRILL) \
    F(MOVE_HOWL) \
    F(MOVE_HURRICANE) \
    F(MOVE_HYDRO_CANNON) \
    F(MOVE_HYDRO_PUMP) \
    F(MOVE_HYPER_BEAM) \
    F(MOVE_HYPER_VOICE) \
    F(MOVE_HYPNOSIS) \
    F(MOVE_ICE_BEAM) \
    F(MOVE_ICE_FANG) \
    F(MOVE_ICE_PUNCH) \
    F(MOVE_ICE_SHARD) \
    F(MOVE_ICE_SPINNER) \
    F(MOVE_ICICLE_CRASH) \
    F(MOVE_ICICLE_SPEAR) \
    F(MOVE_ICY_WIND) \
    F(MOVE_IMPRISON) \
    F(MOVE_INFESTATION) \
    F(MOVE_INGRAIN) \
    F(MOVE_IRON_DEFENSE) \
    F(MOVE_IRON_HEAD) \
    F(MOVE_IRON_TAIL) \
    F(MOVE_KNOCK_OFF) \
    F(MOVE_LASH_OUT) \
    F(MOVE_LAST_RESORT) \
    F(MOVE_LEAF_BLADE) \
    F(MOVE_LEAF_STORM) \
    F(MOVE_LEECH_LIFE) \
    F(MOVE_LEECH_SEED) \
    F(MOVE_LEER) \
    F(MOVE_LICK) \
    F(MOVE_LIFE_DEW) \
    F(MOVE_LIGHT_SCREEN) \
    F(MOVE_LIQUIDATION) \
    F(MOVE_LOW_KICK) \
    F(MOVE_LOW_SWEEP) \
    F(MOVE_LUNGE) \
    F(MOVE_MACH_PUNCH) \
    F(MOVE_MAGIC_ROOM) \
    F(MOVE_MAGICAL_LEAF) \
    F(MOVE_MAGNET_RISE) \
    F(MOVE_MEAN_LOOK) \
    F(MOVE_MEGA_DRAIN) \
    F(MOVE_MEGA_KICK) \
    F(MOVE_MEGA_PUNCH) \
    F(MOVE_MEGAHORN) \
    F(MOVE_MEMENTO) \
    F(MOVE_METAL_CLAW) \
    F(MOVE_METAL_SOUND) \
    F(MOVE_METEOR_BEAM) \
    F(MOVE_METRONOME) \
    F(MOVE_MIMIC) \
    F(MOVE_MIRROR_COAT) \
    F(MOVE_MIST) \
    F(MOVE_MISTY_EXPLOSION) \
    F(MOVE_MISTY_TERRAIN) \
    F(MOVE_MOONBLAST) \
    F(MOVE_MORNING_SUN) \
    F(MOVE_MUD_SHOT) \
    F(MOVE_MUD_SLAP) \
    F(MOVE_MUDDY_WATER) \
    F(MOVE_MYSTICAL_FIRE) \
    F(MOVE_NASTY_PLOT) \
    F(MOVE_NIGHT_SHADE) \
    F(MOVE_NIGHT_SLASH) \
    F(MOVE_NUZZLE) \
    F(MOVE_OCTAZOOKA) \
    F(MOVE_OUTRAGE) \
    F(MOVE_OVERHEAT) \
    F(MOVE_PAIN_SPLIT) \
    F(MOVE_PARTING_SHOT) \
    F(MOVE_PAY_DAY) \
    F(MOVE_PAYBACK) \
    F(MOVE_PECK) \
    F(MOVE_PERISH_SONG) \
    F(MOVE_PETAL_BLIZZARD) \
    F(MOVE_PHANTOM_FORCE) \
    F(MOVE_PIN_MISSILE) \
    F(MOVE_PLAY_ROUGH) \
    F(MOVE_PLUCK) \
    F(MOVE_POISON_FANG) \
    F(MOVE_POISON_JAB) \
    F(MOVE_POISON_POWDER) \
    F(MOVE_POISON_TAIL) \
    F(MOVE_POLLEN_PUFF) \
    F(MOVE_POLTERGEIST) \
    F(MOVE_POUNCE) \
    F(MOVE_POWER_GEM) \
    F(MOVE_POWER_SPLIT) \
    F(MOVE_POWER_SWAP) \
    F(MOVE_POWER_TRIP) \
    F(MOVE_POWER_UP_PUNCH) \
    F(MOVE_POWER_WHIP) \
    F(MOVE_PRESENT) \
    F(MOVE_PROTECT) \
    F(MOVE_PSYBEAM) \
    F(MOVE_PSYCH_UP) \
    F(MOVE_PSYCHIC) \
    F(MOVE_PSYCHIC_FANGS) \
    F(MOVE_PSYCHIC_NOISE) \
    F(MOVE_PSYCHIC_TERRAIN) \
    F(MOVE_PSYCHO_CUT) \
    F(MOVE_PSYSHIELD_BASH) \
    F(MOVE_PSYSHOCK) \
    F(MOVE_QUASH) \
    F(MOVE_QUICK_ATTACK) \
    F(MOVE_QUICK_GUARD) \
    F(MOVE_QUIVER_DANCE) \
    F(MOVE_RAIN_DANCE) \
    F(MOVE_RAPID_SPIN) \
    F(MOVE_RAZOR_SHELL) \
    F(MOVE_RECOVER) \
    F(MOVE_RECYCLE) \
    F(MOVE_REFLECT) \
    F(MOVE_REFLECT_TYPE) \
    F(MOVE_REST) \
    F(MOVE_RETALIATE) \
    F(MOVE_REVERSAL) \
    F(MOVE_ROAR) \
    F(MOVE_ROCK_BLAST) \
    F(MOVE_ROCK_POLISH) \
    F(MOVE_ROCK_SLIDE) \
    F(MOVE_ROCK_SMASH) \
    F(MOVE_ROCK_THROW) \
    F(MOVE_ROCK_TOMB) \
    F(MOVE_ROLE_PLAY) \
    F(MOVE_ROLLOUT) \
    F(MOVE_ROOST) \
    F(MOVE_ROUND) \
    F(MOVE_SAFEGUARD) \
    F(MOVE_SAND_ATTACK) \
    F(MOVE_SAND_TOMB) \
    F(MOVE_SANDSTORM) \
    F(MOVE_SCALD) \
    F(MOVE_SCALE_SHOT) \
    F(MOVE_SCARY_FACE) \
    F(MOVE_SCORCHING_SANDS) \
    F(MOVE_SCREECH) \
    F(MOVE_SEED_BOMB) \
    F(MOVE_SEISMIC_TOSS) \
    F(MOVE_SELF_DESTRUCT) \
    F(MOVE_SHADOW_BALL) \
    F(MOVE_SHADOW_CLAW) \
    F(MOVE_SHADOW_SNEAK) \
    F(MOVE_SHELL_SMASH) \
    F(MOVE_SHOCK_WAVE) \
    F(MOVE_SIMPLE_BEAM) \
    F(MOVE_SKILL_SWAP) \
    F(MOVE_SKITTER_SMACK) \
    F(MOVE_SKY_ATTACK) \
    F(MOVE_SLAM) \
    F(MOVE_SLASH) \
    F(MOVE_SLEEP_TALK) \
    F(MOVE_SLUDGE) \
    F(MOVE_SLUDGE_BOMB) \
    F(MOVE_SLUDGE_WAVE) \
    F(MOVE_SMACK_DOWN) \
    F(MOVE_SMART_STRIKE) \
    F(MOVE_SMOG) \
    F(MOVE_SMOKESCREEN) \
    F(MOVE_SNARL) \
    F(MOVE_SNORE) \
    F(MOVE_SNOWSCAPE) \
    F(MOVE_SOAK) \
    F(MOVE_SOLAR_BEAM) \
    F(MOVE_SOLAR_BLADE) \
    F(MOVE_SPARKLING_ARIA) \
    F(MOVE_SPEED_SWAP) \
    F(MOVE_SPIKES) \
    F(MOVE_SPIT_UP) \
    F(MOVE_SPITE) \
    F(MOVE_SPLASH) \
    F(MOVE_STEALTH_ROCK) \
    F(MOVE_STEEL_BEAM) \
    F(MOVE_STEEL_WING) \
    F(MOVE_STICKY_WEB) \
    F(MOVE_STOCKPILE) \
    F(MOVE_STOMP) \
    F(MOVE_STOMPING_TANTRUM) \
    F(MOVE_STONE_EDGE) \
    F(MOVE_STORED_POWER) \
    F(MOVE_STRENGTH_SAP) \
    F(MOVE_STRUGGLE_BUG) \
    F(MOVE_STUFF_CHEEKS) \
    F(MOVE_STUN_SPORE) \
    F(MOVE_SUBSTITUTE) \
    F(MOVE_SUCKER_PUNCH) \
    F(MOVE_SUNNY_DAY) \
    F(MOVE_SUPER_FANG) \
    F(MOVE_SUPERCELL_SLAM) \
    F(MOVE_SUPERPOWER) \
    F(MOVE_SUPERSONIC) \
    F(MOVE_SURF) \
    F(MOVE_SWAGGER) \
    F(MOVE_SWALLOW) \
    F(MOVE_SWEET_KISS) \
    F(MOVE_SWEET_SCENT) \
    F(MOVE_SWIFT) \
    F(MOVE_SWITCHEROO) \
    F(MOVE_SWORDS_DANCE) \
    F(MOVE_SYNTHESIS) \
    F(MOVE_TAIL_SLAP) \
    F(MOVE_TAIL_WHIP) \
    F(MOVE_TAILWIND) \
    F(MOVE_TAKE_DOWN) \
    F(MOVE_TAUNT) \
    F(MOVE_TEARFUL_LOOK) \
    F(MOVE_TEETER_DANCE) \
    F(MOVE_TEMPER_FLARE) \
    F(MOVE_THIEF) \
    F(MOVE_THRASH) \
    F(MOVE_THROAT_CHOP) \
    F(MOVE_THUNDER) \
    F(MOVE_THUNDER_FANG) \
    F(MOVE_THUNDER_PUNCH) \
    F(MOVE_THUNDER_WAVE) \
    F(MOVE_THUNDERBOLT) \
    F(MOVE_TICKLE) \
    F(MOVE_TORMENT) \
    F(MOVE_TOXIC) \
    F(MOVE_TOXIC_SPIKES) \
    F(MOVE_TRAILBLAZE) \
    F(MOVE_TRI_ATTACK) \
    F(MOVE_TRICK) \
    F(MOVE_TRICK_ROOM) \
    F(MOVE_TRIPLE_AXEL) \
    F(MOVE_TWISTER) \
    F(MOVE_U_TURN) \
    F(MOVE_UPPER_HAND) \
    F(MOVE_UPROAR) \
    F(MOVE_VACUUM_WAVE) \
    F(MOVE_VENOSHOCK) \
    F(MOVE_VOLT_SWITCH) \
    F(MOVE_WAKE_UP_SLAP) \
    F(MOVE_WATER_PLEDGE) \
    F(MOVE_WATER_PULSE) \
    F(MOVE_WATER_SPOUT) \
    F(MOVE_WATERFALL) \
    F(MOVE_WEATHER_BALL) \
    F(MOVE_WHIRLPOOL) \
    F(MOVE_WHIRLWIND) \
    F(MOVE_WIDE_GUARD) \
    F(MOVE_WILD_CHARGE) \
    F(MOVE_WILL_O_WISP) \
    F(MOVE_WING_ATTACK) \
    F(MOVE_WISH) \
    F(MOVE_WONDER_ROOM) \
    F(MOVE_WORK_UP) \
    F(MOVE_WORRY_SEED) \
    F(MOVE_X_SCISSOR) \
    F(MOVE_YAWN) \
    F(MOVE_ZEN_HEADBUTT)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

// Start pokedexUpdate
#define ITEM_TM_ABSORB ITEM_TM01
#define ITEM_TM_ACID ITEM_TM02
#define ITEM_TM_ACID_ARMOR ITEM_TM03
#define ITEM_TM_ACID_SPRAY ITEM_TM04
#define ITEM_TM_ACROBATICS ITEM_TM05
#define ITEM_TM_ACUPRESSURE ITEM_TM06
#define ITEM_TM_AERIAL_ACE ITEM_TM07
#define ITEM_TM_AFTER_YOU ITEM_TM08
#define ITEM_TM_AGILITY ITEM_TM09
#define ITEM_TM_AIR_CUTTER ITEM_TM10
#define ITEM_TM_AIR_SLASH ITEM_TM11
#define ITEM_TM_ALLURING_VOICE ITEM_TM12
#define ITEM_TM_ALLY_SWITCH ITEM_TM13
#define ITEM_TM_AMNESIA ITEM_TM14
#define ITEM_TM_ANCIENT_POWER ITEM_TM15
#define ITEM_TM_AQUA_CUTTER ITEM_TM16
#define ITEM_TM_AQUA_JET ITEM_TM17
#define ITEM_TM_AQUA_RING ITEM_TM18
#define ITEM_TM_AQUA_TAIL ITEM_TM19
#define ITEM_TM_AROMATIC_MIST ITEM_TM20
#define ITEM_TM_ASSURANCE ITEM_TM21
#define ITEM_TM_ASTONISH ITEM_TM22
#define ITEM_TM_ATTRACT ITEM_TM23
#define ITEM_TM_AURA_SPHERE ITEM_TM24
#define ITEM_TM_AURORA_BEAM ITEM_TM25
#define ITEM_TM_AURORA_VEIL ITEM_TM26
#define ITEM_TM_AVALANCHE ITEM_TM27
#define ITEM_TM_BABY_DOLL_EYES ITEM_TM28
#define ITEM_TM_BATON_PASS ITEM_TM29
#define ITEM_TM_BEAT_UP ITEM_TM30
#define ITEM_TM_BELCH ITEM_TM31
#define ITEM_TM_BELLY_DRUM ITEM_TM32
#define ITEM_TM_BIND ITEM_TM33
#define ITEM_TM_BITE ITEM_TM34
#define ITEM_TM_BLIZZARD ITEM_TM35
#define ITEM_TM_BLOCK ITEM_TM36
#define ITEM_TM_BODY_PRESS ITEM_TM37
#define ITEM_TM_BODY_SLAM ITEM_TM38
#define ITEM_TM_BOOMBURST ITEM_TM39
#define ITEM_TM_BOUNCE ITEM_TM40
#define ITEM_TM_BRAVE_BIRD ITEM_TM41
#define ITEM_TM_BREAKING_SWIPE ITEM_TM42
#define ITEM_TM_BRICK_BREAK ITEM_TM43
#define ITEM_TM_BRINE ITEM_TM44
#define ITEM_TM_BRUTAL_SWING ITEM_TM45
#define ITEM_TM_BUG_BITE ITEM_TM46
#define ITEM_TM_BUG_BUZZ ITEM_TM47
#define ITEM_TM_BULK_UP ITEM_TM48
#define ITEM_TM_BULLDOZE ITEM_TM49
#define ITEM_TM_BULLET_PUNCH ITEM_TM50
#define ITEM_TM_BULLET_SEED ITEM_TM51
#define ITEM_TM_BURNING_JEALOUSY ITEM_TM52
#define ITEM_TM_CALM_MIND ITEM_TM53
#define ITEM_TM_CHARGE ITEM_TM54
#define ITEM_TM_CHARGE_BEAM ITEM_TM55
#define ITEM_TM_CHARM ITEM_TM56
#define ITEM_TM_CHILLING_WATER ITEM_TM57
#define ITEM_TM_CIRCLE_THROW ITEM_TM58
#define ITEM_TM_CLEAR_SMOG ITEM_TM59
#define ITEM_TM_CLOSE_COMBAT ITEM_TM60
#define ITEM_TM_COACHING ITEM_TM61
#define ITEM_TM_CONFIDE ITEM_TM62
#define ITEM_TM_CONFUSE_RAY ITEM_TM63
#define ITEM_TM_CONFUSION ITEM_TM64
#define ITEM_TM_COPYCAT ITEM_TM65
#define ITEM_TM_COSMIC_POWER ITEM_TM66
#define ITEM_TM_COTTON_GUARD ITEM_TM67
#define ITEM_TM_COUNTER ITEM_TM68
#define ITEM_TM_COVET ITEM_TM69
#define ITEM_TM_CRABHAMMER ITEM_TM70
#define ITEM_TM_CROSS_CHOP ITEM_TM71
#define ITEM_TM_CROSS_POISON ITEM_TM72
#define ITEM_TM_CRUNCH ITEM_TM73
#define ITEM_TM_CURSE ITEM_TM74
#define ITEM_TM_DARK_PULSE ITEM_TM75
#define ITEM_TM_DARKEST_LARIAT ITEM_TM76
#define ITEM_TM_DAZZLING_GLEAM ITEM_TM77
#define ITEM_TM_DEFENSE_CURL ITEM_TM78
#define ITEM_TM_DEFOG ITEM_TM79
#define ITEM_TM_DESTINY_BOND ITEM_TM80
#define ITEM_TM_DETECT ITEM_TM81
#define ITEM_TM_DIG ITEM_TM82
#define ITEM_TM_DISABLE ITEM_TM83
#define ITEM_TM_DISARMING_VOICE ITEM_TM84
#define ITEM_TM_DISCHARGE ITEM_TM85
#define ITEM_TM_DIVE ITEM_TM86
#define ITEM_TM_DOUBLE_EDGE ITEM_TM87
#define ITEM_TM_DOUBLE_HIT ITEM_TM88
#define ITEM_TM_DOUBLE_KICK ITEM_TM89
#define ITEM_TM_DOUBLE_TEAM ITEM_TM90
#define ITEM_TM_DRACO_METEOR ITEM_TM91
#define ITEM_TM_DRAGON_BREATH ITEM_TM92
#define ITEM_TM_DRAGON_CHEER ITEM_TM93
#define ITEM_TM_DRAGON_CLAW ITEM_TM94
#define ITEM_TM_DRAGON_DANCE ITEM_TM95
#define ITEM_TM_DRAGON_PULSE ITEM_TM96
#define ITEM_TM_DRAGON_RUSH ITEM_TM97
#define ITEM_TM_DRAGON_TAIL ITEM_TM98
#define ITEM_TM_DRAIN_PUNCH ITEM_TM99
#define ITEM_TM_DRAINING_KISS ITEM_TM100
#define ITEM_TM_DREAM_EATER ITEM_TM101
#define ITEM_TM_DRILL_PECK ITEM_TM102
#define ITEM_TM_DRILL_RUN ITEM_TM103
#define ITEM_TM_DUAL_WINGBEAT ITEM_TM104
#define ITEM_TM_DYNAMIC_PUNCH ITEM_TM105
#define ITEM_TM_EARTH_POWER ITEM_TM106
#define ITEM_TM_EARTHQUAKE ITEM_TM107
#define ITEM_TM_ECHOED_VOICE ITEM_TM108
#define ITEM_TM_EERIE_IMPULSE ITEM_TM109
#define ITEM_TM_ELECTRIC_TERRAIN ITEM_TM110
#define ITEM_TM_ELECTRO_BALL ITEM_TM111
#define ITEM_TM_ELECTROWEB ITEM_TM112
#define ITEM_TM_ENCORE ITEM_TM113
#define ITEM_TM_ENDEAVOR ITEM_TM114
#define ITEM_TM_ENDURE ITEM_TM115
#define ITEM_TM_ENERGY_BALL ITEM_TM116
#define ITEM_TM_ENTRAINMENT ITEM_TM117
#define ITEM_TM_EXPANDING_FORCE ITEM_TM118
#define ITEM_TM_EXPLOSION ITEM_TM119
#define ITEM_TM_EXTRASENSORY ITEM_TM120
#define ITEM_TM_EXTREME_SPEED ITEM_TM121
#define ITEM_TM_FACADE ITEM_TM122
#define ITEM_TM_FAINT_ATTACK ITEM_TM123
#define ITEM_TM_FAKE_OUT ITEM_TM124
#define ITEM_TM_FAKE_TEARS ITEM_TM125
#define ITEM_TM_FALSE_SWIPE ITEM_TM126
#define ITEM_TM_FEATHER_DANCE ITEM_TM127
#define ITEM_TM_FEINT ITEM_TM128
#define ITEM_TM_FELL_STINGER ITEM_TM129
#define ITEM_TM_FINAL_GAMBIT ITEM_TM130
#define ITEM_TM_FIRE_BLAST ITEM_TM131
#define ITEM_TM_FIRE_FANG ITEM_TM132
#define ITEM_TM_FIRE_PUNCH ITEM_TM133
#define ITEM_TM_FIRE_SPIN ITEM_TM134
#define ITEM_TM_FIRST_IMPRESSION ITEM_TM135
#define ITEM_TM_FISSURE ITEM_TM136
#define ITEM_TM_FLAIL ITEM_TM137
#define ITEM_TM_FLAME_CHARGE ITEM_TM138
#define ITEM_TM_FLAMETHROWER ITEM_TM139
#define ITEM_TM_FLARE_BLITZ ITEM_TM140
#define ITEM_TM_FLATTER ITEM_TM141
#define ITEM_TM_FLING ITEM_TM142
#define ITEM_TM_FLIP_TURN ITEM_TM143
#define ITEM_TM_FLY ITEM_TM144
#define ITEM_TM_FOCUS_BLAST ITEM_TM145
#define ITEM_TM_FOCUS_ENERGY ITEM_TM146
#define ITEM_TM_FOCUS_PUNCH ITEM_TM147
#define ITEM_TM_FOLLOW_ME ITEM_TM148
#define ITEM_TM_FOUL_PLAY ITEM_TM149
#define ITEM_TM_FREEZE_DRY ITEM_TM150
#define ITEM_TM_FRENZY_PLANT ITEM_TM151
#define ITEM_TM_FURY_CUTTER ITEM_TM152
#define ITEM_TM_FUTURE_SIGHT ITEM_TM153
#define ITEM_TM_GASTRO_ACID ITEM_TM154
#define ITEM_TM_GIGA_DRAIN ITEM_TM155
#define ITEM_TM_GIGA_IMPACT ITEM_TM156
#define ITEM_TM_GLARE ITEM_TM157
#define ITEM_TM_GRASS_KNOT ITEM_TM158
#define ITEM_TM_GRASS_PLEDGE ITEM_TM159
#define ITEM_TM_GRASSY_GLIDE ITEM_TM160
#define ITEM_TM_GRASSY_TERRAIN ITEM_TM161
#define ITEM_TM_GRAVITY ITEM_TM162
#define ITEM_TM_GROWTH ITEM_TM163
#define ITEM_TM_GUARD_SPLIT ITEM_TM164
#define ITEM_TM_GUARD_SWAP ITEM_TM165
#define ITEM_TM_GUNK_SHOT ITEM_TM166
#define ITEM_TM_GUST ITEM_TM167
#define ITEM_TM_GYRO_BALL ITEM_TM168
#define ITEM_TM_HAMMER_ARM ITEM_TM169
#define ITEM_TM_HARD_PRESS ITEM_TM170
#define ITEM_TM_HARDEN ITEM_TM171
#define ITEM_TM_HAZE ITEM_TM172
#define ITEM_TM_HEAD_SMASH ITEM_TM173
#define ITEM_TM_HEADBUTT ITEM_TM174
#define ITEM_TM_HEAL_BELL ITEM_TM175
#define ITEM_TM_HEAL_PULSE ITEM_TM176
#define ITEM_TM_HEALING_WISH ITEM_TM177
#define ITEM_TM_HEAT_CRASH ITEM_TM178
#define ITEM_TM_HEAT_WAVE ITEM_TM179
#define ITEM_TM_HEAVY_SLAM ITEM_TM180
#define ITEM_TM_HELPING_HAND ITEM_TM181
#define ITEM_TM_HEX ITEM_TM182
#define ITEM_TM_HIGH_HORSEPOWER ITEM_TM183
#define ITEM_TM_HIGH_JUMP_KICK ITEM_TM184
#define ITEM_TM_HORN_DRILL ITEM_TM185
#define ITEM_TM_HOWL ITEM_TM186
#define ITEM_TM_HURRICANE ITEM_TM187
#define ITEM_TM_HYDRO_CANNON ITEM_TM188
#define ITEM_TM_HYDRO_PUMP ITEM_TM189
#define ITEM_TM_HYPER_BEAM ITEM_TM190
#define ITEM_TM_HYPER_VOICE ITEM_TM191
#define ITEM_TM_HYPNOSIS ITEM_TM192
#define ITEM_TM_ICE_BEAM ITEM_TM193
#define ITEM_TM_ICE_FANG ITEM_TM194
#define ITEM_TM_ICE_PUNCH ITEM_TM195
#define ITEM_TM_ICE_SHARD ITEM_TM196
#define ITEM_TM_ICE_SPINNER ITEM_TM197
#define ITEM_TM_ICICLE_CRASH ITEM_TM198
#define ITEM_TM_ICICLE_SPEAR ITEM_TM199
#define ITEM_TM_ICY_WIND ITEM_TM200
#define ITEM_TM_IMPRISON ITEM_TM201
#define ITEM_TM_INFESTATION ITEM_TM202
#define ITEM_TM_INGRAIN ITEM_TM203
#define ITEM_TM_IRON_DEFENSE ITEM_TM204
#define ITEM_TM_IRON_HEAD ITEM_TM205
#define ITEM_TM_IRON_TAIL ITEM_TM206
#define ITEM_TM_KNOCK_OFF ITEM_TM207
#define ITEM_TM_LASH_OUT ITEM_TM208
#define ITEM_TM_LAST_RESORT ITEM_TM209
#define ITEM_TM_LEAF_BLADE ITEM_TM210
#define ITEM_TM_LEAF_STORM ITEM_TM211
#define ITEM_TM_LEECH_LIFE ITEM_TM212
#define ITEM_TM_LEECH_SEED ITEM_TM213
#define ITEM_TM_LEER ITEM_TM214
#define ITEM_TM_LICK ITEM_TM215
#define ITEM_TM_LIFE_DEW ITEM_TM216
#define ITEM_TM_LIGHT_SCREEN ITEM_TM217
#define ITEM_TM_LIQUIDATION ITEM_TM218
#define ITEM_TM_LOW_KICK ITEM_TM219
#define ITEM_TM_LOW_SWEEP ITEM_TM220
#define ITEM_TM_LUNGE ITEM_TM221
#define ITEM_TM_MACH_PUNCH ITEM_TM222
#define ITEM_TM_MAGIC_ROOM ITEM_TM223
#define ITEM_TM_MAGICAL_LEAF ITEM_TM224
#define ITEM_TM_MAGNET_RISE ITEM_TM225
#define ITEM_TM_MEAN_LOOK ITEM_TM226
#define ITEM_TM_MEGA_DRAIN ITEM_TM227
#define ITEM_TM_MEGA_KICK ITEM_TM228
#define ITEM_TM_MEGA_PUNCH ITEM_TM229
#define ITEM_TM_MEGAHORN ITEM_TM230
#define ITEM_TM_MEMENTO ITEM_TM231
#define ITEM_TM_METAL_CLAW ITEM_TM232
#define ITEM_TM_METAL_SOUND ITEM_TM233
#define ITEM_TM_METEOR_BEAM ITEM_TM234
#define ITEM_TM_METRONOME ITEM_TM235
#define ITEM_TM_MIMIC ITEM_TM236
#define ITEM_TM_MIRROR_COAT ITEM_TM237
#define ITEM_TM_MIST ITEM_TM238
#define ITEM_TM_MISTY_EXPLOSION ITEM_TM239
#define ITEM_TM_MISTY_TERRAIN ITEM_TM240
#define ITEM_TM_MOONBLAST ITEM_TM241
#define ITEM_TM_MORNING_SUN ITEM_TM242
#define ITEM_TM_MUD_SHOT ITEM_TM243
#define ITEM_TM_MUD_SLAP ITEM_TM244
#define ITEM_TM_MUDDY_WATER ITEM_TM245
#define ITEM_TM_MYSTICAL_FIRE ITEM_TM246
#define ITEM_TM_NASTY_PLOT ITEM_TM247
#define ITEM_TM_NIGHT_SHADE ITEM_TM248
#define ITEM_TM_NIGHT_SLASH ITEM_TM249
#define ITEM_TM_NUZZLE ITEM_TM250
#define ITEM_TM_OCTAZOOKA ITEM_TM251
#define ITEM_TM_OUTRAGE ITEM_TM252
#define ITEM_TM_OVERHEAT ITEM_TM253
#define ITEM_TM_PAIN_SPLIT ITEM_TM254
#define ITEM_TM_PARTING_SHOT ITEM_TM255
#define ITEM_TM_PAY_DAY ITEM_TM256
#define ITEM_TM_PAYBACK ITEM_TM257
#define ITEM_TM_PECK ITEM_TM258
#define ITEM_TM_PERISH_SONG ITEM_TM259
#define ITEM_TM_PETAL_BLIZZARD ITEM_TM260
#define ITEM_TM_PHANTOM_FORCE ITEM_TM261
#define ITEM_TM_PIN_MISSILE ITEM_TM262
#define ITEM_TM_PLAY_ROUGH ITEM_TM263
#define ITEM_TM_PLUCK ITEM_TM264
#define ITEM_TM_POISON_FANG ITEM_TM265
#define ITEM_TM_POISON_JAB ITEM_TM266
#define ITEM_TM_POISON_POWDER ITEM_TM267
#define ITEM_TM_POISON_TAIL ITEM_TM268
#define ITEM_TM_POLLEN_PUFF ITEM_TM269
#define ITEM_TM_POLTERGEIST ITEM_TM270
#define ITEM_TM_POUNCE ITEM_TM271
#define ITEM_TM_POWER_GEM ITEM_TM272
#define ITEM_TM_POWER_SPLIT ITEM_TM273
#define ITEM_TM_POWER_SWAP ITEM_TM274
#define ITEM_TM_POWER_TRIP ITEM_TM275
#define ITEM_TM_POWER_UP_PUNCH ITEM_TM276
#define ITEM_TM_POWER_WHIP ITEM_TM277
#define ITEM_TM_PRESENT ITEM_TM278
#define ITEM_TM_PROTECT ITEM_TM279
#define ITEM_TM_PSYBEAM ITEM_TM280
#define ITEM_TM_PSYCH_UP ITEM_TM281
#define ITEM_TM_PSYCHIC ITEM_TM282
#define ITEM_TM_PSYCHIC_FANGS ITEM_TM283
#define ITEM_TM_PSYCHIC_NOISE ITEM_TM284
#define ITEM_TM_PSYCHIC_TERRAIN ITEM_TM285
#define ITEM_TM_PSYCHO_CUT ITEM_TM286
#define ITEM_TM_PSYSHIELD_BASH ITEM_TM287
#define ITEM_TM_PSYSHOCK ITEM_TM288
#define ITEM_TM_QUASH ITEM_TM289
#define ITEM_TM_QUICK_ATTACK ITEM_TM290
#define ITEM_TM_QUICK_GUARD ITEM_TM291
#define ITEM_TM_QUIVER_DANCE ITEM_TM292
#define ITEM_TM_RAIN_DANCE ITEM_TM293
#define ITEM_TM_RAPID_SPIN ITEM_TM294
#define ITEM_TM_RAZOR_SHELL ITEM_TM295
#define ITEM_TM_RECOVER ITEM_TM296
#define ITEM_TM_RECYCLE ITEM_TM297
#define ITEM_TM_REFLECT ITEM_TM298
#define ITEM_TM_REFLECT_TYPE ITEM_TM299
#define ITEM_TM_REST ITEM_TM300
#define ITEM_TM_RETALIATE ITEM_TM301
#define ITEM_TM_REVERSAL ITEM_TM302
#define ITEM_TM_ROAR ITEM_TM303
#define ITEM_TM_ROCK_BLAST ITEM_TM304
#define ITEM_TM_ROCK_POLISH ITEM_TM305
#define ITEM_TM_ROCK_SLIDE ITEM_TM306
#define ITEM_TM_ROCK_SMASH ITEM_TM307
#define ITEM_TM_ROCK_THROW ITEM_TM308
#define ITEM_TM_ROCK_TOMB ITEM_TM309
#define ITEM_TM_ROLE_PLAY ITEM_TM310
#define ITEM_TM_ROLLOUT ITEM_TM311
#define ITEM_TM_ROOST ITEM_TM312
#define ITEM_TM_ROUND ITEM_TM313
#define ITEM_TM_SAFEGUARD ITEM_TM314
#define ITEM_TM_SAND_ATTACK ITEM_TM315
#define ITEM_TM_SAND_TOMB ITEM_TM316
#define ITEM_TM_SANDSTORM ITEM_TM317
#define ITEM_TM_SCALD ITEM_TM318
#define ITEM_TM_SCALE_SHOT ITEM_TM319
#define ITEM_TM_SCARY_FACE ITEM_TM320
#define ITEM_TM_SCORCHING_SANDS ITEM_TM321
#define ITEM_TM_SCREECH ITEM_TM322
#define ITEM_TM_SEED_BOMB ITEM_TM323
#define ITEM_TM_SEISMIC_TOSS ITEM_TM324
#define ITEM_TM_SELF_DESTRUCT ITEM_TM325
#define ITEM_TM_SHADOW_BALL ITEM_TM326
#define ITEM_TM_SHADOW_CLAW ITEM_TM327
#define ITEM_TM_SHADOW_SNEAK ITEM_TM328
#define ITEM_TM_SHELL_SMASH ITEM_TM329
#define ITEM_TM_SHOCK_WAVE ITEM_TM330
#define ITEM_TM_SIMPLE_BEAM ITEM_TM331
#define ITEM_TM_SKILL_SWAP ITEM_TM332
#define ITEM_TM_SKITTER_SMACK ITEM_TM333
#define ITEM_TM_SKY_ATTACK ITEM_TM334
#define ITEM_TM_SLAM ITEM_TM335
#define ITEM_TM_SLASH ITEM_TM336
#define ITEM_TM_SLEEP_TALK ITEM_TM337
#define ITEM_TM_SLUDGE ITEM_TM338
#define ITEM_TM_SLUDGE_BOMB ITEM_TM339
#define ITEM_TM_SLUDGE_WAVE ITEM_TM340
#define ITEM_TM_SMACK_DOWN ITEM_TM341
#define ITEM_TM_SMART_STRIKE ITEM_TM342
#define ITEM_TM_SMOG ITEM_TM343
#define ITEM_TM_SMOKESCREEN ITEM_TM344
#define ITEM_TM_SNARL ITEM_TM345
#define ITEM_TM_SNORE ITEM_TM346
#define ITEM_TM_SNOWSCAPE ITEM_TM347
#define ITEM_TM_SOAK ITEM_TM348
#define ITEM_TM_SOLAR_BEAM ITEM_TM349
#define ITEM_TM_SOLAR_BLADE ITEM_TM350
#define ITEM_TM_SPARKLING_ARIA ITEM_TM351
#define ITEM_TM_SPEED_SWAP ITEM_TM352
#define ITEM_TM_SPIKES ITEM_TM353
#define ITEM_TM_SPIT_UP ITEM_TM354
#define ITEM_TM_SPITE ITEM_TM355
#define ITEM_TM_SPLASH ITEM_TM356
#define ITEM_TM_STEALTH_ROCK ITEM_TM357
#define ITEM_TM_STEEL_BEAM ITEM_TM358
#define ITEM_TM_STEEL_WING ITEM_TM359
#define ITEM_TM_STICKY_WEB ITEM_TM360
#define ITEM_TM_STOCKPILE ITEM_TM361
#define ITEM_TM_STOMP ITEM_TM362
#define ITEM_TM_STOMPING_TANTRUM ITEM_TM363
#define ITEM_TM_STONE_EDGE ITEM_TM364
#define ITEM_TM_STORED_POWER ITEM_TM365
#define ITEM_TM_STRENGTH_SAP ITEM_TM366
#define ITEM_TM_STRUGGLE_BUG ITEM_TM367
#define ITEM_TM_STUFF_CHEEKS ITEM_TM368
#define ITEM_TM_STUN_SPORE ITEM_TM369
#define ITEM_TM_SUBSTITUTE ITEM_TM370
#define ITEM_TM_SUCKER_PUNCH ITEM_TM371
#define ITEM_TM_SUNNY_DAY ITEM_TM372
#define ITEM_TM_SUPER_FANG ITEM_TM373
#define ITEM_TM_SUPERCELL_SLAM ITEM_TM374
#define ITEM_TM_SUPERPOWER ITEM_TM375
#define ITEM_TM_SUPERSONIC ITEM_TM376
#define ITEM_TM_SURF ITEM_TM377
#define ITEM_TM_SWAGGER ITEM_TM378
#define ITEM_TM_SWALLOW ITEM_TM379
#define ITEM_TM_SWEET_KISS ITEM_TM380
#define ITEM_TM_SWEET_SCENT ITEM_TM381
#define ITEM_TM_SWIFT ITEM_TM382
#define ITEM_TM_SWITCHEROO ITEM_TM383
#define ITEM_TM_SWORDS_DANCE ITEM_TM384
#define ITEM_TM_SYNTHESIS ITEM_TM385
#define ITEM_TM_TAIL_SLAP ITEM_TM386
#define ITEM_TM_TAIL_WHIP ITEM_TM387
#define ITEM_TM_TAILWIND ITEM_TM388
#define ITEM_TM_TAKE_DOWN ITEM_TM389
#define ITEM_TM_TAUNT ITEM_TM390
#define ITEM_TM_TEARFUL_LOOK ITEM_TM391
#define ITEM_TM_TEETER_DANCE ITEM_TM392
#define ITEM_TM_TEMPER_FLARE ITEM_TM393
#define ITEM_TM_THIEF ITEM_TM394
#define ITEM_TM_THRASH ITEM_TM395
#define ITEM_TM_THROAT_CHOP ITEM_TM396
#define ITEM_TM_THUNDER ITEM_TM397
#define ITEM_TM_THUNDER_FANG ITEM_TM398
#define ITEM_TM_THUNDER_PUNCH ITEM_TM399
#define ITEM_TM_THUNDER_WAVE ITEM_TM400
#define ITEM_TM_THUNDERBOLT ITEM_TM401
#define ITEM_TM_TICKLE ITEM_TM402
#define ITEM_TM_TORMENT ITEM_TM403
#define ITEM_TM_TOXIC ITEM_TM404
#define ITEM_TM_TOXIC_SPIKES ITEM_TM405
#define ITEM_TM_TRAILBLAZE ITEM_TM406
#define ITEM_TM_TRI_ATTACK ITEM_TM407
#define ITEM_TM_TRICK ITEM_TM408
#define ITEM_TM_TRICK_ROOM ITEM_TM409
#define ITEM_TM_TRIPLE_AXEL ITEM_TM410
#define ITEM_TM_TWISTER ITEM_TM411
#define ITEM_TM_U_TURN ITEM_TM412
#define ITEM_TM_UPPER_HAND ITEM_TM413
#define ITEM_TM_UPROAR ITEM_TM414
#define ITEM_TM_VACUUM_WAVE ITEM_TM415
#define ITEM_TM_VENOSHOCK ITEM_TM416
#define ITEM_TM_VOLT_SWITCH ITEM_TM417
#define ITEM_TM_WAKE_UP_SLAP ITEM_TM418
#define ITEM_TM_WATER_PLEDGE ITEM_TM419
#define ITEM_TM_WATER_PULSE ITEM_TM420
#define ITEM_TM_WATER_SPOUT ITEM_TM421
#define ITEM_TM_WATERFALL ITEM_TM422
#define ITEM_TM_WEATHER_BALL ITEM_TM423
#define ITEM_TM_WHIRLPOOL ITEM_TM424
#define ITEM_TM_WHIRLWIND ITEM_TM425
#define ITEM_TM_WIDE_GUARD ITEM_TM426
#define ITEM_TM_WILD_CHARGE ITEM_TM427
#define ITEM_TM_WILL_O_WISP ITEM_TM428
#define ITEM_TM_WING_ATTACK ITEM_TM429
#define ITEM_TM_WISH ITEM_TM430
#define ITEM_TM_WONDER_ROOM ITEM_TM431
#define ITEM_TM_WORK_UP ITEM_TM432
#define ITEM_TM_WORRY_SEED ITEM_TM433
#define ITEM_TM_X_SCISSOR ITEM_TM434
#define ITEM_TM_YAWN ITEM_TM435
#define ITEM_TM_ZEN_HEADBUTT ITEM_TM436

// These defines are simply to make sure Emerald can still compile
#define ITEM_TM_HIDDEN_POWER ITEM_TM01
#define ITEM_TM_RETURN ITEM_TM01
#define ITEM_TM_FRUSTRATION ITEM_TM01
#define ITEM_TM_SNATCH ITEM_TM01
#define ITEM_TM_SECRET_POWER ITEM_TM01
#define ITEM_TM_HAIL ITEM_TM01
// End pokedexUpdate

#endif
