#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(GLARE) \
    F(HARDEN) \
    F(DOUBLE_TEAM) \
    F(TAIL_WHIP) \
    F(LEER) \
    F(CONFIDE) \
    F(SMOKESCREEN) \
    F(WHIRLWIND) \
    F(ROAR) \
    F(RECOVER) \
    F(FOCUS_ENERGY) \
    F(SUPERSONIC) \
    F(TEETER_DANCE) \
    F(SWORDS_DANCE) \
    F(SCREECH) \
    F(SCARY_FACE) \
    F(SWEET_SCENT) \
    F(SUBSTITUTE) \
    F(MIMIC) \
    F(METRONOME) \
    F(SPLASH) \
    F(DISABLE) \
    F(ENCORE) \
    F(PAIN_SPLIT) \
    F(SLEEP_TALK) \
    F(HEAL_BELL) \
    F(MEAN_LOOK) \
    F(BLOCK) \
    F(PROTECT) \
    F(PERISH_SONG) \
    F(ENDURE) \
    F(SWAGGER) \
    F(ATTRACT) \
    F(SAFEGUARD) \
    F(BATON_PASS) \
    F(MORNING_SUN) \
    F(BELLY_DRUM) \
    F(PSYCH_UP) \
    F(DEFENSE_CURL) \
    F(STOCKPILE) \
    F(SWALLOW) \
    F(FOLLOW_ME) \
    F(HELPING_HAND) \
    F(WISH) \
    F(RECYCLE) \
    F(YAWN) \
    F(TICKLE) \
    F(SIMPLE_BEAM) \
    F(ENTRAINMENT) \
    F(WORK_UP) \
    F(REFLECT_TYPE) \
    F(GROWTH) \
    F(SHELL_SMASH) \
    F(TEARFUL_LOOK) \
    F(COPYCAT) \
    F(AFTER_YOU) \
    F(ACUPRESSURE) \
    F(STUFF_CHEEKS) \
    F(HOWL) \
    F(DETECT) \
    F(QUICK_GUARD) \
    F(BULK_UP) \
    F(COACHING) \
    F(FEATHER_DANCE) \
    F(ROOST) \
    F(TAILWIND) \
    F(DEFOG) \
    F(POISON_POWDER) \
    F(TOXIC) \
    F(ACID_ARMOR) \
    F(TOXIC_SPIKES) \
    F(GASTRO_ACID) \
    F(SAND_ATTACK) \
    F(SPIKES) \
    F(ROCK_POLISH) \
    F(WIDE_GUARD) \
    F(SANDSTORM) \
    F(STEALTH_ROCK) \
    F(STICKY_WEB) \
    F(QUIVER_DANCE) \
    F(CONFUSE_RAY) \
    F(DESTINY_BOND) \
    F(SPITE) \
    F(CURSE) \
    F(IRON_DEFENSE) \
    F(METAL_SOUND) \
    F(WILL_O_WISP) \
    F(SUNNY_DAY) \
    F(RAIN_DANCE) \
    F(AQUA_RING) \
    F(SOAK) \
    F(LIFE_DEW) \
    F(STUN_SPORE) \
    F(LEECH_SEED) \
    F(SYNTHESIS) \
    F(WORRY_SEED) \
    F(INGRAIN) \
    F(GRASSY_TERRAIN) \
    F(COTTON_GUARD) \
    F(STRENGTH_SAP) \
    F(THUNDER_WAVE) \
    F(EERIE_IMPULSE) \
    F(CHARGE) \
    F(MAGNET_RISE) \
    F(ELECTRIC_TERRAIN) \
    F(HYPNOSIS) \
    F(LIGHT_SCREEN) \
    F(REST) \
    F(AGILITY) \
    F(AMNESIA) \
    F(REFLECT) \
    F(HEALING_WISH) \
    F(TRICK) \
    F(ROLE_PLAY) \
    F(SKILL_SWAP) \
    F(IMPRISON) \
    F(COSMIC_POWER) \
    F(CALM_MIND) \
    F(GRAVITY) \
    F(TRICK_ROOM) \
    F(WONDER_ROOM) \
    F(MAGIC_ROOM) \
    F(POWER_SWAP) \
    F(GUARD_SWAP) \
    F(POWER_SPLIT) \
    F(GUARD_SPLIT) \
    F(HEAL_PULSE) \
    F(PSYCHIC_TERRAIN) \
    F(SPEED_SWAP) \
    F(ALLY_SWITCH) \
    F(HAZE) \
    F(MIST) \
    F(AURORA_VEIL) \
    F(SNOWSCAPE) \
    F(DRAGON_DANCE) \
    F(DRAGON_CHEER) \
    F(NASTY_PLOT) \
    F(FAKE_TEARS) \
    F(TORMENT) \
    F(FLATTER) \
    F(MEMENTO) \
    F(TAUNT) \
    F(SWITCHEROO) \
    F(QUASH) \
    F(PARTING_SHOT) \
    F(BABY_DOLL_EYES) \
    F(SWEET_KISS) \
    F(CHARM) \
    F(MISTY_TERRAIN) \
    F(AROMATIC_MIST) \
    F(HORN_DRILL) \
    F(SUPER_FANG) \
    F(FLAIL) \
    F(PRESENT) \
    F(ENDEAVOR) \
    F(SPIT_UP) \
    F(SEISMIC_TOSS) \
    F(COUNTER) \
    F(REVERSAL) \
    F(LOW_KICK) \
    F(FINAL_GAMBIT) \
    F(FISSURE) \
    F(NIGHT_SHADE) \
    F(HEAVY_SLAM) \
    F(GYRO_BALL) \
    F(HEAT_CRASH) \
    F(GRASS_KNOT) \
    F(ELECTRO_BALL) \
    F(MIRROR_COAT) \
    F(BEAT_UP) \
    F(FLING) \
    F(BIND) \
    F(MUD_SLAP) \
    F(INFESTATION) \
    F(ABSORB) \
    F(NUZZLE) \
    F(STORED_POWER) \
    F(TRIPLE_AXEL) \
    F(POWER_TRIP) \
    F(TAIL_SLAP) \
    F(ROCK_BLAST) \
    F(PIN_MISSILE) \
    F(BULLET_SEED) \
    F(ICICLE_SPEAR) \
    F(SCALE_SHOT) \
    F(FEINT) \
    F(DOUBLE_KICK) \
    F(SMOG) \
    F(ROLLOUT) \
    F(LICK) \
    F(ASTONISH) \
    F(DOUBLE_HIT) \
    F(PECK) \
    F(SAND_TOMB) \
    F(FIRE_SPIN) \
    F(WHIRLPOOL) \
    F(PAY_DAY) \
    F(QUICK_ATTACK) \
    F(FALSE_SWIPE) \
    F(FAKE_OUT) \
    F(ECHOED_VOICE) \
    F(MACH_PUNCH) \
    F(ROCK_SMASH) \
    F(POWER_UP_PUNCH) \
    F(VACUUM_WAVE) \
    F(DUAL_WINGBEAT) \
    F(GUST) \
    F(ACID) \
    F(ACID_SPRAY) \
    F(FURY_CUTTER) \
    F(SHADOW_SNEAK) \
    F(BULLET_PUNCH) \
    F(AQUA_JET) \
    F(MEGA_DRAIN) \
    F(ICE_SHARD) \
    F(TWISTER) \
    F(DISARMING_VOICE) \
    F(RAPID_SPIN) \
    F(SNORE) \
    F(WEATHER_BALL) \
    F(POISON_FANG) \
    F(POISON_TAIL) \
    F(CLEAR_SMOG) \
    F(ROCK_THROW) \
    F(SMACK_DOWN) \
    F(POUNCE) \
    F(FELL_STINGER) \
    F(STRUGGLE_BUG) \
    F(METAL_CLAW) \
    F(FLAME_CHARGE) \
    F(CHILLING_WATER) \
    F(TRAILBLAZE) \
    F(CHARGE_BEAM) \
    F(CONFUSION) \
    F(PAYBACK) \
    F(DRAINING_KISS) \
    F(ACROBATICS) \
    F(MUD_SHOT) \
    F(GRASSY_GLIDE) \
    F(ELECTROWEB) \
    F(ICY_WIND) \
    F(SNARL) \
    F(COVET) \
    F(SWIFT) \
    F(ROUND) \
    F(CIRCLE_THROW) \
    F(WING_ATTACK) \
    F(AERIAL_ACE) \
    F(PLUCK) \
    F(AIR_CUTTER) \
    F(BULLDOZE) \
    F(ROCK_TOMB) \
    F(ANCIENT_POWER) \
    F(BUG_BITE) \
    F(FLIP_TURN) \
    F(WATER_PULSE) \
    F(MAGICAL_LEAF) \
    F(SHOCK_WAVE) \
    F(AVALANCHE) \
    F(BREAKING_SWIPE) \
    F(DRAGON_TAIL) \
    F(DRAGON_BREATH) \
    F(BITE) \
    F(THIEF) \
    F(FAINT_ATTACK) \
    F(BRUTAL_SWING) \
    F(ASSURANCE) \
    F(STOMP) \
    F(LOW_SWEEP) \
    F(UPPER_HAND) \
    F(SLUDGE) \
    F(VENOSHOCK) \
    F(HEX) \
    F(FIRE_FANG) \
    F(OCTAZOOKA) \
    F(BRINE) \
    F(THUNDER_FANG) \
    F(PSYBEAM) \
    F(ICE_FANG) \
    F(AURORA_BEAM) \
    F(KNOCK_OFF) \
    F(HEADBUTT) \
    F(SLASH) \
    F(FACADE) \
    F(RETALIATE) \
    F(WAKE_UP_SLAP) \
    F(CROSS_POISON) \
    F(SCORCHING_SANDS) \
    F(SKITTER_SMACK) \
    F(U_TURN) \
    F(SHADOW_CLAW) \
    F(STEEL_WING) \
    F(SMART_STRIKE) \
    F(BURNING_JEALOUSY) \
    F(AQUA_CUTTER) \
    F(VOLT_SWITCH) \
    F(PSYCHO_CUT) \
    F(PSYSHIELD_BASH) \
    F(FREEZE_DRY) \
    F(NIGHT_SLASH) \
    F(SUCKER_PUNCH) \
    F(DRAIN_PUNCH) \
    F(BRICK_BREAK) \
    F(AIR_SLASH) \
    F(STOMPING_TANTRUM) \
    F(ROCK_SLIDE) \
    F(FIRE_PUNCH) \
    F(TEMPER_FLARE) \
    F(MYSTICAL_FIRE) \
    F(RAZOR_SHELL) \
    F(GIGA_DRAIN) \
    F(THUNDER_PUNCH) \
    F(PSYCHIC_NOISE) \
    F(ICE_PUNCH) \
    F(LASH_OUT) \
    F(MEGA_PUNCH) \
    F(SLAM) \
    F(EXTREME_SPEED) \
    F(TRI_ATTACK) \
    F(BODY_PRESS) \
    F(AURA_SPHERE) \
    F(DRILL_PECK) \
    F(POISON_JAB) \
    F(DRILL_RUN) \
    F(DIG) \
    F(POWER_GEM) \
    F(X_SCISSOR) \
    F(LUNGE) \
    F(LEECH_LIFE) \
    F(SHADOW_BALL) \
    F(IRON_HEAD) \
    F(WATERFALL) \
    F(DIVE) \
    F(SCALD) \
    F(WATER_PLEDGE) \
    F(SEED_BOMB) \
    F(GRASS_PLEDGE) \
    F(DISCHARGE) \
    F(ZEN_HEADBUTT) \
    F(EXTRASENSORY) \
    F(PSYSHOCK) \
    F(EXPANDING_FORCE) \
    F(ICE_SPINNER) \
    F(DRAGON_CLAW) \
    F(CRUNCH) \
    F(THROAT_CHOP) \
    F(DARK_PULSE) \
    F(DAZZLING_GLEAM) \
    F(ALLURING_VOICE) \
    F(BODY_SLAM) \
    F(BOUNCE) \
    F(LIQUIDATION) \
    F(PSYCHIC_FANGS) \
    F(ICICLE_CRASH) \
    F(DRAGON_PULSE) \
    F(DARKEST_LARIAT) \
    F(TAKE_DOWN) \
    F(HYPER_VOICE) \
    F(UPROAR) \
    F(FLY) \
    F(SLUDGE_BOMB) \
    F(EARTH_POWER) \
    F(FIRST_IMPRESSION) \
    F(BUG_BUZZ) \
    F(POLLEN_PUFF) \
    F(PHANTOM_FORCE) \
    F(FLAMETHROWER) \
    F(AQUA_TAIL) \
    F(SURF) \
    F(MUDDY_WATER) \
    F(SPARKLING_ARIA) \
    F(LEAF_BLADE) \
    F(PETAL_BLIZZARD) \
    F(ENERGY_BALL) \
    F(WILD_CHARGE) \
    F(THUNDERBOLT) \
    F(PSYCHIC) \
    F(ICE_BEAM) \
    F(PLAY_ROUGH) \
    F(SLUDGE_WAVE) \
    F(HIGH_HORSEPOWER) \
    F(HEAT_WAVE) \
    F(FOUL_PLAY) \
    F(MOONBLAST) \
    F(DYNAMIC_PUNCH) \
    F(CROSS_CHOP) \
    F(HAMMER_ARM) \
    F(EARTHQUAKE) \
    F(STONE_EDGE) \
    F(IRON_TAIL) \
    F(HARD_PRESS) \
    F(CRABHAMMER) \
    F(SUPERCELL_SLAM) \
    F(DREAM_EATER) \
    F(DRAGON_RUSH) \
    F(MISTY_EXPLOSION) \
    F(HURRICANE) \
    F(POLTERGEIST) \
    F(FIRE_BLAST) \
    F(HYDRO_PUMP) \
    F(THUNDER) \
    F(BLIZZARD) \
    F(MEGA_KICK) \
    F(THRASH) \
    F(DOUBLE_EDGE) \
    F(SUPERPOWER) \
    F(CLOSE_COMBAT) \
    F(FOCUS_BLAST) \
    F(BRAVE_BIRD) \
    F(GUNK_SHOT) \
    F(BELCH) \
    F(METEOR_BEAM) \
    F(MEGAHORN) \
    F(FLARE_BLITZ) \
    F(POWER_WHIP) \
    F(SOLAR_BEAM) \
    F(FUTURE_SIGHT) \
    F(OUTRAGE) \
    F(SOLAR_BLADE) \
    F(HIGH_JUMP_KICK) \
    F(OVERHEAT) \
    F(LEAF_STORM) \
    F(DRACO_METEOR) \
    F(LAST_RESORT) \
    F(BOOMBURST) \
    F(SKY_ATTACK) \
    F(STEEL_BEAM) \
    F(GIGA_IMPACT) \
    F(HYPER_BEAM) \
    F(FOCUS_PUNCH) \
    F(HEAD_SMASH) \
    F(HYDRO_CANNON) \
    F(WATER_SPOUT) \
    F(FRENZY_PLANT) \
    F(SELF_DESTRUCT) \
    F(EXPLOSION)

#define FOREACH_HM(F) \
    F(CUT) \
    F(STRENGTH)
/*
    F(FLY) \
    F(SURF) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)
    */

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

// Start pokedexUpdate
// PSF TODO moves are ordered by type > power > category > effect > id
// These defines are simply to make sure Emerald can still compile
#define ITEM_TM_HIDDEN_POWER ITEM_TM01
#define ITEM_TM_RETURN ITEM_TM01
#define ITEM_TM_FRUSTRATION ITEM_TM01
#define ITEM_TM_SNATCH ITEM_TM01
#define ITEM_TM_SECRET_POWER ITEM_TM01
#define ITEM_TM_HAIL ITEM_TM01
#define ITEM_HM_FLY ITEM_TM_FLY
#define ITEM_HM_SURF ITEM_TM_SURF
#define ITEM_HM_FLASH ITEM_TM01
#define ITEM_HM_ROCK_SMASH ITEM_TM_ROCK_SMASH
#define ITEM_HM_WATERFALL ITEM_TM_WATERFALL
#define ITEM_HM_DIVE ITEM_TM_DIVE
// End pokedexUpdate

#endif
