#ifndef GUARD_ADVENTURE_GUIDES_H
#define GUARD_ADVENTURE_GUIDES_H

enum AdventureGuideList
{
    GUIDE_YOUR_ADVENTURE_GUIDE,
    GUIDE_WILD_POKEMON,
    GUIDE_YOUR_ROTOM_PHONE,
    GUIDE_AUTO_HEAL,
    GUIDE_OPENING_POKEDEX,
    GUIDE_LETS_GO,
    GUIDE_YOUR_POKEMON_BOXES,
    GUIDE_LOCKING_ON,
    GUIDE_CROUCHING,
    GUIDE_NO_IDEA_1,
    GUIDE_CATCHING_POKEMON,
    GUIDE_NO_IDEA_2,
    GUIDE_SOMETHING_1,
    GUIDE_SOMETHING_2,
    GUIDE_SOMETHING_3,
    GUIDE_SOMETHING_4,
    GUIDE_SOMETHING_5,
    GUIDE_SOMETHING_6,
    NUM_GUIDES,
};

enum
{
    FONT_COLOR_ADVENTURE_BLACK,
    FONT_COLOR_ADVENTURE_WHITE,
    FONT_COLOR_ADVENTURE_WHITE_2,
    FONT_COLOR_ADVENTURE_RED,
    FONT_COLOR_ADVENTURE_BLUE,
};

enum
{
	BG0_ADVENTURE_GUIDE_TEXT,
	BG1_ADVENTURE_GUIDE_LIST,
	BG2_ADVENTURE_LIST_BOXES,
    BG3_ADVENTURE_LIST_GENERIC,
	NUM_ADVENTURE_GUIDE_BACKGROUNDS,
};

enum
{
    SPRITE_ADVENTURE_UP_ARROW,
    SPRITE_ADVENTURE_DOWN_ARROW,
    SPRITE_ADVENTURE_LEFT_ARROW,
    SPRITE_ADVENTURE_RIGHT_ARROW,
    NUM_ADVENTURE_GUIDE_SPRITES,
};

enum AdventureWindows
{
    WINDOW_ADVENTURE_LIST_HEADER,
    WINDOW_ADVENTURE_LIST,
    WINDOW_ADVENTURE_LIST_FOOTER,
    WINDOW_ADVENTURE_GUIDE_HEADER,
    WINDOW_ADVENTURE_GUIDE_DESC,
    WINDOW_ADVENTURE_GUIDE_FOOTER,
    WINDOW_ADVENTURE_COUNT,
};

#define ADVENTURE_GUIDE_TRANSPARENCY_STRENGTH 3
#define ADVENTURE_GUIDE_INFO_WIDTH 176
#define ADVENTURE_GUIDE_LINES 9
#define ADVENTURE_GUIDE_INFO_HEIGHT 128

#define MAX_ADVENTURE_GUIDE_ROWS_ON_SCREEN 8
#define MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW  2
#define MAX_ADVENTURE_GUIDE_ITEMS          MAX_ADVENTURE_GUIDE_ROWS_ON_SCREEN * MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW
#define MAX_ADVENTURE_GUIDE_ROWS           NUM_GUIDES / MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW
#define VAR_ADVENTURE_GUIDE_TO_OPEN        VAR_TEMP_0 // To change

#endif //GUARD_ADVENTURE_GUIDES_H
