#ifndef GUARD_ADVENTURE_GUIDES_H
#define GUARD_ADVENTURE_GUIDES_H

enum AdventureGuideList
{
    GUIDE_ADVENTURE_GUIDE,
    GUIDE_POKEDEX,
    GUIDE_POKEMON_BOXES,
    GUIDE_CATCHING_POKEMON,
    GUIDE_BATTLING_WILD_POKEMON,
    GUIDE_REMEMBERING_MOVES,
    GUIDE_FEELING_LOST,
    GUIDE_SURPRISE_TRADE,
    GUIDE_FISHING,
    GUIDE_GYM_CHALLENGE,
    GUIDE_TYPE_MATCHUPS,
    GUIDE_HELD_TIEMS,
    GUIDE_WEATHER,
    GUIDE_LITTLE_CUP,
    GUIDE_TERRAIN,
    GUIDE_SPEED_CONTROL,
    GUIDE_HAZARDS,
    GUIDE_ARRIBA,
    GUIDE_PRESTO,
    GUIDE_BUZZR,
    GUIDE_BAG,
    GUIDE_FREE_SPACE,
    GUIDE_SETTINGS,
    GUIDE_QUESTS,
    GUIDE_DEXNAV,
    GUIDE_TRAINER_CARD,
    GUIDE_WAVES_OF_CHANGE,
    GUIDE_CUSTOMIZE,
    GUIDE_STAT_POINTS,
    GUIDE_IV,
    GUIDE_GLASS,
    GUIDE_FIELD_MOVES,
    GUIDE_FIELD_MOVE_TOOLS,
    GUIDE_SHINY_POKEMON,
    GUIDE_POKERUS,
    GUIDE_REMATCHES,
    GUIDE_BATTLE_FACILITY,
    NUM_GUIDES,
};

enum
{
    FONT_COLOR_ADVENTURE_BLACK,
    FONT_COLOR_ADVENTURE_WHITE,
    FONT_COLOR_ADVENTURE_WHITE_2,
    FONT_COLOR_ADVENTURE_RED,
    FONT_COLOR_ADVENTURE_BLUE,
};

enum AdventureBackgrounds
{
	BG0_ADVENTURE_GUIDE_TEXT,
	BG1_ADVENTURE_GUIDE_LIST,
	BG2_ADVENTURE_LIST_BOXES,
    BG3_ADVENTURE_LIST_GENERIC,
	BG_ADVENTURE_GUIDE_COUNT,
};

enum AdventureSpriteArrows
{
    SPRITE_ADVENTURE_UP_ARROW,
    SPRITE_ADVENTURE_DOWN_ARROW,
    SPRITE_ADVENTURE_LEFT_ARROW,
    SPRITE_ADVENTURE_RIGHT_ARROW,
    NUM_ADVENTURE_GUIDE_SPRITES,
};

enum AdventureWindows
{
    WINDOW_ADVENTURE_GUIDE_HEADER,
    WINDOW_ADVENTURE_GUIDE_DESC,
    WINDOW_ADVENTURE_LIST_HEADER,
    WINDOW_ADVENTURE_LIST,
    WINDOW_ADVENTURE_LIST_FOOTER,
    WINDOW_ADVENTURE_COUNT,
};

#define ADVENTURE_GUIDE_TRANSPARENCY_STRENGTH 3
#define ADVENTURE_GUIDE_INFO_WIDTH 176
#define ADVENTURE_GUIDE_LINES 11
#define ADVENTURE_GUIDE_INFO_HEIGHT 128

#define MAX_ADVENTURE_GUIDE_ROWS_ON_SCREEN 8
#define MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW  2
#define MAX_ADVENTURE_GUIDE_ITEMS          MAX_ADVENTURE_GUIDE_ROWS_ON_SCREEN * MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW
#define MAX_ADVENTURE_GUIDE_ROWS           NUM_GUIDES / MAX_ADVENTURE_GUIDE_ITEMS_PER_ROW
#define VAR_ADVENTURE_GUIDE_TO_OPEN        VAR_TEMP_0 // To change

#define ADVENTURE_UP_ARROW_X (120 - 16)
#define ADVENTURE_UP_ARROW_Y 0
#define ADVENTURE_DOWN_ARROW_X ADVENTURE_UP_ARROW_X
#define ADVENTURE_DOWN_ARROW_Y (DISPLAY_HEIGHT - 16)
#define ADVENTURE_LEFT_ARROW_X 8
#define ADVENTURE_LEFT_ARROW_Y (DISPLAY_HEIGHT / 2)
#define ADVENTURE_RIGHT_ARROW_X (DISPLAY_WIDTH - 16)
#define ADVENTURE_RIGHT_ARROW_Y ADVENTURE_LEFT_ARROW_X

#define PAL_ADVENTURE_UI_SPRITES 123
#define ADVENTURE_SPRITE_TAG 1000

#define PAL_ID_ADVENTURE_UI     0
#define PAL_ID_ADVENTURE_TEXT   15
#define PAL_SLOT_ADVENTURE_UI   BG_PLTT_ID(PAL_ID_ADVENTURE_UI)
#define PAL_SLOT_ADVENTURE_TEXT BG_PLTT_ID(PAL_ID_ADVENTURE_TEXT)

#define PAL_SLOT_ADVENTURE_CURSOR 6
#define PAL_ID_ADVENTURE_LIST_TEXT 7

#define PAL_INDEX_CURSOR (PAL_SLOT_ADVENTURE_TEXT + PAL_SLOT_ADVENTURE_CURSOR)
#define PAL_INDEX_LIST_TEXT (PAL_SLOT_ADVENTURE_TEXT + PAL_ID_ADVENTURE_LIST_TEXT)

#define ADVENTURE_CURSOR_COLOR RGB2GBA(79,226,125)
#define ADVENTURE_DARK_CURSOR_COLOR RGB2GBA(55,112,73)
#define ADVENTURE_DARK_LIST_TEXT_COLOR RGB2GBA(125,125,125)
#define ADVENTURE_LIST_TEXT_COLOR RGB2GBA(255,255,255)

#define MAX_GUIDE_PAGES 10

#define MAX_CURSOR_NUM_X 2
#define MAX_CURSOR_NUM_Y 8

enum AdvancedGuideStatus
{
    ADVENTURE_GUIDE_NONE,
    ADVENTURE_GUIDE_BASIC,
    ADVENTURE_GUIDE_ADVANCED,
};

#endif //GUARD_ADVENTURE_GUIDES_H
