#ifndef GUARD_CONSTANTS_UI_CHARACTER_CUSTOMIZATION_MENU_H
#define GUARD_CONSTANTS_UI_CHARACTER_CUSTOMIZATION_MENU_H

#include "ui_character_customization_menu.h"

//For Customization
enum{
    CUSTOMIZATION_BODY_TYPE,
    CUSTOMIZATION_SKIN_COLOR,
    CUSTOMIZATION_HAIR_COLOR,
    CUSTOMIZATION_PRIMARY_COLOR,
    CUSTOMIZATION_SECONDARY_COLOR,
    CUSTOMIZATION_SUBJECT_PRONOUN,
    CUSTOMIZATION_OBJECT_PRONOUN,
    CUSTOMIZATION_POSSESIVE_PRONOUN,
    NUM_CUSTOMIZATION_PARTS,
};

enum{
    OPTION_COLOR_RED,
    OPTION_COLOR_GREEN,
    OPTION_COLOR_BLUE,
    NUM_COLOR_OPTIONS
};

enum
{
    BODY_TYPE_M1,
    BODY_TYPE_M2,
    BODY_TYPE_M3,
    BODY_TYPE_N1,
    BODY_TYPE_N2,
    BODY_TYPE_N3,
    BODY_TYPE_F1,
    BODY_TYPE_F2,
    BODY_TYPE_F3,
    BODY_TYPE_CHAMPION,
    NUM_ALL_BODY_TYPES,
};
#define NUM_BODY_TYPES (BODY_TYPE_F3 + 1)

enum
{
    HAIR_COLOR_GOLD,
    HAIR_COLOR_DARK_BROWN,
    HAIR_COLOR_ASH_BROWN,
    HAIR_COLOR_LIGHT_BROWN,
    HAIR_COLOR_PLATINUM,
    HAIR_COLOR_PINK_BROWN,
    HAIR_COLOR_WINE_RED,
    HAIR_COLOR_GREEN,
    HAIR_COLOR_WHITE,
    HAIR_COLOR_PINK,
    HAIR_COLOR_BLUE,
    HAIR_COLOR_RED,
    HAIR_COLOR_SMOKY_PINK,
    HAIR_COLOR_BLUE_GREEN,
    HAIR_COLOR_LAVENDER,
    HAIR_COLOR_VIOLET,
    HAIR_COLOR_SCARLET,
    HAIR_COLOR_SILVER,
    HAIR_COLOR_ASH_PURPLE,
    HAIR_COLOR_ASH_WHITE,
    HAIR_COLOR_ASH_BLOND,
    HAIR_COLOR_ASH_GREEN,
    HAIR_COLOR_DARK_DENIM,
    HAIR_COLOR_DENIM,
    HAIR_COLOR_LIGHT_DENIM,
    HAIR_COLOR_BLACK,
    HAIR_COLOR_CUSTOM,
    NUM_HAIR_COLOR,
};

enum
{
    SKIN_COLOR_PALE_IVORY,
    SKIN_COLOR_PORCELAIN,
    SKIN_COLOR_FAIR,
    SKIN_COLOR_WARM_IVORY,
    SKIN_COLOR_SAND,
    SKIN_COLOR_PEACH,
    SKIN_COLOR_ROSE,
    SKIN_COLOR_GOLDEN,
    SKIN_COLOR_OLIVE,
    SKIN_COLOR_CARAMEL,
    SKIN_COLOR_HONEY,
    SKIN_COLOR_AMBER,
    SKIN_COLOR_MAHOGANY,
    SKIN_COLOR_SIENNA,
    SKIN_COLOR_BRONZE,
    SKIN_COLOR_ESPRESSO,
    SKIN_COLOR_EBONY,
    SKIN_COLOR_COCOA,
    SKIN_COLOR_CUSTOM,
    NUM_SKIN_COLOR,
};

enum
{
    OUTFIT_COLOR_SCARLET,
    OUTFIT_COLOR_BLACK,
    OUTFIT_COLOR_WHITE,
    OUTFIT_COLOR_GOLDEN,
    OUTFIT_COLOR_RUBY,
    OUTFIT_COLOR_EMERALD,
    OUTFIT_COLOR_SAPPHIRE,
    OUTFIT_COLOR_VIOLET,
    OUTFIT_COLOR_SILVER,
    OUTFIT_COLOR_CUSTOM,
    NUM_PRIMARY_COLOR,
};

enum SubjectPronouns
{
    PRONOUN_SUBJECT_THEY,
    PRONOUN_SUBJECT_HE,
    PRONOUN_SUBJECT_SHE,
    PRONOUN_SUBJECT_CUSTOM,
    PRONOUN_SUBJECT_COUNT,
};

enum ObjectPronouns
{
    PRONOUN_OBJECT_THEM,
    PRONOUN_OBJECT_HIM,
    PRONOUN_OBJECT_HER,
    PRONOUN_OBJECT_CUSTOM,
    PRONOUN_OBJECT_COUNT,
};


enum PossessivePronouns
{
    PRONOUN_POSSESSIVE_THEIR,
    PRONOUN_POSSESSIVE_HIS,
    PRONOUN_POSSESSIVE_HER,
    PRONOUN_POSSESSIVE_CUSTOM,
    PRONOUN_POSSESSIVE_COUNT,
};

#define NUM_PRONOUN_TYPES 3
#define NUM_COLOR_LEVEL 11

enum PlayerPaletteSlots
{
    PLAYER_OUTLINE_COLOR_TRANSPERANT,
    PLAYER_OUTLINE_COLOR_DARK_GRAY,
    PLAYER_OUTLINE_COLOR_LIGHT_GRAY,
    PLAYER_HAIR_COLOR_3,
    PLAYER_HAIR_COLOR_2,
    PLAYER_HAIR_COLOR_1,
    PLAYER_SECONDARY_COLOR_3,
    PLAYER_SECONDARY_COLOR_2,
    PLAYER_SECONDARY_COLOR_1,
    PLAYER_SKIN_COLOR_3,
    PLAYER_SKIN_COLOR_2,
    PLAYER_SKIN_COLOR_1,
    PLAYER_PRIMARY_COLOR_2,
    PLAYER_PRIMARY_COLOR_1,
    PLAYER_OUTLINE_COLOR_WHITE,
    PLAYER_OUTLINE_COLOR_BLACK,
    PLAYER_PALETTE_COUNT,
};

enum
{
    BACKGROUND_NULL,
    NORMAL_BACKGROUND_NUM,
    SCROLLING_BACKGROUND_NUM,
};

#define MAX_CUSTOMIZATION_OPTIONS_PER_SETTING 27
#define NUM_MAX_CUSTOMIZATION_PARTS_ON_SCREEN 6

#define UP_CUSTOM_ARROW_X 109 + 8
#define UP_CUSTOM_ARROW_Y 19

#define DOWN_CUSTOM_ARROW_X UP_CUSTOM_ARROW_X
#define DOWN_CUSTOM_ARROW_Y 132

#define LEFT_CUSTOM_ARROW_X 168
#define LEFT_CUSTOM_ARROW_Y 36
#define RIGHT_CUSTOM_ARROW_X LEFT_CUSTOM_ARROW_X + 64
#define RIGHT_CUSTOM_ARROW_Y LEFT_CUSTOM_ARROW_Y

#define TRAINER_OVERWORLD_PIC_X 37 - 16
#define TRAINER_OVERWORLD_PIC_Y 128 - 16
#define TRAINER_OVERWORLD_PALETTE_SLOT 1

#define TRAINER_BACK_SPRITE_X 37
#define TRAINER_BACK_SPRITE_Y 55

#define NUM_BIKE_ANIMS 4
#define NUM_PLAYER_ANIMS 8
#define NUM_MOVEMENT_FRAMES 100
#define ANIMATION_NONE DIR_SOUTH

enum CustomizeBackgrounds
{
	CUSTOMIZATION_MENU_BG_TEXT,
    CUSTOMIZATION_MENU_BG_BOXES,
    CUSTOMIZATION_MENU_BG_SHADOWS,
    CUSTOMIZATION_MENU_BG_ART,
	NUM_CUSTOMIZATION_BACKGROUNDS,
};

//Sprites
enum SpriteIDs
{
    SPRITE_TRAINER_FRONT_SPRITE,
    SPRITE_TRAINER_BACK_SPRITE,
    SPRITE_TRAINER_OVERWORLD,
    SPRITE_TRAINER_OVERWORLD_BIKE,
    SPRITE_TRAINER_OVERWORLD_POKEMON_CALL,
    SPRITE_UP_CUSTOM_ARROW,
    SPRITE_DOWN_CUSTOM_ARROW,
    SPRITE_LEFT_CUSTOM_ARROW,
    SPRITE_RIGHT_CUSTOM_ARROW,
    NUM_SPRITES,
};

enum CustomizeWindows
{
    CUSTOM_WINDOW_HEADER,
    CUSTOM_WINDOW_OPTIONS,
    CUSTOM_WINDOW_VALUES,
    CUSTOM_WINDOW_FOOTER,
    CUSTOM_WINDOW_COUNT,
};

enum DialogueIds
{
    DRAWN_DIALOGUE_HELP_BAR,
    DRAWN_DIALOGUE_LEAVE_DIALOG,
};

enum{
    STATE_PLAYER_FRONT_SPRITE,
    STATE_PLAYER_BACK_SPRITE,
    STATE_PLAYER_OVERWORLD_SPRITE,
    STATE_PLAYER_BIKE_SPRITE,
    STATE_PLAYER_POKEMON_CALL_SPRITE,
    NUM_PLAYER_SPRITE_STATES,
};

enum{
    SEQUENCE_WALK_DOWN,
    SEQUENCE_WALK_RIGHT,
    SEQUENCE_WALK_UP,
    SEQUENCE_WALK_LEFT,
    SEQUENCE_RUN_DOWN,
    SEQUENCE_RUN_RIGHT,
    SEQUENCE_RUN_UP,
    SEQUENCE_RUN_LEFT,
    SEQUENCE_BIKE_DOWN,
    SEQUENCE_BIKE_RIGHT,
    SEQUENCE_BIKE_UP,
    SEQUENCE_BIKE_LEFT,
    SEQUENCE_CALL_POKEMON,
    NUM_SEQUENCES,
};

enum
{
    FONT_CUSTOM_BLACK,
    FONT_CUSTOM_WHITE,
};


#endif // GUARD_CONSTANTS_UI_CHARACTER_CUSTOMIZATION_MENU_H
