#ifndef GUARD_CONSTANTS_UI_DEXNAV_H
#define GUARD_CONSTANTS_UI_DEXNAV_H

#define DEXNAV_PALETTE_INTERFACE_ID   0
#define DEXNAV_PALETTE_INTERFACE_SLOT BG_PLTT_ID(DEXNAV_PALETTE_INTERFACE_ID)
#define DEXNAV_PALETTE_TEXT_ID        15
#define DEXNAV_PALETTE_TEXT_SLOT      BG_PLTT_ID(DEXNAV_PALETTE_TEXT_ID)

enum DexnavMode
{
  DEXNAV_MODE_OVERVIEW,
  DEXNAV_MODE_SEARCH,
  DEXNAV_MODE_COUNT,
};

enum DexnavBackgrounds
{
  BG0_DEXNAV_TEXT,
  BG1_DEXNAV_WHEEL,
  BG2_DEXNAV_UI,
  BG3_DEXNAV_BACKGROUNDS,
  BG_DEXNAV_COUNT,
};

enum DexnavWindows
{
  WIN_DEXNAV_HEADER,
  WIN_DEXNAV_INTERFACE_INSIGHT,
  WIN_DEXNAV_INTERFACE_MON_INFO,
  WIN_DEXNAV_INTERFACE_STREAK,
  WIN_DEXNAV_HELP_BAR,
};

enum DexnavSpriteIds
{
  DEXNAV_SPRITEIDS_COUNT,
};

#endif // GUARD_CONSTANTS_UI_DEXNAV_H
