#ifndef GUARD_CONSTANTS_UI_DEXNAV_H
#define GUARD_CONSTANTS_UI_DEXNAV_H

#define DEXNAV_PALETTE_INTERFACE_ID   0
#define DEXNAV_PALETTE_INTERFACE_SLOT BG_PLTT_ID(DEXNAV_PALETTE_INTERFACE_ID)
#define DEXNAV_PALETTE_HABITAT_ID     13
#define DEXNAV_PALETTE_HABITAT_SLOT   BG_PLTT_ID(DEXNAV_PALETTE_HABITAT_ID)
#define DEXNAV_PALETTE_TEXT_ID        15
#define DEXNAV_PALETTE_TEXT_SLOT      BG_PLTT_ID(DEXNAV_PALETTE_TEXT_ID)
#define DEXNAV_PALETTE_TYPE_ID        13
#define DEXNAV_PALETTE_TYPE_SLOT      OBJ_PLTT_ID(DEXNAV_PALETTE_TYPE_ID)
#define DEXNAV_PALETTE_MAIN_MON_ID        (DEXNAV_PALETTE_TYPE_ID - 1)
#define DEXNAV_PALETTE_MAIN_MON_SLOT      OBJ_PLTT_ID(DEXNAV_PALETTE_MAIN_MON_ID)
#define DEXNAV_PALETTE_ALL_BLACK_ID        (DEXNAV_PALETTE_MAIN_MON_ID - 1)
#define DEXNAV_PALETTE_ALL_BLACK_SLOT      OBJ_PLTT_ID(DEXNAV_PALETTE_ALL_BLACK_ID)

enum DexnavMode
{
  DEXNAV_MODE_MAIN,
  DEXNAV_MODE_SCAN,
  DEXNAV_MODE_COUNT,
};

enum DexnavHabitats
{
  DEXNAV_HABITAT_LAND,
  DEXNAV_HABITAT_WATER,
  DEXNAV_HABITAT_NONE,
  DEXNAV_HABITAT_COUNT,
};

enum DexnavBackgrounds
{
  BG0_DEXNAV_TEXT,
  BG1_DEXNAV_WHEEL,
  BG2_DEXNAV_UI,
  BG3_DEXNAV_BACKGROUNDS,
  BG_DEXNAV_COUNT,
};

enum DexnavWindows
{
  WIN_DEXNAV_HEADER,
  WIN_DEXNAV_INTERFACE_INSIGHT,
  WIN_DEXNAV_INTERFACE_ABILITY = WIN_DEXNAV_INTERFACE_INSIGHT,
  WIN_DEXNAV_INTERFACE_MON_INFO,
  WIN_DEXNAV_INTERFACE_STREAK,
  WIN_DEXNAV_INTERFACE_MOVE = WIN_DEXNAV_INTERFACE_STREAK,
  WIN_DEXNAV_HELP_BAR,
  WIN_DEXNAV_HABITAT_HEADER,
};

enum DexnavSpriteIds
{
  DEXNAV_SPRITEID_COMPLETION_MARK,
  DEXNAV_SPRITEID_INSIGHT_POSITION_0,
  DEXNAV_SPRITEID_INSIGHT_POSITION_1,
  DEXNAV_SPRITEID_INSIGHT_POSITION_2,
  DEXNAV_SPRITEID_STREAK_POSITION_0,
  DEXNAV_SPRITEID_STREAK_POSITION_1,
  DEXNAV_SPRITEID_STREAK_POSITION_2,
  DEXNAV_SPRITEID_INDICATOR_ABILITY,
  DEXNAV_SPRITEID_INDICATOR_LEVEL,
  DEXNAV_SPRITEID_INDICATOR_ITEM,
  DEXNAV_SPRITEID_INDICATOR_MOVE,
  DEXNAV_SPRITEID_INDICATOR_FISHING,
  DEXNAV_SPRITEID_TYPE_0,
  DEXNAV_SPRITEID_TYPE_1,
  DEXNAV_SPRITEID_FAB,
  DEXNAV_SPRITEID_MON_MAIN,
  DEXNAV_SPRITEID_MON_0,
  DEXNAV_SPRITEID_MON_1,
  DEXNAV_SPRITEID_MON_2,
  DEXNAV_SPRITEID_MON_3,
  DEXNAV_SPRITEID_MON_4,
  DEXNAV_SPRITEID_MON_5,
  DEXNAV_SPRITEID_MON_6,
  DEXNAV_SPRITEID_MON_7,
  DEXNAV_SPRITEID_MON_8,
  DEXNAV_SPRITEID_MON_9,
  DEXNAV_SPRITEID_MON_10,
  DEXNAV_SPRITEID_MON_11,
  DEXNAV_SPRITEID_INDICATOR_IV_0,
  DEXNAV_SPRITEID_INDICATOR_IV_1,
  DEXNAV_SPRITEID_INDICATOR_IV_2,
  DEXNAV_SPRITEID_INDICATOR_IV_3,
  DEXNAV_SPRITEID_INDICATOR_IV_4,
  DEXNAV_SPRITEID_INDICATOR_IV_5,
  DEXNAV_SPRITEID_INDICATOR_IV_6,
  DEXNAV_SPRITEID_INDICATOR_IV_7,
  DEXNAV_SPRITEID_INDICATOR_IV_8,
  DEXNAV_SPRITEID_INDICATOR_IV_9,
  DEXNAV_SPRITEID_INDICATOR_IV_10,
  DEXNAV_SPRITEID_INDICATOR_IV_11,
  DEXNAV_SPRITEID_CURSOR,
  DEXNAV_SPRITEID_REGISTER,
  DEXNAV_SPRITEID_OVERWORLD,
  DEXNAV_SPRITEIDS_COUNT,
};

enum DexnavSpriteTags
{
  DEXNAV_SPRITETAG = 3118,
  DEXNAV_SPRITETAG_COMPLETION,
  DEXNAV_SPRITETAG_STAR,
  DEXNAV_SPRITETAG_FISHING,
  DEXNAV_SPRITETAG_TYPES,
  DEXNAV_SPRITETAG_FAB,
  DEXNAV_SPRITETAG_INDICATOR,
  DEXNAV_SPRITETAG_IV,
  DEXNAV_SPRITETAG_MAIN_MON,
  DEXNAV_SPRITETAG_CURSOR,
  DEXNAV_SPRITETAG_REGISTER,
  DEXNAV_SPRITETAG_OVERWORLD,
};

enum DexnavPalTags
{
  DEXNAV_PALTAG = 2118,
  DEXNAV_PALTAG_ARROW_COMPLETION_STAR_FAB_FISHING,
  DEXNAV_PALTAG_TYPES,
  DEXNAV_PALTAG_INDICATOR,
  DEXNAV_PALTAG_IV,
  DEXNAV_PALTAG_MAIN_MON,
};

enum DexnavFontColors
{
  DEXNAV_FONT_COLOR_BLACK,
  DEXNAV_FONT_COLOR_WHITE,
  DEXNAV_FONT_COLOR_COUNT,
};

#define FONT_DEXNAV_HELPBAR FONT_NORMAL
#define FONT_DEXNAV_STAT_HEADER FONT_NARROW
#define FONT_DEXNAV_SCAN_HEADER FONT_SMALL_NARROW
#define DEXNAV_HABITAT_HEADER_WIDTH (17 * TILE_SIZE_4BPP * 2)

enum DexnavStarStates
{
  DEXNAV_STAR_SMALL_EMPTY,
  DEXNAV_STAR_SMALL_HALF,
  DEXNAV_STAR_SMALL_FULL,
  DEXNAV_STAR_SMALL_SPARKLE,
  DEXNAV_STAR_BIG_EMPTY,
  DEXNAV_STAR_BIG_HALF,
  DEXNAV_STAR_BIG_FULL,
  DEXNAV_STAR_BIG_SPARKLE,
  DEXNAV_STAR_SMALL_SPARKLE_MID,
  DEXNAV_STAR_BIG_SPARKLE_MID,
};

enum DexnavStarPosition
{
  DEXNAV_STAR_LEFT,
  DEXNAV_STAR_CENTER,
  DEXNAV_STAR_RIGHT,
  DEXNAV_STAR_POSITION_COUNT,
};

enum DexnavArrowPositions
{
  DEXNAV_ARROWS_OUT,
  DEXNAV_ARROWS_IN,
  DEXNAV_ARROWS_COUNT,
};

enum DexnavCursorState
{
  DEXNAV_CURSOR_STEP_0,
  DEXNAV_CURSOR_STEP_1,
  DEXNAV_CURSOR_STEP_2,
};

enum DexnavCursorPositionMovement
{
  DEXNAV_DECREMENT_POSITION = -1,
  DEXNAV_NULL_POSITION,
  DEXNAV_INCREMENT_POSITION,
};

enum 
{
  DEXNAV_OVERWORLD_STEP_0,
  DEXNAV_OVERWORLD_STEP_1,
  DEXNAV_OVERWORLD_STEP_2,
  DEXNAV_OVERWORLD_STEP_3,
  DEXNAV_OVERWORLD_STEP_4,
  DEXNAV_OVERWORLD_STEP_5,
  DEXNAV_OVERWORLD_STEP_6,
  DEXNAV_OVERWORLD_STEP_7,
  DEXNAV_OVERWORLD_STEP_8,
};

#define DEXNAV_OVERWORLD_SPRITE_X 192
#define DEXNAV_OVERWORLD_SPRITE_Y 16

#define DEXNAV_OVERWORLD_FRAME_SIZE 16
#define DEXNAV_OVERWORLD_FRAME_0 (DEXNAV_OVERWORLD_STEP_0 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_1 (DEXNAV_OVERWORLD_STEP_1 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_2 (DEXNAV_OVERWORLD_STEP_2 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_3 (DEXNAV_OVERWORLD_STEP_3 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_4 (DEXNAV_OVERWORLD_STEP_4 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_5 (DEXNAV_OVERWORLD_STEP_5 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_6 (DEXNAV_OVERWORLD_STEP_6 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_7 (DEXNAV_OVERWORLD_STEP_7 * DEXNAV_OVERWORLD_FRAME_SIZE)
#define DEXNAV_OVERWORLD_FRAME_8 (DEXNAV_OVERWORLD_STEP_8 * DEXNAV_OVERWORLD_FRAME_SIZE)
  
#define DEXNAV_CURSOR_FRAME_0 (DEXNAV_CURSOR_STEP_0 * 64)
#define DEXNAV_CURSOR_FRAME_1 (DEXNAV_CURSOR_STEP_1 * 64)
#define DEXNAV_CURSOR_FRAME_2 (DEXNAV_CURSOR_STEP_2 * 64)

#define DEXNAV_ARROW_FRAME_OUT (DEXNAV_ARROWS_OUT * 32)
#define DEXNAV_ARROW_FRAME_IN (DEXNAV_ARROWS_IN * 32)

#define DEXNAV_FAB_FRAME_SCAN (DEXNAV_MODE_MAIN * 16)
#define DEXNAV_FAB_FRAME_CANCEL (DEXNAV_MODE_SCAN * 16)

#define DEXNAV_STAR_FRAME_SMALL_EMPTY (DEXNAV_STAR_SMALL_EMPTY * 4)
#define DEXNAV_STAR_FRAME_SMALL_HALF (DEXNAV_STAR_SMALL_HALF * 4)
#define DEXNAV_STAR_FRAME_SMALL_FULL (DEXNAV_STAR_SMALL_FULL * 4)
#define DEXNAV_STAR_FRAME_SMALL_SPARKLE (DEXNAV_STAR_SMALL_SPARKLE * 4)
#define DEXNAV_STAR_FRAME_BIG_EMPTY (DEXNAV_STAR_BIG_EMPTY * 4)
#define DEXNAV_STAR_FRAME_BIG_HALF (DEXNAV_STAR_BIG_HALF * 4)
#define DEXNAV_STAR_FRAME_BIG_FULL (DEXNAV_STAR_BIG_FULL * 4)
#define DEXNAV_STAR_FRAME_BIG_SPARKLE (DEXNAV_STAR_BIG_SPARKLE * 4)

#define DEXNAV_MAX_SHOWN_MONS 12
#define RGB_DEXNAV_GRAY RGB2GBA(89,89,89)
#define DEXNAV_MAX_INSIGHT 200
#define DEXNAV_MAX_STREAK UCHAR_MAX
#define DEXNAV_INSIGHT_PERCENT_10        (DEXNAV_MAX_INSIGHT * 10 / 100)
#define DEXNAV_INSIGHT_PERCENT_50        (DEXNAV_MAX_INSIGHT * 50 / 100)
#define DEXNAV_INSIGHT_PERCENT_75        (DEXNAV_MAX_INSIGHT * 75 / 100)
#define DEXNAV_INSIGHT_PERCENT_5         (DEXNAV_MAX_INSIGHT * 5 / 100)
#define DEXNAV_INSIGHT_PERCENT_12_5      (DEXNAV_MAX_INSIGHT * 1250 / 10000)
#define DEXNAV_MAX_ITEM_ABILITY_CHANCE   50
#define DEXNAV_ITEM_RARE_CHANCE          9

#endif // GUARD_CONSTANTS_UI_DEXNAV_H
