#ifndef GUARD_CONSTANTS_UI_DEXNAV_H
#define GUARD_CONSTANTS_UI_DEXNAV_H

#define DEXNAV_PALETTE_INTERFACE_ID   0
#define DEXNAV_PALETTE_INTERFACE_SLOT BG_PLTT_ID(DEXNAV_PALETTE_INTERFACE_ID)
#define DEXNAV_PALETTE_TEXT_ID        15
#define DEXNAV_PALETTE_TEXT_SLOT      BG_PLTT_ID(DEXNAV_PALETTE_TEXT_ID)

enum DexnavMode
{
  DEXNAV_MODE_MAIN,
  DEXNAV_MODE_SCAN,
  DEXNAV_MODE_COUNT,
};

enum DexnavHabitats
{
  DEXNAV_HABITAT_LAND,
  DEXNAV_HABITAT_WATER,
  DEXNAV_HABITAT_COUNT,
};

enum DexnavBackgrounds
{
  BG0_DEXNAV_TEXT,
  BG1_DEXNAV_WHEEL,
  BG2_DEXNAV_UI,
  BG3_DEXNAV_BACKGROUNDS,
  BG_DEXNAV_COUNT,
};

enum DexnavWindows
{
  WIN_DEXNAV_HEADER,
  WIN_DEXNAV_INTERFACE_INSIGHT,
  WIN_DEXNAV_INTERFACE_MON_INFO,
  WIN_DEXNAV_INTERFACE_STREAK,
  WIN_DEXNAV_HELP_BAR,
};

enum DexnavSpriteIds
{
  DEXNAV_SPRITEIDS_COUNT,
};

enum DexnavFontColors
{
  DEXNAV_FONT_COLOR_BLACK,
  DEXNAV_FONT_COLOR_WHITE,
  DEXNAV_FONT_COLOR_COUNT,
};

#define FONT_DEXNAV_HELPBAR FONT_NORMAL

#endif // GUARD_CONSTANTS_UI_DEXNAV_H
