#ifndef GUARD_MAP_SYSTEM_CONSTANTS_MENU_H
#define GUARD_MAP_SYSTEM_CONSTANTS_MENU_H

enum FareVariables
{
    FARE_BASE,
    FARE_DISTANCE,
    FARE_TYPE_COUNT,
};

enum LocationType {
    LOCATION_NONE,
    LOCATION_NOT_VISITED,
    LOCATION_VISITED,
};

enum MapModes {
    MAP_MODE_DEFAULT,
    MAP_MODE_TAXI,
    MAP_MODE_FLY,
    MAP_MODE_TROLLEY,
    MAP_MODE_COUNT,
};

enum WindowIds
{
    WINDOW_HEADER_TEXT,
    WINDOW_FOOTER_TEXT,
    WINDOW_L2_RIGHT_SIDE_TEXT,
    WINDOW_L2_LEFT_SIDE_TEXT,
};

enum Colors
{
    FONT_MAP_BLACK,
    FONT_MAP_WHITE,
    FONT_MAP_RED,
    FONT_MAP_BLUE,
};

enum {
    TAG_CURSOR,
    TAG_PLAYER_ICON,
    TAG_FLY_ICON,
    TAG_CURSOR_TOOLTIP_LOC_STATE,
};

enum POIShape { // These are the possible Gray POI Shapes mapped to their Animation Number for the GrayPOI sprite
    POI_SMALL_SQUARE,
    POI_LARGE_RECT,
    POI_SMALL_RECT_CIRCLE,
    POI_LARGE_SQUARE_CIRCLE,
    POI_SMALL_VERT_RECT,
    POI_LARGE_SQUARE,
};

enum GrayPOILocations { // Locations which have a gray POI sprite for them
    GRAY_POI_LEAVERRA_FOREST,
    GRAY_POI_ESPULEE_OUTSKIRTS,
    GRAY_POI_CHASILLA,
    GRAY_POI_PETAROSA_BOROUGH,
    GRAY_POI_CRESALTA_VISTA,
    GRAY_POI_TORA_TOWN,
    GRAY_POI_HODOU_CITY,
    GRAY_POI_TIRABUDIN_PLACE,
    GRAY_POI_QIU_VILLAGE,
    GRAY_POI_CURENO_PORT,
    GRAY_POI_CUCUNO_TOWN,
    GRAY_POI_HALERBA_CITY,
    GRAY_POI_HALAI_ISLAND,
    GRAY_POI_OROLAND,
    GRAY_POI_IRISINA_TOWN,
    GRAY_POI_CAPHE_CITY,
    GRAY_POI_MERMEREZA_CITY,
    GRAY_POI_PERLACIA_CITY,
    GRAY_POI_COUNT,
};

#define FARE_DISCOUNT_ARRIBA_NUMERATOR   10
#define FARE_DISCOUNT_ARRIBA_DENOMINATOR 100

#define FARE_BASE_TAXI 150
#define FARE_DISTANCE_TAXI 100

#define FARE_BASE_ARRIBA 300
#define FARE_DISTANCE_ARRIBA 250

#define FARE_BASE_TROLLEY 5
#define FARE_DISTANCE_TROLLEY 0

#define FARE_BASE_FLY 0
#define FARE_DISTANCE_FLY FARE_BASE_FLY

#define MAP_MODE_ARRIBA MAP_MODE_DEFAULT

#define FONT_MAP_HELP_BAR FONT_NARROW

#endif // GUARD_MAP_SYSTEM_CONSTANTS_MENU_H
