#ifndef GUARD_CONSTANTS_MAINMENU_H
#define GUARD_CONSTANTS_MAINMENU_H

#define FONT_MAINMENU_HEADER FONT_SMALL_NARROW
#define FONT_MAINMENU_HELP_BAR FONT_MAINMENU_HEADER
#define FONT_MAINMENU_OPTIONS FONT_OUTLINED
#define FONT_MAINMENU_MESSAGE FONT_NORMAL

enum MainMenuWindowFontColors
{
    MAINMENU_FONT_COLOR_BLACK,
    MAINMENU_FONT_COLOR_WHITE,
    MAINMENU_FONT_COLOR_WHITE_MENU,
    MAINMENU_FONT_COLOR_WHITE_HEADER,
};

enum MainMenuWindows
{
    MAINMENU_WINDOW_HEADER,
    MAINMENU_WINDOW_INFO_BAR,
    MAINMENU_WINDOW_STATS,
    MAINMENU_WINDOW_OPTIONS,
    MAINMENU_WINDOW_HELP_BAR,
    MAINMENU_WINDOW_BACKGROUND_OPTIONS,
    MAINMENU_WINDOW_ERASE_BACKGROUND,
    MAINMENU_WINDOW_COUNT,
};

#define MAINMENU_WINDOW_ERASE MAINMENU_WINDOW_STATS

enum MainMenuBackgrounds
{
    BG0_MAINMENU_TEXT,
    BG1_MAINMENU_STATS,
    BG2_MAINMENU_SHADOW,
    BG3_MAINMENU_GENERAL,
    BG_MAINMENU_COUNT,
};

enum MainMenuContinueMenuOptions
{
    MAINMENU_CONTINUE,
    MAINMENU_NEWGAME,
    MAINMENU_ERASE,
    MAINMENU_OPTIONS,
    MAINMENU_MENU_COUNT,
};

enum MainMenuTrainerCardDisplay
{
    TRAINERCARD_MONEY_TITLE,
    TRAINERCARD_MONEY_VALUE,
    TRAINERCARD_COUNT,
    TRAINERCARD_BP_TITLE = TRAINERCARD_COUNT,
    TRAINERCARD_BP_VALUE,
    TRAINERCARD_TOTAL_COUNT,
};

enum MainMenuEraseMenuOptions
{
    MAINMENU_ERASE_NO,
    MAINMENU_ERASE_YES,
    MAINMENU_ERASE_COUNT,
};

enum MainMenuCompletionStats
{
    MAINMENU_COMPLETION_STORY,
    MAINMENU_COMPLETION_TRAINER,
    MAINMENU_COMPLETION_POKEDEX,
    MAINMENU_COMPLETION_QUESTS,
    MAINMENU_COMPLETION_GYMS,
    MAINMENU_COMPLETION_OVERALL,
    MAINMENU_COMPLETION_STAT_COUNT,
};

#define PAL_SLOT_MAINMENU_UI BG_PLTT_ID(0)
#define PAL_SLOT_MAINMENU_TEXT BG_PLTT_ID(15)

#define PAL_MAINMENU_UI_SPRITES 123
#define MAINMENU_SPRITETAG 2512

enum MainMenuSpritesTags
{
    MAINMENU_SPRITE_TIME,
    MAINMENU_SPRITE_MENUCURSOR,
    MAINMENU_SPRITE_COMPLETION,
};

enum MainMenuModes
{
    MAINMENU_MODE_CONTINUE,
    MAINMENU_MODE_ERASE,
    MAINMENU_MODE_TRAINER_CARD,
    MAINMENU_MODE_COUNT
};

#define MAINMENU_PALTAG_TIME (PAL_MAINMENU_UI_SPRITES + MAINMENU_SPRITE_TIME)
#define MAINMENU_GFXTAG_TIME (MAINMENU_SPRITETAG + MAINMENU_SPRITE_TIME)
#define MAINMENU_GFXTAG_MENUCURSOR (MAINMENU_SPRITETAG + MAINMENU_SPRITE_MENUCURSOR)
#define MAINMENU_GFXTAG_COMPLETION (MAINMENU_SPRITETAG + MAINMENU_SPRITE_COMPLETION)

#define MAINMENU_PLAYTIME_RIGHT_BUFFER 220
#define MAINMENU_DIFFICULTY_RIGHT_BUFFER 231
#define MAINMENU_STATS_HEADER_BOTTOM_PADDING 2
#define MAINMENU_STATS_STAT_BOTTOM_PADDING 4
#define MAINMENU_STATS_STAT_RIGHT_PADDING 56
#define MAINMENU_OPTION_BOTTOM_PADDING 5

#define MAINMENU_OPTIONS_BACKGROUND_LEFT_MARGIN (TILE_WIDTH * 16)
#define MAINMENU_OPTIONS_ERASE_BACKGROUND_LEFT_MARGIN (TILE_WIDTH * 7)
#define MAINMENU_OPTIONS_TRAINER_CARD_LEFT_MARGIN (TILE_WIDTH * 12)
#define MAINMENU_OPTIONS_CURSOR_Y_POSITION 34
#define MAINMENU_OPTIONS_ERASE_CURSOR_Y_POSITION (MAINMENU_OPTIONS_CURSOR_Y_POSITION + (MAINMENU_OPTIONS_CURSOR_BOTTOM_PADDING * 2))
#define MAINMENU_OPTIONS_CURSOR_BOTTOM_PADDING 20
#define MAINMENU_OPTIONS_CURSOR_X_POSITION 57
#define MAINMENU_OPTIONS_ERASE_CURSOR_X_POSITION (MAINMENU_OPTIONS_CURSOR_X_POSITION + 72)

#define POKEMON_ICON_FRAME_COUNT  4
#define POKEMON_ICON_FRAME_SCROLL (32 * 8 / 2)
#define POKEMON_ICON_SPRITE_SIZE  (32 * 16 / 2)

#endif // GUARD_CONSTANTS_MAINMENU_H
