#ifndef GUARD_CONSTANTS_PRESTO_H
#define GUARD_CONSTANTS_PRESTO_H

// Buy Icon Sprite -------------------------------------------------------------------------------------------------------
#define TAG_PRESTO_INTERFACE 0 // Tile and pal tag used for all interface sprites.
#define PAL_UI_SPRITES 0

enum PrestoSpriteIDs
{
    SPRITE_BUY_ICON_ID,
    SPRITE_UP_ARROW,
    SPRITE_DOWN_ARROW,
    SPRITE_LEFT_ARROW,
    SPRITE_RIGHT_ARROW,
    SPRITE_UP_ARROW_SMALL,
    SPRITE_DOWN_ARROW_SMALL,
    NUM_PRESTO_SPRITES,
};

enum {
    GFXTAG_BUY_ICON = TAG_PRESTO_INTERFACE,
    GFXTAG_UP_ARROW,
    GFXTAG_DOWN_ARROW,
    GFXTAG_LEFT_ARROW,
    GFXTAG_RIGHT_ARROW,
    GFXTAG_UP_ARROW_SMALL,
    GFXTAG_DOWN_ARROW_SMALL,
};

#define NUM_ITEMS_PER_ROW 5
#define NUM_MAX_ICONS_ROWNS_ON_SCREEN 5
#define NUM_MAX_ROWNS_ON_SCREEN 3
#define NUM_MAX_ITEMS_PER_ROW 150
#define NUM_RECOMMENDED_ITEMS 10

#define MAX_ITEM_SPRITES 16
#define FIRST_ITEM_SPRITE_ID NUM_PRESTO_SPRITES

#define PRESTO_FEE_BASE_DRONE 50
#define PRESTO_FEE_RECCOMENDED_BOOST 2
#define PRESTO_FEE_SHARP_RISE_DISCOUNT 30

#endif // GUARD_CONSTANTS_PRESTO_H
