#ifndef GUARD_CONSTANTS_UI_POKEDEX_H
#define GUARD_CONSTANTS_UI_POKEDEX_H

#include "ui_pokedex.h"

enum
{
    BG0_POKEDEX_TEXT_CONTENT,
    BG1_POKEDEX_STATS_CURSOR,
    BG2_POKEDEX_LIST_BG,
    BG3_POKEDEX_BACKGROUND,
    BG_POKEDEX_COUNT,
};

#define FONT_POKEDEX_HEADER_BAR FONT_SHORT
#define FONT_POKEDEX_SPECIES_GRID FONT_SMALL
#define FONT_POKEDEX_DEX_STATS FONT_SMALL
#define FONT_POKEDEX_HELP_BAR FONT_SMALL_NARROW
#define FONT_POKEDEX_METRICS FONT_NORMAL
#define FONT_POKEDEX_MENU FONT_SMALL_NARROW
#define FONT_POKEDEX_TYPE_FILTER FONT_SHORT_NARROW
#define FONT_POKEDEX_ALPHABET FONT_SMALL_NARROW
#define FONT_POKEDEX_FILTER_MOVE_LIST FONT_SMALL
#define FONT_POKEDEX_FILTER_MOVE_DESC FONT_SMALL
#define FONT_MOVES_LIST FONT_NORMAL
#define FONT_MOVES_DATA FONT_SMALL
#define FONT_MOVES_DESC FONT_NORMAL
#define FONT_MOVES_LEARN_METHOD FONT_SHORT
#define FONT_MOVES_TYPE_NAME FONT_SMALL_NARROW
#define FONT_MOVES_PARENTS FONT_SMALL_NARROWER
#define FONT_EVOLUTION_DESC FONT_SMALL
#define FONT_EVOLUTION_LIST_HEADER FONT_SMALL
#define FONT_EVOLUTION_LIST FONT_NORMAL
#define FONT_ABILITY_DESC FONT_NORMAL
#define FONT_STATS_DESC FONT_SMALL
#define FONT_SPECIES_FLAVOR FONT_SMALL
#define FONT_LEGEND FONT_SMALL
#define FONT_INFO_SPRITE_LABEL FONT_SMALL

enum
{
    POKEDEX_FONT_COLOR_BLACK,
    POKEDEX_FONT_COLOR_WHITE,
    POKEDEX_FONT_COLOR_MENU,
    POKEDEX_FONT_COLOR_COUNT
};

#define POKEDEX_PALETTE_UI 0
#define PAL_SLOT_POKEDEX_UI BG_PLTT_ID(POKEDEX_PALETTE_UI)
#define POKEDEX_TYPE_WINDOW_COLOR_ADDRESS (PAL_SLOT_POKEDEX_UI + 10)
#define POKEDEX_INFO_TYPE_WINDOW_COLOR_ADDRESS (PAL_SLOT_POKEDEX_UI + 10)
#define POKEDEX_STAT_HIGHLIGHT_PALETTE_ADDRESS POKEDEX_INFO_TYPE_WINDOW_COLOR_ADDRESS
#define POKEDEX_PALETTE_TEXT 15
#define PAL_SLOT_POKEDEX_TEXT BG_PLTT_ID(POKEDEX_PALETTE_TEXT)
#define PAL_POKEDEX_UI_SPRITES 123
#define PAL_POKEDEX_UI_FOOTPRINT_SPRITES 124
#define PAL_SLOT_MON_SPRITE 11
#define PAL_SLOT_MON_SPRITE_2 12
#define PAL_SLOT_MON_TYPE 13

#define POKEDEX_PALETTE_UI_WHITE 4
#define POKEDEX_PALETTE_UI_TRANSPERANT 0
#define POKEDEX_PALETTE_UI_DARK_GREY 1

enum PokedexPages
{
    POKEDEX_PAGE_SPECIES_LIST,
    POKEDEX_PAGE_INFORMATION,
    POKEDEX_PAGE_STATS,
    POKEDEX_PAGE_EVOLUTION,
    POKEDEX_PAGE_FORMS,
    POKEDEX_PAGE_LOCATION,
    POKEDEX_PAGE_MOVES,
    POKEDEX_PAGE_WEAKNESSES,
    POKEDEX_PAGE_FILTER,
    POKEDEX_PAGE_COUNT,
};

#define SPECIES_MENU_COUNT (POKEDEX_PAGE_COUNT - 2)

#define tTargetPageId data[14]
#define tPageDelta data[15]

enum PokedexPageWindows
{
    POKEDEX_PAGE_WINDOW_HEADER,
    POKEDEX_PAGE_WINDOW_MON_DATA,
    POKEDEX_PAGE_WINDOW_GETSEEN_DATA,
    POKEDEX_PAGE_WINDOW_GRID,
    POKEDEX_PAGE_WINDOW_HELP_BAR,
    POKEDEX_PAGE_WINDOW_COUNT,
};

enum PokedexPageMovesWindows
{
    PAGE_MOVES_WINDOW_HEADER,
    PAGE_MOVES_WINDOW_LEARN_METHOD,
    PAGE_MOVES_WINDOW_MOVES_DATA,
    PAGE_MOVES_WINDOW_MOVES_LIST,
    PAGE_MOVES_WINDOW_MOVES_DESC,
    PAGE_MOVES_WINDOW_FOOTER,
    PAGE_MOVES_WINDOW_COUNT,
};

enum PokedexPageEvolutionWindows
{
    PAGE_EVOLUTION_WINDOW_HEADER,
    PAGE_EVOLUTION_WINDOW_SPECIES_DATA,
    PAGE_EVOLUTION_WINDOW_MON_LIST,
    PAGE_EVOLUTION_WINDOW_METHOD_DESC,
    PAGE_EVOLUTION_WINDOW_FOOTER,
    PAGE_EVOLUTION_WINDOW_COUNT,
};

enum PokedexPageStatsWindows
{
    PAGE_STATS_WINDOW_HEADER,
    PAGE_STATS_WINDOW_SPECIES_DATA,
    PAGE_STATS_WINDOW_ABILITIES_LIST,
    PAGE_STATS_WINDOW_ABILITIES_DESC,
    PAGE_STATS_WINDOW_FOOTER,
    PAGE_STATS_WINDOW_COUNT,
};

enum PokedexPageInformationWindows
{
    PAGE_INFORMATION_WINDOW_HEADER,
    PAGE_INFORMATION_WINDOW_DATA,
    PAGE_INFORMATION_WINDOW_SPRITES,
    PAGE_INFORMATION_WINDOW_FLAVOR,
    PAGE_INFORMATION_WINDOW_FOOTER,
    PAGE_INFORMATION_WINDOW_COUNT,
};

enum PokedexPageWeaknessesWindows
{
    PAGE_WEAKNESSES_WINDOW_HEADER,
    PAGE_WEAKNESSES_WINDOW_TYPES,
    PAGE_WEAKNESSES_WINDOW_FOOTER,
    PAGE_WEAKNESSES_WINDOW_COUNT,
};

enum PokedexPageLocationWindows
{
    PAGE_LOCATION_WINDOW_HEADER,
    PAGE_LOCATION_WINDOW_FOOTER,
    PAGE_LOCATION_WINDOW_COUNT,
};

#define POKEDEX_PAGE_STRING_LENGTH 500

enum SpeciesListColumns
{
    SPECIES_LIST_COLUMN_0,
    SPECIES_LIST_COLUMN_1,
    SPECIES_LIST_COLUMN_2,
    SPECIES_LIST_COLUMN_3,
    NUM_SPECIES_LIST_COLUMNS,
};

enum SpeciesListRows
{
    SPECIES_LIST_ROW_0,
    SPECIES_LIST_ROW_1,
    SPECIES_LIST_ROW_2,
    NUM_SPECIES_LIST_ROWS,
};

#define NUM_MONS_ON_SCREEN (NUM_SPECIES_LIST_ROWS * NUM_SPECIES_LIST_COLUMNS)
#define SPECIES_LIST_ROW_HEIGHT 32
#define SPECIES_LIST_VERTICAL_OFFSET (((PARTY_HEIGHT /  4) *  3) + 5)
#define POKEDEX_SPECIESLIST_NUMDESC_LENGTH 30
#define POKEDEX_SPECIESLIST_DATA_WIDTH 80
#define POKEDEX_SPECIES_LIST_FRAME_BASE_TILE 370

#define MIN_POKEDEX_SCROLLBAR_Y 22
#define MAX_POKEDEX_SCROLLBAR_Y 120
#define MOVEABLE_AREA_POKEDEX_SCROLLBAR (MAX_POKEDEX_SCROLLBAR_Y - MIN_POKEDEX_SCROLLBAR_Y)

enum PokedexSpriteTags
{
    POKEDEX_SPRITETAG_SPECIES_LIST_CURSOR,
    POKEDEX_SPRITETAG_SPECIES_LIST_SCROLLBAR,
    POKEDEX_SPRITETAG_SPECIES_LIST_MON,
    POKEDEX_SPRITETAG_SPECIES_LIST_MON_SHINY,
    POKEDEX_SPRITETAG_SPECIES_LIST_TYPE_1,
    POKEDEX_SPRITETAG_SPECIES_LIST_TYPE_2,
    POKEDEX_SPRITETAG_SPECIES_LIST_HEADER_ICON,
    POKEDEX_SPRITETAG_SPECIES_LIST_CAPTURE_INDICATOR,
    POKEDEX_SPRITETAG_SPECIES_LIST_UNCAUGHT_INDICATOR,
    POKEDEX_SPRITETAG_SPECIES_GRID_CAPTURE_INDICATOR,
    POKEDEX_SPRITETAG_SPECIES_GRID_UNCAUGHT_INDICATOR,
    POKEDEX_SPRITETAG_ALOLA_SPECIES_LIST_CAPTURE_INDICATOR,
    POKEDEX_SPRITETAG_ALOLA_SPECIES_LIST_UNCAUGHT_INDICATOR,
    POKEDEX_SPRITETAG_ALOLA_SPECIES_GRID_CAPTURE_INDICATOR,
    POKEDEX_SPRITETAG_ALOLA_SPECIES_GRID_UNCAUGHT_INDICATOR,
    POKEDEX_SPRITETAG_EDITPAGE_CHECK,
    POKEDEX_SPRITE_COUNT,
};

#define POKEDEX_CAPTURE_INDICATOR_X 7
#define POKEDEX_CAPTURE_INDICATOR_Y 19
#define POKEDEX_CAPTURE_INDICATOR_Y_SPECIES_DATA 124

#define POKEDEX_SPRITETAG_PAGE_MOVES_CATEGORY (POKEDEX_SPRITETAG_SPECIES_LIST_TYPE_2)
#define POKEDEX_SPRITETAG 2512
#define POKEDEX_GFXTAG_EDITPAGE_CHECK (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_EDITPAGE_CHECK)
#define POKEDEX_GFXTAG_SPECIES_LIST_CURSOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_CURSOR)
#define POKEDEX_GFXTAG_SPECIES_LIST_SCROLLBAR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_SCROLLBAR)
#define POKEDEX_GFXTAG_SPECIES_LIST_MON (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_MON)
#define POKEDEX_GFXTAG_SPECIES_LIST_TYPES (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_TYPES)
#define POKEDEX_GFXTAG_SPECIES_LIST_HEADER_ICON (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_HEADER_ICON)
#define POKEDEX_GFXTAG_SPECIES_LIST_CAPTURE_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_CAPTURE_INDICATOR)
#define POKEDEX_GFXTAG_SPECIES_LIST_UNCAUGHT_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_LIST_UNCAUGHT_INDICATOR)
#define POKEDEX_GFXTAG_SPECIES_GRID_CAPTURE_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_GRID_CAPTURE_INDICATOR)
#define POKEDEX_GFXTAG_SPECIES_GRID_UNCAUGHT_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_SPECIES_GRID_UNCAUGHT_INDICATOR)
#define POKEDEX_GFXTAG_ALOLA_SPECIES_LIST_CAPTURE_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_ALOLA_SPECIES_LIST_CAPTURE_INDICATOR)
#define POKEDEX_GFXTAG_ALOLA_SPECIES_LIST_UNCAUGHT_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_ALOLA_SPECIES_LIST_UNCAUGHT_INDICATOR)
#define POKEDEX_GFXTAG_ALOLA_SPECIES_GRID_CAPTURE_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_ALOLA_SPECIES_GRID_CAPTURE_INDICATOR)
#define POKEDEX_GFXTAG_ALOLA_SPECIES_GRID_UNCAUGHT_INDICATOR (POKEDEX_SPRITETAG + POKEDEX_SPRITETAG_ALOLA_SPECIES_GRID_UNCAUGHT_INDICATOR)

#define TAG_TERA_TYPE 30009
#define TAG_CATEGORY 30007

#define POKEDEX_SPRITE_ICON_SIZE (16 * 16)
#define POKEDEX_SPRITETAG_FOOTPRINT 1544
#define NUM_FOOTPRINT_TILES 4
#define FOOTPRINT_COLOR_IDX  15

#define POKEDEX_PARENT_ARROW_GFXTAG 1288
#define POKEDEX_PARENT_ARROW_PADDING 128

enum PokedexMovesArrowGfxTags
{
    POKEDEX_PARENT_ARROW_UP_GFXTAG,
    POKEDEX_PARENT_ARROW_DOWN_GFXTAG,
    POKEDEX_PARENT_ARROW_COUNT_GFXTAG,
};
#define POKEDEX_PARENT_ARROW_SPRITE_START POKEDEX_SPRITETAG_SPECIES_LIST_CAPTURE_INDICATOR

enum
{
    MON_HAS_EVOLUTION,
    MON_HAS_FORMS,
    MON_RELATIONSHIP_COUNT,
};

enum PokedexEvolution
{
    EVOLUTION_NULL,
    MON_CAN_EVOLVE,
    MON_HAS_EVOLVED_STILL_CAN,
    MON_FULLY_EVOLVED,
    NO_EVOLUTION,
    EVOLUTION_STAGE_COUNT,
};

enum PokedexEvolutionCheckMode
{
    CHECK_CAN_EVOLVE,
    CHECK_HAS_EVOLVED,
    CHECK_NO_EVOLTION,
};

enum PokedexFamilyAttributes
{
    POKEDEX_EVOLUTION_ATTRIBUTE_ORIGINAL_SPECIES,
    POKEDEX_EVOLUTION_ATTRIBUTE_METHOD,
    POKEDEX_EVOLUTION_ATTRIBUTE_TARGET_SPECIES,
    POKEDEX_EVOLUTION_ATTRIBUTE_ARG1,
    POKEDEX_EVOLUTION_ATTRIBUTE_ARG2,
    POKEDEX_EVOLUTION_ATTRIBUTE_ARG3,
    POKEDEX_EVOLUTION_ATTRIBUTE_COUNT,
};

enum EvolutionListRow
{
    EVOLUTION_LIST_ROW_0,
    EVOLUTION_LIST_ROW_1,
    EVOLUTION_LIST_ROW_2,
    EVOLUTION_LIST_ROW_3,
    EVOLUTION_LIST_ROW_4,
    NUM_EVOLUTIONS_LIST_ROWS,
};

#define EVOLUTION_LIST_SCREEN_BUFFER (NUM_EVOLUTIONS_LIST_ROWS/ 2)
#define MIN_EVOLUTION_PAGE_SCROLLBAR_Y 22
#define MAX_EVOLUTION_PAGE_SCROLLBAR_Y 70
#define MOVEABLE_AREA_EVOLUTION_PAGE_SCROLLBAR (MAX_EVOLUTION_PAGE_SCROLLBAR_Y - MIN_EVOLUTION_PAGE_SCROLLBAR_Y)
#define EVO_FORM_LIST_CURSOR_PADDING 16
#define EVO_FORM_LIST_CURSOR_WIDTH 80
#define EVO_FORM_LIST_CURSOR_HEIGHT 16
#define SPECIES_LOCKED 65535
#define SPECIES_ANY (SPECIES_LOCKED - 1)
#define MAX_NUM_FORMS_EVOLUTIONS 65 // Alcremie has 65 forms

enum PokedexPageMoveData
{
    POKEDEX_PAGE_MOVE_DATA_PP,
    POKEDEX_PAGE_MOVE_DATA_POWER,
    POKEDEX_PAGE_MOVE_DATA_CATEGORY,
    POKEDEX_PAGE_MOVE_DATA_ACC,
    POKEDEX_PAGE_MOVE_DATA_COUNT,
};

enum MoveListRow
{
    MOVE_LIST_ROW_0,
    MOVE_LIST_ROW_1,
    MOVE_LIST_ROW_2,
    MOVE_LIST_ROW_3,
    MOVE_LIST_ROW_4,
    NUM_MOVES_LIST_ROWS,
};

enum MoveLearnMethods
{
    METHOD_LEVEL,
    METHOD_EGG,
    METHOD_MACHINE,
    METHOD_LEVEL_EGG,
    METHOD_EGG_MACHINE,
    METHOD_MACHINE_LEVEL,
    METHOD_ALL,
    METHOD_COUNT,
};

#define METHOD_EGG_LEVEL METHOD_LEVEL_EGG
#define METHOD_MACHINE_EGG METHOD_EGG_MACHINE
#define METHOD_LEVEL_MACHINE METHOD_MACHINE_LEVEL

#define MOVES_LIST_SCREEN_BUFFER (NUM_MOVES_LIST_ROWS / 2)
#define MOVE_CURSOR_MAX_Y_POSITION (NUM_MOVES_LIST_ROWS - 1)
#define MIN_MOVES_PAGE_SCROLLBAR_Y 22
#define MAX_MOVES_PAGE_SCROLLBAR_Y 83
#define MOVEABLE_AREA_MOVES_PAGE_SCROLLBAR (MAX_MOVES_PAGE_SCROLLBAR_Y - MIN_MOVES_PAGE_SCROLLBAR_Y)
#define MOVE_LIST_CURSOR_PADDING 15
#define MOVE_LIST_CURSOR_WIDTH 88
#define MOVE_LIST_CURSOR_HEIGHT 14

#define UI_MOVES_COUNT_TOTAL (EGG_MOVES_ARRAY_COUNT + MAX_LEVEL_UP_MOVES + NUM_TECHNICAL_MACHINES)
#define MAX_MOVES_PER_LETTER MOVES_COUNT
#define MAX_ABILITIES_PER_LETTER ABILITIES_COUNT
#define POKEDEX_EDIT_MOVE_LIST_MAX_MOVES (POKEDEX_EDIT_MOVE_MAX_COLUMN + 1) * (POKEDEX_EDIT_MOVE_MAX_ROW + 1)
#define POKEDEX_PAGE_MOVES_LEARN_ICON_RIGHT_PADDING 10

enum PokedexFilters {
    POKEDEX_FILTER_EVOLUTION,
    POKEDEX_FILTER_STATS,
    POKEDEX_FILTER_COLOR,
    POKEDEX_FILTER_EGG,
    POKEDEX_FILTER_TYPES,
    POKEDEX_FILTER_ABILITY,
    POKEDEX_FILTER_MOVES,
    POKEDEX_FILTER_COUNT,
};

enum PokedexFilterList
{
    FILTER_LIST_TYPE1,
    FILTER_LIST_TYPE2,
    FILTER_LIST_HP,
    FILTER_LIST_ATK,
    FILTER_LIST_DEF,
    FILTER_LIST_SPEED,
    FILTER_LIST_SPATK,
    FILTER_LIST_SPDEF,
    FILTER_LIST_EGG1,
    FILTER_LIST_EGG2,
    FILTER_LIST_COLOR,
    FILTER_LIST_MOVE1,
    FILTER_LIST_MOVE2,
    FILTER_LIST_MOVE3,
    FILTER_LIST_MOVE4,
    FILTER_LIST_ABILITY,
    FILTER_LIST_EVOLUTION,
    FILTER_LIST_COUNT,
};

enum FilterEditPageModes
{
    FILTER_MODE_NONE,
    FILTER_MODE_ALPHABET,
    FILTER_MODE_OPTIONSELECT,
    FILTER_MODE_MANAGEFILTER,
    FILTER_MODE_COUNT,
};

enum PokedexFilterAlphabet
{
    POKEDEX_FILTER_ALPHABET_ALL,
    POKEDEX_FILTER_ALPHABET_A,
    POKEDEX_FILTER_ALPHABET_B,
    POKEDEX_FILTER_ALPHABET_C,
    POKEDEX_FILTER_ALPHABET_D,
    POKEDEX_FILTER_ALPHABET_E,
    POKEDEX_FILTER_ALPHABET_F,
    POKEDEX_FILTER_ALPHABET_G,
    POKEDEX_FILTER_ALPHABET_H,
    POKEDEX_FILTER_ALPHABET_I,
    POKEDEX_FILTER_ALPHABET_J,
    POKEDEX_FILTER_ALPHABET_K,
    POKEDEX_FILTER_ALPHABET_L,
    POKEDEX_FILTER_ALPHABET_M,
    POKEDEX_FILTER_ALPHABET_N,
    POKEDEX_FILTER_ALPHABET_O,
    POKEDEX_FILTER_ALPHABET_P,
    POKEDEX_FILTER_ALPHABET_Q,
    POKEDEX_FILTER_ALPHABET_R,
    POKEDEX_FILTER_ALPHABET_S,
    POKEDEX_FILTER_ALPHABET_T,
    POKEDEX_FILTER_ALPHABET_U,
    POKEDEX_FILTER_ALPHABET_V,
    POKEDEX_FILTER_ALPHABET_W,
    POKEDEX_FILTER_ALPHABET_X,
    POKEDEX_FILTER_ALPHABET_Y,
    POKEDEX_FILTER_ALPHABET_Z,
    POKEDEX_FILTER_ALPHABET_COUNT,
};

enum
{
    FILTER_LIST_ROW_0,
    FILTER_LIST_ROW_1,
    FILTER_LIST_ROW_2,
    FILTER_LIST_ROW_3,
    NUM_FILTER_LIST_ROWS,
};

enum FilterManageListRows
{
    FILTER_MANAGE_LIST_ROW_0,
    FILTER_MANAGE_LIST_ROW_1,
    FILTER_MANAGE_LIST_ROW_2,
    FILTER_MANAGE_LIST_ROW_3,
    NUM_FILTER_MANAGE_LIST_ROWS,
};

#define FILTER_LIST_PROPERTIES_WIDTH 221
#define FILTER_LIST_SCREEN_BUFFER (NUM_FILTER_LIST_ROWS / 2)

enum FilterPageWindows
{
    FILTER_PAGE_WINDOW_HEADER,
    FILTER_PAGE_WINDOW_FILTER_NAME_0,
    FILTER_PAGE_WINDOW_FILTER_PROPERTIES_0,
    FILTER_PAGE_WINDOW_FILTER_NAME_1,
    FILTER_PAGE_WINDOW_FILTER_PROPERTIES_1,
    FILTER_PAGE_WINDOW_FILTER_NAME_2,
    FILTER_PAGE_WINDOW_FILTER_PROPERTIES_2,
    FILTER_PAGE_WINDOW_FILTER_NAME_3,
    FILTER_PAGE_WINDOW_FILTER_PROPERTIES_3,
    FILTER_PAGE_WINDOW_HELP_BAR,
    FILTER_PAGE_WINDOW_COUNT,
};

enum FilterPageWindows_Type
{
    FILTER_PAGE_TYPE_WINDOW_HEADER,
    FILTER_PAGE_TYPE_WINDOW_COLUMN_1,
    FILTER_PAGE_TYPE_WINDOW_HELP_BAR,
    FILTER_PAGE_TYPE_WINDOW_COUNT,
};

enum FilterPageWindows_Move
{
    FILTER_PAGE_MOVE_WINDOW_HEADER,
    FILTER_PAGE_MOVE_WINDOW_LIST,
    FILTER_PAGE_MOVE_WINDOW_SELECTED_MOVES,
    FILTER_PAGE_MOVE_WINDOW_DESC,
    FILTER_PAGE_MOVE_WINDOW_HELP_BAR,
    FILTER_PAGE_MOVE_WINDOW_COUNT,
};

enum FilterPageWindows_List
{
    FILTER_PAGE_LIST_WINDOW_HEADER,
    FILTER_PAGE_LIST_WINDOW_LIST,
    FILTER_PAGE_LIST_WINDOW_HELP_BAR,
    FILTER_PAGE_LIST_WINDOW_COUNT,
};

enum editPageSpacing
{
    EDIT_PAGE_SPACING_HORIZONTAL_PADDING,
    EDIT_PAGE_SPACING_HORIZONTAL_MARGIN,
    EDIT_PAGE_SPACING_VERTICAL_PADDING,
    EDIT_PAGE_SPACING_VERTICAL_MARGIN,
    EDIT_PAGE_SPACING_MAX_COLUMN_WIDTH,
    EDIT_PAGE_SPACING_CURSOR_WIDTH,
    EDIT_PAGE_SPACING_CURSOR_PADDING,
    EDIT_PAGE_SPACING_CHECK_PADDING,
    EDIT_PAGE_SPACING_CHECK_MARGIN,
    EDIT_PAGE_SPACING_COUNT,
};

#define POKEDEX_EDIT_TYPE_MAX_COLUMN 2
#define POKEDEX_EDIT_TYPE_MAX_ROW 5
#define POKEDEX_EDIT_EGG_MAX_COLUMN 2
#define POKEDEX_EDIT_EGG_MAX_ROW 4
#define POKEDEX_EDIT_MOVE_MAX_COLUMN 1
#define POKEDEX_EDIT_MOVE_MAX_ROW 6
#define POKEDEX_EDIT_STAT_MAX_COLUMN 0
#define POKEDEX_EDIT_STAT_MAX_ROW 4
#define POKEDEX_EDIT_COLOR_MAX_COLUMN 1
#define POKEDEX_EDIT_COLOR_MAX_ROW 5
#define POKEDEX_EDIT_EVOLUTION_MAX_COLUMN 0
#define POKEDEX_EDIT_EVOLUTION_MAX_ROW 3

enum StatTierList
{
    STAT_TIER_NONE,
    STAT_TIER_D,
    STAT_TIER_C,
    STAT_TIER_B,
    STAT_TIER_A,
    STAT_TIER_S,
    STAT_TIER_COUNT,
};

#define POKEDEX_FILTER_HP_D_CEIL 41
#define POKEDEX_FILTER_HP_D_FLOOR (POKEDEX_FILTER_HP_D_CEIL - 1)
#define POKEDEX_FILTER_HP_C_CEIL 58
#define POKEDEX_FILTER_HP_C_FLOOR (POKEDEX_FILTER_HP_C_CEIL - 1)
#define POKEDEX_FILTER_HP_B_CEIL 77
#define POKEDEX_FILTER_HP_B_FLOOR (POKEDEX_FILTER_HP_B_CEIL - 1)
#define POKEDEX_FILTER_HP_A_CEIL 97
#define POKEDEX_FILTER_HP_A_FLOOR (POKEDEX_FILTER_HP_A_CEIL - 1)
#define POKEDEX_FILTER_ATK_D_CEIL 41
#define POKEDEX_FILTER_ATK_D_FLOOR (POKEDEX_FILTER_ATK_D_CEIL - 1)
#define POKEDEX_FILTER_ATK_C_CEIL 60
#define POKEDEX_FILTER_ATK_C_FLOOR (POKEDEX_FILTER_ATK_C_CEIL - 1)
#define POKEDEX_FILTER_ATK_B_CEIL 90
#define POKEDEX_FILTER_ATK_B_FLOOR (POKEDEX_FILTER_ATK_B_CEIL - 1)
#define POKEDEX_FILTER_ATK_A_CEIL 115
#define POKEDEX_FILTER_ATK_A_FLOOR (POKEDEX_FILTER_ATK_A_CEIL - 1)
#define POKEDEX_FILTER_DEF_D_CEIL 41
#define POKEDEX_FILTER_DEF_D_FLOOR (POKEDEX_FILTER_DEF_D_CEIL - 1)
#define POKEDEX_FILTER_DEF_C_CEIL 57
#define POKEDEX_FILTER_DEF_C_FLOOR (POKEDEX_FILTER_DEF_C_CEIL - 1)
#define POKEDEX_FILTER_DEF_B_CEIL 85
#define POKEDEX_FILTER_DEF_B_FLOOR (POKEDEX_FILTER_DEF_B_CEIL - 1)
#define POKEDEX_FILTER_DEF_A_CEIL 103
#define POKEDEX_FILTER_DEF_A_FLOOR (POKEDEX_FILTER_DEF_A_CEIL - 1)
#define POKEDEX_FILTER_SPATK_D_CEIL 40
#define POKEDEX_FILTER_SPATK_D_FLOOR (POKEDEX_FILTER_SPATK_D_CEIL - 1)
#define POKEDEX_FILTER_SPATK_C_CEIL 53
#define POKEDEX_FILTER_SPATK_C_FLOOR (POKEDEX_FILTER_SPATK_C_CEIL - 1)
#define POKEDEX_FILTER_SPATK_B_CEIL 81
#define POKEDEX_FILTER_SPATK_B_FLOOR (POKEDEX_FILTER_SPATK_B_CEIL - 1)
#define POKEDEX_FILTER_SPATK_A_CEIL 105
#define POKEDEX_FILTER_SPATK_A_FLOOR (POKEDEX_FILTER_SPATK_A_CEIL - 1)
#define POKEDEX_FILTER_SPDEF_D_CEIL 40
#define POKEDEX_FILTER_SPDEF_D_FLOOR (POKEDEX_FILTER_SPDEF_D_CEIL - 1)
#define POKEDEX_FILTER_SPDEF_C_CEIL 51
#define POKEDEX_FILTER_SPDEF_C_FLOOR (POKEDEX_FILTER_SPDEF_C_CEIL - 1)
#define POKEDEX_FILTER_SPDEF_B_CEIL 75
#define POKEDEX_FILTER_SPDEF_B_FLOOR (POKEDEX_FILTER_SPDEF_B_CEIL - 1)
#define POKEDEX_FILTER_SPDEF_A_CEIL 95
#define POKEDEX_FILTER_SPDEF_A_FLOOR (POKEDEX_FILTER_SPDEF_A_CEIL - 1)
#define POKEDEX_FILTER_SPEED_D_CEIL 35
#define POKEDEX_FILTER_SPEED_D_FLOOR (POKEDEX_FILTER_SPEED_D_CEIL - 1)
#define POKEDEX_FILTER_SPEED_C_CEIL 48
#define POKEDEX_FILTER_SPEED_C_FLOOR (POKEDEX_FILTER_SPEED_C_CEIL - 1)
#define POKEDEX_FILTER_SPEED_B_CEIL 76
#define POKEDEX_FILTER_SPEED_B_FLOOR (POKEDEX_FILTER_SPEED_B_CEIL - 1)
#define POKEDEX_FILTER_SPEED_A_CEIL 98
#define POKEDEX_FILTER_SPEED_A_FLOOR (POKEDEX_FILTER_SPEED_A_CEIL - 1)

#define STAT_LIST_CURSOR_WIDTH 96
#define STAT_LIST_CURSOR_HEIGHT 16
#define STATS_ABILITY_DESC_LEFT_COLUMN_WIDTH 91
#define STATS_ABILITY_DESC_RIGHT_COLUMN_WIDTH 106

enum ParentsDisplayColumns
{
    POKEDEX_PARENT_COLUMN_0,
    POKEDEX_PARENT_COLUMN_1,
    POKEDEX_PARENT_COLUMN_COUNT,
};

enum ParentsDisplayRows
{
    POKEDEX_PARENT_ROW_0,
    POKEDEX_PARENT_ROW_1,
    POKEDEX_PARENT_ROW_2,
    POKEDEX_PARENT_ROW_COUNT,
};

#define MAX_MONS_PER_PARENT_PAGE (POKEDEX_PARENT_COLUMN_COUNT * POKEDEX_PARENT_ROW_COUNT)
#define MAX_NUM_PARENTS 78

#define PERCENT_FEMALE(percent) min(254, ((percent * 255) / 100))
#define MON_12_5_FEMALE 31
#define MON_87_5_FEMALE 223

#define POKEDEX_STATS_EVOLUTION_PAGE_SPRITE_X_STARTING 152
#define POKEDEX_STATS_EVOLUTION_PAGE_SPRITE_Y_STARTING 20
#define POKEDEX_STATS_EVOLUTION_PAGE_SPRITE_Y_PADDING 16

#define POKEDEX_STATS_FORMS_DESC_SCREEN_LINES 4

#define POKEDEX_STATS_CATEGORY_Y_STARTING 14
#define POKEDEX_STATS_STATS_TITLE_X_STARTING 85
#define POKEDEX_STATS_YIELD_TITLE_X_STARTING 118
#define POKEDEX_STATS_GENDER_STRING_X_STARTING 148
#define POKEDEX_STATS_YIELD_START_PADDING 12
#define POKEDEX_STATS_YIELD_X_PADDING 15
#define POKEDEX_STATS_YIELD_Y_PADDING 10
#define POKEDEX_STATS_VALUE_X_PADDING 30
#define POKEDEX_STATS_NUM_X_STARTING 18

#define POKEDEX_STATS_ITEM_ICON_X_STARTING 4
#define POKEDEX_STATS_ITEM_ICON_Y_MARGIN 3
#define POKEDEX_STATS_INFO_COLUMN_1_TITLE_X_STARTING 15
#define POKEDEX_STATS_INFO_COLUMN_1_TITLE_Y_STARTING 5
#define POKEDEX_STATS_INFO_ITEM_NAME_Y_STARTING POKEDEX_STATS_INFO_COLUMN_1_TITLE_Y_STARTING + 10
#define POKEDEX_STATS_INFO_ITEM_RARE_NAME_Y_STARTING POKEDEX_STATS_INFO_ITEM_NAME_Y_STARTING + 10
#define POKEDEX_STATS_INFO_EXP_YIELD POKEDEX_STATS_INFO_ITEM_RARE_NAME_Y_STARTING + 10
#define POKEDEX_STATS_INFO_FRIENDSHIP_Y_STARTING POKEDEX_STATS_INFO_EXP_YIELD + 10

#define POKEDEX_STATS_INFO_COLUMN_2_TITLE_X_STARTING 130
#define POKEDEX_STATS_INFO_EGG_CYCLES_Y_STARTING           POKEDEX_STATS_INFO_ITEM_RARE_NAME_Y_STARTING
#define POKEDEX_STATS_INFO_CATCH_RATE_Y_STARTING           POKEDEX_STATS_INFO_FRIENDSHIP_Y_STARTING
#define POKEDEX_STATS_INFO_GROWTH_RATE_Y_STARTING          POKEDEX_STATS_INFO_EXP_YIELD
#define POKEDEX_STATS_INFO_EGG_GROUPS_Y_STARTING           POKEDEX_STATS_INFO_ITEM_NAME_Y_STARTING
#define POKEDEX_STATS_INFO_EGG_GROUP_TITLE_Y_STARTING      POKEDEX_STATS_INFO_COLUMN_1_TITLE_Y_STARTING

#define POKEDEX_STATS_ABILIT_DESC_Y_STARTING 6
#define POKEDEX_STATS_ABILITY_TITLE_Y_STARTING 11
#define POKEDEX_STATS_ABILITY_LIST_Y_STARTING POKEDEX_STATS_ABILITY_TITLE_Y_STARTING + 14
#define POKEDEX_STATS_ABILITY_LIST_Y_MARGIN 16

#define POKEDEX_INFO_FOOTPRINT_TITLE_X_STARTING POKEDEX_INFO_MEASUREMENT_LABEL_X_STARTING
#define POKEDEX_INFO_FOOTPRINT_TITLE_Y_STARTING 20

#define POKEDEX_INFO_MEASUREMENT_LABEL_X_STARTING 2
#define POKEDEX_INFO_MEASUREMENT_VALUE_X_STARTING 39
#define POKEDEX_INFO_HEIGHT_Y_STARTING POKEDEX_INFO_FOOTPRINT_TITLE_Y_STARTING + 14
#define POKEDEX_INFO_WEIGHT_Y_STARTING POKEDEX_INFO_HEIGHT_Y_STARTING + 14

#define POKEDEX_INFO_TYPE_TITLE_X_STARTING POKEDEX_INFO_MEASUREMENT_LABEL_X_STARTING
#define POKEDEX_INFO_TYPE_NAME_X_STARTING 39
#define POKEDEX_INFO_TYPE_2_TITLE_Y_MARGIN 14
#define POKEDEX_INFO_TYPE_NAME_Y_STARTING 62
#define POKEDEX_INFO_TYPE_NAME_Y_MARGIN 14

#define POKEDEX_INFO_CATEGORYNAME_X 6
#define POKEDEX_INFO_MON_LABEL_X_STARTING 9
#define POKEDEX_INFO_MON_LABEL_Y_STARTING 21
#define POKEDEX_INFO_MON_SPRITE_MARGIN 69

#define POKEDEX_WEAKNESS_LABEL_X_STARING 61
#define POKEDEX_WEAKNESS_LABEL_X_MARGIN 80
#define POKEDEX_WEAKNESS_LABEL_MAX_WIDTH 60

#define POKEDEX_WEAKNESS_0_PERCENT   0
#define POKEDEX_WEAKNESS_25_PERCENT  1024
#define POKEDEX_WEAKNESS_50_PERCENT  2048
#define POKEDEX_WEAKNESS_100_PERCENT 4096
#define POKEDEX_WEAKNESS_200_PERCENT 8192
#define POKEDEX_WEAKNESS_400_PERCENT 16384

#endif // GUARD_CONSTANTS_UI_POKEDEX_H
