//VAR_STORYLINE_STATE //0x40FC

#define STORY_NOT_STARTED                        0
#define STORY_WEST_RESIDO_ONLY                   1
#define STORY_WEST_RESIDO_TASK_A                 2
#define STORY_WEST_RESIDO_TASK_B                 3
#define STORY_WEST_RESIDO_TASK_C                 4
#define STORY_WEST_RESIDO_TASK_D                 5
#define STORY_WEST_RESIDO_TASK_E                 6
#define STORY_WEST_RESIDO_TASK_F                 7
#define STORY_WEST_RESIDO_TASK_G                 8
#define STORY_WEST_RESIDO_COMPLETE               9
#define STORY_FERRY_FIXED                        10
#define STORY_DEFEAT_BAIYA_HALAI_ISLAND            11
#define STORY_DEFEAT_CHASILLA_PROTEST            12
#define STORY_DEFEAT_PUA                       13
#define STORY_COMPLETE_ARANTRAZ                  14
#define STORY_EAST_RESIDO_TASK_H                 15 //Baiya
#define STORY_EAST_RESIDO_TASK_I                 16 //Ami
#define STORY_EAST_RESIDO_TASK_J                 17 //BD
#define STORY_EAST_RESIDO_TASK_K                 18 //Dimu
#define STORY_EAST_RESIDO_TASK_L                 19 //Charlotte
#define STORY_EAST_RESIDO_TASK_M                 20 //Keiying
#define STORY_EAST_RESIDO_COMPLETE               21
#define STORY_CALLED_TO_CONSTRUCTION             22
#define STORY_DEFEATED_GARBODOR                  23
#define STORY_NEED_SLEEP_BEFORE_FRANK          24
#define STORY_ASSIGNED_FRANK_QUESTS            25
#define STORY_COMPLETED_NAVAL_BASE               26
#define STORY_START_CHAMPIONSHIP                 27
#define STORY_CHAMPIONSHIP_EXPLAINED             28
#define STORY_CHARLOTTE_WON_GROUP                29
#define STORY_READY_GROUP_STAGE                  30
#define STORY_GROUP_STATE_COMPLETE               31
#define STORY_SEMIFINAL_COMPLETE                 32
#define STORY_WATCH_SEMIFINAL                    33
#define STORY_READY_FINALS                       34
#define STORY_SAVE_FINALS                        35
#define STORY_WON_FINALS                         36
#define STORY_EXPLORE_ZENZU_ISLAND               37
#define STORY_SAVE_BAIYA_ZENZU_ISLAND              38
#define STORY_POST_BATTLE_BAIYA_ZENZU_ISLAND       39
#define STORY_BAIYA_EXPLAIN_RESTORATION            40
#define STORY_RESTORATION_1_COMPLETE             41
#define STORY_POST_YOU_REALIZE_WERE_EVIL         42
#define STORY_MORNING_OF_TIMELINE_SPLIT          43
#define STORY_START_FALSE_TIMELINE               44
#define STORY_1ST_THE_TIDE_TAKEDOWN               45
#define STORY_2ND_THE_TIDE_TAKEDOWN               46
#define STORY_3RD_THE_TIDE_TAKEDOWN               47
#define STORY_THE_TIDE_FINISHED                   48
#define STORY_SAVE_DIANTHA                       49
#define STORY_POST_DIANTHA                       50
#define STORY_CONGRATULATED_BY_LUCREZIA          51
#define STORY_RECIEVED_BAMBOO_STAR               52
#define STORY_BEGIN_LETS_FIX_IT                  53
#define STORY_MORNING_AFTER_TIMETRAVEL           99
#define STORY_START_TRUE_TIMELINE                100
#define STORY_DEFEATED_VIGRIM                   101
#define STORY_RECIVED_RAVE_INVITE                102
#define STORY_RAVE_OR_SPEECH_COMPLETE            103
#define STORY_RAVE_AND_SPEECH_COMPLETE           104
#define STORY_1ST_TAKEDOWN                       105
#define STORY_PRE_EARTHQUAKE                     106
#define STORY_POST_EARTHQUAKE                    107
#define STORY_POST_DYNAMAX_BOSS                  108
#define STORY_BEFORE_RAMESH_BREAKIN              109
#define STORY_WARP_TILE_ACCESSIBLE               110
#define STORY_EPILOGUE                           111
#define STORY_BEFORE_CREDITS                     112
#define STORY_CLEAR                              113

/*
enum StorylineVarsDefines
{
    STORY_WEST_RESIDO_ONLY,
    STORY_WEST_RESIDO_TASK_A,
    STORY_WEST_RESIDO_TASK_B,
    STORY_WEST_RESIDO_TASK_C,
    STORY_WEST_RESIDO_TASK_D,
    STORY_WEST_RESIDO_TASK_E,
    STORY_WEST_RESIDO_TASK_F,
    STORY_WEST_RESIDO_TASK_G,
    STORY_WEST_RESIDO_COMPLETE,
    STORY_FERRY_FIXED,
    STORY_DEFEAT_BAIYA_HALAI_ISLAND,
    STORY_DEFEAT_CHASILLA_PROTEST,
    STORY_DEFEAT_PUA,
    STORY_COMPLETE_ARANTRAZ,
    STORY_EAST_RESIDO_TASK_H,
    STORY_EAST_RESIDO_TASK_I,
    STORY_EAST_RESIDO_TASK_J,
    STORY_EAST_RESIDO_TASK_K,
    STORY_EAST_RESIDO_TASK_L,
    STORY_EAST_RESIDO_TASK_M,
    STORY_EAST_RESIDO_COMPLETE,
    STORY_CALLED_TO_CONSTRUCTION,
    STORY_DEFEATED_GARBODOR,
    STORY_NEED_SLEEP_BEFORE_FRANK,
    STORY_ASSIGNED_FRANK_QUESTS,
    STORY_COMPLETED_NAVAL_BASE,
    STORY_START_CHAMPIONSHIP,
    STORY_CHAMPIONSHIP_EXPLAINED,
    STORY_CHARLOTTE_WON_GROUP,
    STORY_READY_GROUP_STAGE,
    STORY_GROUP_STATE_COMPLETE,
    STORY_SEMIFINAL_COMPLETE,
    STORY_WATCH_SEMIFINAL,
    STORY_READY_FINALS,
    STORY_SAVE_FINALS,
    STORY_WON_FINALS,
    STORY_EXPLORE_ZENZU_ISLAND,
    STORY_SAVE_BAIYA_ZENZU_ISLAND,
    STORY_POST_BATTLE_BAIYA_ZENZU_ISLAND,
    STORY_BAIYA_EXPLAIN_RESTORATION,
    STORY_RESTORATION_1_COMPLETE,
    STORY_POST_YOU_REALIZE_WERE_EVIL,
    STORY_MORNING_OF_TIMELINE_SPLIT,
    STORY_START_FALSE_TIMELINE,
    STORY_1ST_THE_TIDE_TAKEDOWN,
    STORY_2ND_THE_TIDE_TAKEDOWN,
    STORY_3RD_THE_TIDE_TAKEDOWN,
    STORY_THE_TIDE_FINISHED,
    STORY_SAVE_DIANTHA,
    STORY_POST_DIANTHA,
    STORY_CONGRATULATED_BY_LUCREZIA,
    STORY_RECIEVED_BAMBOO_STAR,
    STORY_BEGIN_LETS_FIX_IT,
    STORY_MORNING_AFTER_TIMETRAVEL = 99,
    STORY_START_TRUE_TIMELINE,
    STORY_DEFEATED_VIGRIM,
    STORY_RECIVED_RAVE_INVITE,
    STORY_RAVE_OR_SPEECH_COMPLETE,
    STORY_RAVE_AND_SPEECH_COMPLETE,
    STORY_1ST_TAKEDOWN,
    STORY_PRE_EARTHQUAKE,
    STORY_POST_EARTHQUAKE,
    STORY_POST_DYNAMAX_BOSS,
    STORY_BEFORE_RAMESH_BREAKIN,
    STORY_WARP_TILE_ACCESSIBLE,
    STORY_CLEAR,
};
// PSF TODO convert these defines to this enum
*/

//VAR_PLAYER_HOME_STATE 0x4092
enum PlayerHomeState
{
    PLAYER_HOME_STATE_NONE,
    HAS_NOT_MET_CHARLOTTE,
    HAS_MET_CHARLOTTE,
    CHECKED_OUT_BEDROOM,
    POST_SWAGBAG,
    SLEPT_AFTER_SWAGBAG,
    FINISHED_1_1,
    POST_NAVAL_BASE_RAID,
    NEXT_DAY_CHAMPIONSHIP,
};

// VAR_GYM_1_STATE | VAR_GYM_3_STATE | VAR_GYM_4_STATE | VAR_GYM_5-STATE | VAR_GYM_6_STATE | VAR_GYM_7_STATE | VAR_GYM_8_STATE | VAR_GYM_2_STATE
#define GYM_PUZZLE_COMPLETE 1
#define GYM_LEADER_ON_BATTLEFIELD   2
#define GYM_SAVE_BEFORE_LEADER 3
#define GYM_DEFEATED_LEADER 4
#define GYM_EXPLAINED_BADGE_AND_TM  5
#define GYM_REMATCH_SAVE_BEFORE_LEADER 6
#define GYM_REMATCH_DEFEATED    7

//VAR_ROUTE10_STATE
#define HAS_NOT_MET_BAIYA  0
#define SAVED_BEFORE_BAIYA_ROUTE10   1
#define DEFEATED_BAIYA_ROUTE10   2

// VAR_SHARPRISESPIRE_CONFERENCE_STATE 0x40F9
#define DEFEATED_THIRD_LEADER 1
#define POST_WOW_YOURE_STRONG   2
#define START_THE_GANGS_ALL_HERE 3
#define POST_THE_GANGS_ALL_HERE 4
#define PRE_WELCOME_TO_THE_WAR_ROOM 5
#define POST_WELCOME_TO_THE_WAR_ROOM    6
#define PRE_YOU_REALIZE_WERE_EVIL_RIGHT 7
#define POST_YOU_REALIZE_WERE_EVIL_RIGHT    8
#define START_FALSE_TIMELINE    9
#define TRUE_RAID_START 10
#define TRUE_RAID_SAVE_CHARLOTTE   11

// VAR_ANBEH_BEND_STATE 0x4056
#define NOT_SEEN_CHARLOTTE_LOMBARD 0
#define SAVE_CHARLOTTE_LOMBARD 1
#define DEFEATED_CHARLOTTE_LOMBARD 2

//VAR_SHARPRISE_SPIRE_PRODUCTION_STATE 0x40FD
#define HAS_NOT_STEPPED_INTO_RAMESH_ROOM 0
#define STEPPED_INTO_RAMESH_ROOM   1
#define POST_ALWAYS_WATCHING_WAZOWSKI   2
#define RAMESH_NOT_IN_TOWER    3

//VAR_CURENO_PORT_STATE
#define PRE_HOW_DO_WE_GET_HOME 0
#define POST_HOW_DO_WE_GET_HOME 1

//VAR_BATTLE_8_STATE 0x4068
#define NOT_INTERACTED_BAIYA 0
#define SAVE_BAIYA_PINTILLONHOUSE  1
#define DEFEATED_BAIYA_PINTILLONHOUSE   2

//VAR_ARANTRAZ_STATE 0x409B
#define FIRST_ARRIVED_ARANTRAZ  1
#define BATTLED_TALA   2
#define BAIYA_SUMMONED_ARANTRAZ    3
#define POST_ARRIVE_ARANTRAZ 4
#define PRE_YOU_REALIZE_THEYRE_EVIL_RIGHT  5
#define POST_YOU_REALIZE_THEYRE_EVIL_RIGHT  6
#define LAST_CHANCE_TRUE_TIMELINE_START 7
#define START_TRUE_TIMELINE 8
#define PRE_SPEECHSPEECH    9
#define POST_SPEECHSPEECH   10

//VAR_FERRY_STATE 0x40A8
#define FERRY_DEFAULT 0
#define FERRY_HALAI_ISLAND_AVAILABLE 1
#define FERRY_ARANTRAZ_AVAILABLE    2
#define FERRY_ESPULEE_OUTSKIRTS_AVAILABLE 3

//VAR_ARANTRAZ_EXHIBIT_STATE
#define ARANTRAZ_EXHIBIT_NOT_STARTED 0
#define ARANTRAZ_EXHIBIT_START  1
#define ARANTRAZ_EXHIBIT_FINISH 2
#define ARANTRAZ_EXHIBIT_REWARD 3
#define ARANTRAZ_EXHIBIT_COMPLETE   4

//VAR_FERRYBUILDING_STATE 0x4070
#define CHIEF_LEFT_WAR_ROOM 1
#define PLAYER_READY_SURVIVAL_CHANCE_BATTLE 2
#define SAVE_SURVIVAL_CHANCE_BATTLE  3
#define DEFEATED_SURVIVAL_CHANCE_BATTLE 4

//VAR_HALAI_ISLAND_STATE 0x404E
#define HAS_NOT_ENCOUNTERED_BAIYA 0
#define SAVE_BAIYA_HALAI_ISLAND 1
#define DEFEATED_BAIYA_HALAI_ISLAND 2
#define START_SURVIVAL_CHANCE   3
#define POST_SURVIVAL_CHANCE    4
#define WHY_ARE_YOU_HELPING_THEM    5
#define SLEPT_AFTER_RAID    6
#define START_CHAMPIONSHIP_CLEAN_RAID   7
#define POST_EARTHQUAKE 8
#define START_EARTHQUAKE_RESCUE 9
#define POST_EARTHQUAKE_RESCUE  11
#define MEET_AT_ROUTE4   12
#define POST_THIS_ISNT_RANDOM 13
#define POST_WAIT_EVEN_THEN 14

//VAR_NAVAL_BASE_STATE
#define NAVAL_BASE_RAID_NOT_STARTED 0
#define NAVAL_BASE_RAID_START 1
#define CHASE_VIGRIM  2
#define SAVE_BAIYA_NAVAL_BASE   3
#define DEFEATED_BAIYA_NAVAL_BASE 4

//VAR_GROUP_OF_ASSHOLES_STATE
#define HAS_NOT_SEEN_GROUP_THE_TIDE 0
#define SAVE_THE_TIDE_POPIDORA_PIER 1
#define PLAYER_HAS_DEFEATED_THE_TIDE 2

//VAR_ROUTE99_STATE
#define PROTEST_NOTSTARTED  0
#define SAVE_THE_TIDE_ROUTE99  1
#define DEFEATED_THE_TIDE_ROUTE99  2

//VAR_FAINTED_FOG_STATE
#define NEVER_ENCOUNTERED 0
#define ENCOUNTERED_FOG_MON 1
#define WARPED_AFTER_ENCOUNTER 2

//VAR_CHASILLA_STATE
#define SWAGBAG_2_COMPLETE  1
#define DEFEATED_PUA  2
#define GOT_ARANTRAZ_TICKET 3

//VAR_TIRABUDIN_PLACE_STATE
#define PARADE_NOT_STARTED 0
#define PARADE_COMPLETE 1

//VAR_BEACH_BATTLE_STATE
#define NOT_SEEN_CHARLOTTE_BEACH 0
#define SAVE_CHARLOTTE_BEACH   1
#define POST_BEACH_BATTLE   2

//VAR_FORT_YOBU_STATE
#define DEFEATED_NERIENE 1
#define MET_KEIYING_OUTSIDE_GYM 2

//VAR_KEIYING_RAISON_DETRE_STATE
#define NOT_ENTERED_KEIYING_HOUSE 0
#define MET_KEIYING_KIDS   1
#define START_KEIYING_WINE_SPEECH  2
#define POST_KEIYING_WINE_SPEECH   3
#define POST_KEIYING_RAISON_DETRE 4

//VAR_KEIYING_MANSION_STATE
#define HAS_NOT_FINISHED_KEIYING_RAISON 0
#define FINISHED_KEIYING_RAISON 1

//VAR_WAIT_YOU_WENT_WHERE
#define PRE_WAITYOUWENTWHERE 0
#define POST_WAITYOUWENTWHERE 1

//VAR_CONSTRUCTION_STRIKE_STATE
#define STRIKE_NOT_STARTED 0
#define STRIKE_HAS_BEGUN    1
#define START_VS_GARBODOR   2
#define DEFEATED_GARBODOR   3
#define THE_TIDE_ARRESTED 4

//VAR_INNER_CONSTRUCTION_SITE_STATE
#define PLAYER_LEFT_SIDE    1
#define PLAYER_RIGHT_SIDE   2

//VAR_GOLDENGATEBRIDGE_STATE 0x406C
#define CALLED_BY_CHARLOTTE    1
#define POST_OFF_YOU_GO 2

//VAR_ROBINWILLIAMSTUNNEL_STATE 0x406D
#define CHARLOTTE_INSIDE_TUNNEL 1
#define CHARLOTTE_EXPLAINED_PUZZLE 2
#define PUZZLE_1_UNSOLVED   3
#define PUZZLE_1_SOLVED 4
#define PUZZLE_2_SOLVED 5
#define FRANK_BOSS_DEFEATED   6

//VAR_ESPULEE_OUTSKIRTS_STATE 0x406E
#define ROBINWILLIAMSTUNNEL_PUZZLES_SOLVED 1
#define CHARLOTTE_INVITED_KOMALACABIN   2
#define CHARLOTTE_STUDYING             3
#define CHARLOTTE_DEEP_STUDYING        4

//VAR_LEAVERRA_FOREST_STATE
#define CHARLOTTE_WAITING_LEAVERRA_FOREST    1
#define CHARLOTTE_ENTERED_LEAVERRA_FOREST    2
#define LEAVERRA_FOREST_MAZE_COMPLETE     3
#define MET_FRANK                 4
#define FINISHED_FRANK_PUZZLES    5
#define POST_HAVE_YOU_SEEN_THE_NEWS 6


//VAR_SHARPRISESTADIUM_TOURNAMENT_STATE 0x4072
#define NO_TOURNAMENT   0
#define PRE_BATTLE_1    1
#define PRE_BATTLE_2    2
#define PRE_BATTLE_3    3
#define PRE_BATTLE_4    4
#define PRE_BATTLE_5    5

//VAR_WAREHOUSE_RAVE_STATE
#define GOT_RAVE_MESSAGE    1
#define SAVE_KEIYING_WAREHOUSE 2
#define DEFEATED_KEIYING_WAREHOUSE  3
#define TOLD_BAIYA_ABOUT_KEIYING  4

//VAR_HOWDISAPPOINTING_STATE
#define MISSION_NOT_ASSIGNED    0
#define MISSION_ASSIGNED    1
#define GYM_RAID_STARTED    2
#define GRUNT1_ARRESTED 3
#define GRUNT2_ARRESTED 4
#define SAVED_BEFORE_ADAORA 5
#define DEFEATED_ADAORA_HODOU_CITY   6
#define HOWDISAPPOINTING_COMPLETE 7

//VAR_MANHUNT_STATE
#define NOT_ASSIGNED 0
#define ASSIGNED_FIND_VIGRIM  1
#define GOT_MANHUNT_CLUE_1  2
#define GOT_MANHUNT_CLUE_2  3
#define GOT_MANHUNT_CLUE_3  4
#define GOT_MANHUNT_CLUE_4  5
#define SAVED_BEFORE_VIGRIM 6
#define DEFEATED_MANHUNT_VIGRIM   7
#define MANHUNT_COMPLETE 8

//VAR_MASK_OFF_STATE 0x405C
#define NOT_ASSIGNED    0
#define ASSIGNED_MASK_OFF   1
#define GOT_MASK_OFF_CLUE_1  2
#define GOT_MASK_OFF_CLUE_2  3
#define GOT_MASK_OFF_CLUE_3  4
#define GOT_MASK_OFF_CLUE_4  5
#define GOT_MASK_OFF_CLUE_5  6
#define SAVE_VIGRIM_WISHAAST_LAKE_TRUE  7
#define DEFEATED_MASK_OFF_VIGRIM  8

//VAR_LETSBURNTHISMOTHERSTATE
#define NOT_ASSIGNED 0
#define ASSIGNED_BURN_MOTHER    1
#define SAVE_BAIYA_ARANTRAZ    2
#define DEFEATED_BAIYA_ARANTRAZ    3
#define BURN_MOTHER_COMPLETE    4

//VAR_PARC_STATE 0x4052
#define LAB_NOT_DISCOVERED  0
#define PLAYER_DISCOVERED_LAB   1
#define THE_TIDE_DISCOVERED_LAB   2
#define MAGNUS_UNLOCKED_DOOR    3
#define TEAM_INSIDE_LAB 4
#define FREED_LAB_POKEMON_1 5
#define FREED_LAB_POKEMON_2 6
#define SAVE_BEFORE_DYNAMAX 7
#define DEFEATED_DYNAMAX    8

//VAR_TOWER_RAID_STATE 0x4059
#define BROKEN_IN_RAMESH   1
#define SEARCHING_RAMESH_HOUSE 2
#define FOUND_RAMESH_WARP_DOOR 3
#define FOUND_RAMESH_CODE 4
#define RAMESH_WARP_DOOR_UNLOCKED  5
#define TEAM_ENTERED_SHARPRISESPIRE    6
#define SAVE_CHARLOTTE_SHARPRISESPIRE 7
#define DEFEATED_CHARLOTTE_SHARPRISESPIRE 8
#define STOPPED_BY_OLIVER 9
#define SAVE_LUCREZIA_SHARPRISESPIRE   10
#define DEFEATED_FIRST_LUCREZIA 11
#define DEFEATED_SECOND_LUCREZIA 12
#define DEFEATED_LUCREZIA_SHARPRISESPIRE   13

//VAR_QUEST_HODOUTUNNELS
#define NEVER_SPOKEN_ELDER  0
#define SPOKEN_ELDER_FIRST_TIME  1
#define SENT_TO_FIND_RED_SCROLL 2
#define FOUND_RED_SCROLL    3

//VAR_BELEN_STATE
//VAR_SHINZO_STATE
//VAR_EMRYS_STATE
//VAR_PUA_STATE
//VAR_NERIENE_STATE
//VAR_DIMU_STATE
//VAR_BD_STATE
//VAR_AMIARGENTO_STATE
#define NO_BADGE             0
#define BATTLE_1_COMPLETE    1
#define QUEST_1_COMPLETE     2
#define QUEST_2_COMPLETE     3
#define BATTLE_2_COMPLETE    4
#define EXHIBITION_READY     5 //Used for Quest_Alohafromalola
#define EXHIBITION_COMPLETE  6 //Used for Quest_Alohafromalola
#define CUTSCENE_COMPLETE    7 //Used for Quest_Restaurantexpansion

//VAR_CUTE_POKEMON_GUESS
#define VAR_CUTE_POKEMON_STATE_NOT_STARTED 0
#define VAR_CUTE_POKEMON_GREETING_PERLACIA 1
#define VAR_CUTE_POKEMON_EISCUE_HINT_0 2
#define VAR_CUTE_POKEMON_EISCUE_HINT_1 3
#define VAR_CUTE_POKEMON_EISCUE_HINT_2 4
#define VAR_CUTE_POKEMON_GREETING_QIU 5
#define VAR_CUTE_POKEMON_ASK_BATTLE_QIU 6
#define VAR_CUTE_POKEMON_BATTLE_QIU_COMPLETE 7
#define VAR_CUTE_POKEMON_CORSOLA_HINT_0 8
#define VAR_CUTE_POKEMON_CORSOLA_HINT_1 9
#define VAR_CUTE_POKEMON_CORSOLA_HINT_2 10
#define VAR_CUTE_POKEMON_GREETING_CRESALTA  11
#define VAR_CUTE_POKEMON_ASK_BATTLE_CRESALTA 12
#define VAR_CUTE_POKEMON_BATTLE_CRESALTA_COMPLETE  13
#define VAR_CUTE_POKEMON_DUSKULL_HINT_0  14
#define VAR_CUTE_POKEMON_DUSKULL_HINT_1  15
#define VAR_CUTE_POKEMON_DUSKULL_HINT_2  16
#define VAR_CUTE_POKEMON_GREETING_HALAI  17
#define VAR_CUTE_POKEMON_ASK_BATTLE_HALAI 18
#define VAR_CUTE_POKEMON_BATTLE_HALAI_COMPLETE  19
#define VAR_CUTE_POKEMON_SCRAFTY_HINT_0  20
#define VAR_CUTE_POKEMON_SCRAFTY_HINT_1  21
#define VAR_CUTE_POKEMON_SCRAFTY_HINT_2  22
#define VAR_CUTE_POKEMON_CORRECT  23
#define VAR_CUTE_POKEMON_PERLACIA 24
#define VAR_CUTE_POKEMON_QIU  25
#define VAR_CUTE_POKEMON_CRESALTA  26
#define VAR_CUTE_POKEMON_HALAI  27
#define VAR_CUTE_POKEMON_REMATCH_COMPLETE 28

//Number of times you have incorrectly brought a pokemon to the girl in the Quest Cute Pokemon
//resets after a subquest is completed


//VAR_QUEST_RESTOREESPULEEGYM
#define SAVE_BEFORE_IMELDA_BATTLE 1
#define DEFEATED_IMELDA 2

//VAR_QUEST_RESTOREHODOUGYM 0x40FF
#define PRE_PEWFAT_INTO_GYM 0
#define POST_PEWFAT_INTO_GYM    1
#define FIND_HODOU_CITY_LEADER   2
#define FOUND_HODOU_CITY_LEADER  3
#define FIND_BLACKBELTS 4
#define FOUND_ALL_BLACKBELTS 11
#define RESTOREHODOU_CITY_COMPLETE   12

//VAR_QUEST_RESTOREZENZUGYM
#define RESTOREZENZU_ISLAND_NOT_STARTED   0
#define SAVE_BEFORE_DOYLE_BATTLE 1
#define DEFEATED_DOYLE 2

//VAR_QUEST_RECRUITLOLCAARTISTS
#define SMEARGLE_NO_LOCALS  0
#define SMEARGLE_LOCAL_1	1
#define SMEARGLE_LOCAL_2	2

//VAR_QUEST_GLITTERS_GOLD_STATE
#define NOT_TALKED 0
#define NOT_SHOWN_PICTURE 1
#define SHOWN_PICTURE 2
#define QUEST_ASSIGNED 3
#define POST_DIVE 4
#define CAUGHT_SHINY 4
#define DEFEATED_SHINY 5

//VAR_CHASILLA_AXE_STATE
#define AXE_UNTOUCHED   0
#define AXE_STOLEN  1
#define AXE_THROWN_AWAY 2
#define AXE_ASKED   3
#define AXE_TURNED_OVER 4

//VAR_QUEST_MANOFMANYHATS
#define SEEN_LIIDIA_1ST 1
#define SEEN_LIIDIA_2ND 2
#define SEEN_LIIDIA_3RD 3
#define OPEN_LOCKED_DOOR    4

//VAR_FIRSTRUNEXPERIENCE
#define NOT_STARTED 0
#define CHARACTER_CREATED 1
#define CHARACTER_NAMED 2
#define HAS_READ_LETTER 3

//VAR_CHOSEN_PSF_STARTER
#define STARTER_CHOSEN_SCYTHER  SPECIES_SCYTHER
#define STARTER_CHOSEN_CHARCADET  SPECIES_CHARCADET
#define STARTER_CHOSEN_PETILIL  SPECIES_PETILIL
#define STARTER_CHOSEN_FLAAFFY  SPECIES_FLAAFFY
#define STARTER_CHOSEN_MAREANIE  SPECIES_MAREANIE
#define STARTER_CHOSEN_ARON  SPECIES_ARON
#define STARTER_CHOSEN_SWINUB  SPECIES_SWINUB
#define STARTER_CHOSEN_HATTREM  SPECIES_HATTREM
#define STARTER_CHOSEN_PANCHAM  SPECIES_PANCHAM
#define NO_STARTER_CHOSEN  NUM_SPECIES
#define CUTSCENE_NOT_PLAYED SPECIES_NONE

//VAR_PROLOGUE_STATE
#define NOT_STARTED 0
#define GIVEN_POKEMON 1
#define WALKED_IN_CHAMBER   2
#define LOST_TO_MAGNUS  3
#define DEFEATED_MAGNUS 4
#define WALK_INTO_HALL 5
#define ELEANOR_ANNOUNCE   6
#define START_ADVENTURE 7

//VAR_DANCEBATTLE_STATE
#define NEVER_TIPPED 0
#define TIPPED_ONCE 1
#define TIPPED_TWICE    2
#define TIPPED_THRICE   3
#define TIPPED_FOUR 4

//VAR_QUEST_FOOD_TRUCK_BUREAUCRACY_STATE
#define NOT_STARTED 0
#define TALKED_TO_FOOD  1
#define TALKED_TO_SANITATION    2
#define TALKED_TO_IT    3
#define TALKED_TO_TRANSPORTATION    4
#define TRANSPORT_FROM_FOOD 5
#define DELIVERED_TO_TRANSPORATION  6
#define DELIVERED_TO_IT    7
#define DELIVERED_TO_SANITATION 8

//VAR_QUEST_WAREHOUSEWARFARE_STATE
#define NOT_STARTED 0
#define SAVED_BEFORE_PRESTO_CEO 1

//VAR_QUEST_BREAKTHEINTERNET_STATE
#define NOT_STARTED 0
#define TALA_MENTIONED_REPORTER 1
#define TALKED_TO_REPORTER  2
#define SAVED_BEFORE_BUZZR_CEO 3

//VAR_QUEST_PERSUASIVE_PASSENGER_STATE
#define NOT_STARTED 0
#define SAVED_BEFORE_ARRIBA_CEO 1

//VAR_QUEST_MUTUALAIDFUND_AMOUNT
#define NOT_STARTED 0
#define MUTUALAID_REWARD_1 1
#define MUTUALAID_REWARD_2 2
#define MUTUALAID_REWARD_3 3
#define MUTUALAID_REWARD_4 4
#define MUTUALAID_REWARD_5 5
#define MUTUALAID_REWARD_6 6
#define MUTUALAID_REWARD_7 7
#define MUTUALAID_REWARD_8 8
#define MUTUALAID_REWARD_9 9
#define MUTUALAID_REWARD_10 10
#define MUTUALAID_REWARD_11 11
#define MUTUALAID_REWARD_12 12
#define MUTUALAID_REWARD_13 13
#define MUTUALAID_REWARD_14 14

//VAR_QUEST_VOLUNTEER_FIREFIGHTER_COUNT
#define REQUIRED_NUMBER_OF_POKEMON 5

//VAR_CAPHE_CITY_STATE
#define LINE_IS_BLOCKING 0
#define LINE_IS_NOT_BLOCKING 1
#define LINE_IS_GONE 2

//VAR_QUEST_VSDEOXYS
#define VSDEOGUY_NOT_INTERACTED 0
#define VSDEOGUY_INTERACTED 1
#define VSDEOGUY_LEFT_ROUTE 2
#define VSDEOGUY_ENTERED_RESEARCH 3
#define VSDEOGUY_LEFT_RESEARCH 4

// VAR_QUEST_DRUGHELMETTEST
#define DRUGHELMETTEST_FIRSTPHASE 0
#define DRUGHELMETTEST_SECONDPHASE 1
#define DRUGHELMETTEST_THIRDPHASE 2

// VAR_TIME_TRAVEL_STATE
#define TIME_TRAVEL_NEVER_STARTED 0
#define TIME_TRAVEL_START_CUTSCENE 1
#define TIME_TRAVEL_FIRST_RETURN 2
#define TIME_TRAVEL_ASK_PLAYER 3
#define TIME_TRAVEL_SACRIFICE_COMPLETE 4
#define TIME_TRAVEL_ASKED_ABOUT_SNOM 5
#define TIME_TRAVEL_FIRST_WORMHOLE_USE 6
#define TIME_TRAVEL_COMPLETE 7
