#ifndef GUARD_VISUAL_OPTIONS_H
#define GUARD_VISUAL_OPTIONS_H

#define VISUAL_OPTION_TEXTSPEED_SLOW 0
#define VISUAL_OPTION_TEXTSPEED_MEDIUM 1
#define VISUAL_OPTION_TEXTSPEED_FAST 2
#define VISUAL_OPTION_TEXTSPEED_INSTANT 3

#endif //GUARD_VISUAL_OPTIONS_H
