#ifndef GUARD_CONSTANTS_WAVES_H
#define GUARD_CONSTANTS_WAVES_H

enum WavesMode
{
    WAVES_MODE_LANDING_PAGE,
    WAVES_MODE_GOAL_DETAIL,
    WAVES_MODE_GOAL_DONATE_AMOUNT,
    WAVES_MODE_GOAL_NOT_ENOUGH,
    WAVES_MODE_COUNT,
};

enum WavesCursorPosition
{
    WAVES_CURSOR_0,
    WAVES_CURSOR_1,
    WAVES_CURSOR_2,
    WAVES_CURSOR_3,
    WAVES_CURSOR_4,
    WAVES_CURSOR_5,
    WAVES_CURSOR_COUNT,
};

enum GoalEnum
{
    GOAL_NONE,
    GOAL_FOOD_SECURITY,
    GOAL_HEALTHCARE,
    GOAL_SOCIAL_HOUSING,
    GOAL_CRIMINAL_REFORM,
    GOAL_LEGAL_DEFENSE,
    GOAL_COUNT,
};

enum GoalAttributes
{
    GOAL_PLAYER_PERCENT,
    GOAL_PASSIVE_PERCENT,
    GOAL_PERCENT_COUNT,
};

enum WavesBackgrounds
{
    BG0_WAVES_TEXT,
    BG1_WAVES_LANDING,
    BG2_WAVES_DETAIL,
    BG3_WAVES_WALLPAPER,
    BG_WAVES_COUNT,
};

enum WavesWindowsGrid
{
    WIN_WAVES_CARD_HEADER,
    WIN_WAVES_CARD_1,
    WIN_WAVES_CARD_2,
    WIN_WAVES_CARD_3,
    WIN_WAVES_CARD_4,
    WIN_WAVES_CARD_5,
    WIN_WAVES_CARD_6,
    WIN_WAVES_CARD_FOOTER,
    WIN_WAVES_CARD_COUNT,
};

enum WavesWindowsGoal
{
    WIN_WAVES_GOAL_HEADER,
    WIN_WAVES_GOAL_DESC,
    WIN_WAVES_GOAL_RAISED,
    WIN_WAVES_GOAL_PLAYER,
    WIN_WAVES_GOAL_PASSIVE,
    WIN_WAVES_GOAL_TOTAL,
    WIN_WAVES_GOAL_FOOTER,
    WIN_WAVES_GOAL_COUNT,
};

enum WavesPaletteColors
{
    WAVES_PALETTE_TRANSPERANT,
    WAVES_PALETTE_COLOR_1,
    WAVES_PALETTE_COLOR_2,
    WAVES_PALETTE_COLOR_3,
    WAVES_PALETTE_COLOR_4,
    WAVES_PALETTE_COLOR_5,
    WAVES_PALETTE_COLOR_6,
    WAVES_PALETTE_COLOR_7,
    WAVES_PALETTE_COLOR_8,
    WAVES_PALETTE_COLOR_9,
    WAVES_PALETTE_COLOR_10,
    WAVES_PALETTE_COLOR_11,
    WAVES_PALETTE_COLOR_12,
    WAVES_PALETTE_COLOR_13,
    WAVES_PALETTE_COLOR_14,
    WAVES_PALETTE_COLOR_15,
};

enum WavesFontColors
{
  WAVES_FONT_COLOR_BLACK,
  WAVES_FONT_COLOR_WHITE,
};

#define WAVES_PASSIVE_INCREASE_TRUE 5
#define WAVES_PASSIVE_INCREASE 2

#define WAVES_FONT_CARD_HEADER       FONT_NARROW
#define FONT_WAVES_TITLE             FONT_NORMAL
#define FONT_WAVES_DESC              FONT_NORMAL
#define FONT_WAVES_GOAL_TITLE        FONT_OUTLINED
#define WAVES_PALETTE_INTERFACE_ID   0
#define WAVES_PALETTE_INTERFACE_SLOT BG_PLTT_ID(WAVES_PALETTE_INTERFACE_ID)
#define WAVES_PALETTE_TEXT_ID        15
#define WAVES_PALETTE_TEXT_SLOT      BG_PLTT_ID(WAVES_PALETTE_TEXT_ID)
#define WAVES_METER_FACTOR           15625
#define WAVES_METER_CENTER_SECTIONS  6
#define WAVES_METER_TILE_OFFSET      40

#define WAVES_HEADER_X               0
#define WAVES_HEADER_Y               25

#define WAVES_THUMBNAIL_X_POSITION   20
#define WAVES_THUMBNAIL_Y_POSITION   5
#define WAVES_THUMBNAIL_X_PADDING   72
#define WAVES_THUMBNAIL_Y_PADDING   70

#define WAVES_PAL_ICON_SPRITE_TAG         188
#define WAVES_PAL_SPRITE_TAG         189
#define WAVES_SPRITE_TAG             179
#define WAVES_SPRITE_TAG_CURSOR      180

#define WAVES_COLUMN_COUNT          3
#define WAVES_ROW_COUNT          2

#endif // GUARD_CONSTANTS_WAVES_H
