#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

// Start wildEncounters
/*
#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10
*/
#define LAND_WILD_COUNT     20
#define WATER_WILD_COUNT    20
#define ROCK_WILD_COUNT     20
#define FISH_WILD_COUNT     20
#define HIDDEN_WILD_COUNT   3

enum EncounterSlots
{
    ENCOUNTER_SLOT_0,
    ENCOUNTER_SLOT_1,
    ENCOUNTER_SLOT_2,
    ENCOUNTER_SLOT_3,
    ENCOUNTER_SLOT_4,
    ENCOUNTER_SLOT_5,
    ENCOUNTER_SLOT_6,
    ENCOUNTER_SLOT_7,
    ENCOUNTER_SLOT_8,
    ENCOUNTER_SLOT_9,
    ENCOUNTER_SLOT_10,
    ENCOUNTER_SLOT_11,
    ENCOUNTER_SLOT_12,
    ENCOUNTER_SLOT_13,
    ENCOUNTER_SLOT_14,
    ENCOUNTER_SLOT_15,
    ENCOUNTER_SLOT_16,
    ENCOUNTER_SLOT_17,
    ENCOUNTER_SLOT_18,
    ENCOUNTER_SLOT_19,
    ENCOUNTER_SLOT_COUNT,
};

#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_TOTAL 0
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_TOTAL 0
#define ENCOUNTER_CHANCE_FISHING_MONS_OLD_ROD_SLOT_0 0
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_2 0
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_3 0
#define ENCOUNTER_CHANCE_FISHING_MONS_GOOD_ROD_SLOT_4 0

#define ENCOUNTER_SLOT_CHANCE 5
#define ENCOUNTER_SLOT_MAX ENCOUNTER_SLOT_19
// End wildEncounters

#define NUM_ALTERING_CAVE_TABLES 9

#define FISHING_CHAIN_LENGTH_MAX 200
#define FISHING_CHAIN_SHINY_STREAK_MAX 20

// Start fogBattle
enum WildPokemonArea {
    WILD_AREA_LAND,
    WILD_AREA_WATER,
    WILD_AREA_ROCKS,
    WILD_AREA_FISHING,
    WILD_AREA_HIDDEN,
    WILD_AREA_BERRY_TREES, // wildEncounters
    WILD_AREA_FLY_MONS,   // wildEncounters
    WILD_AREA_PHENOMENON, // phenomenon
};
// End fogBattle
#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
