
#ifndef GUARD_SILICON_WILD_ENCOUNTER_H
#define GUARD_SILICON_WILD_ENCOUNTER_H

// Start fogBattle
enum WildPokemonArea {
    WILD_AREA_LAND,
    WILD_AREA_WATER,
    WILD_AREA_ROCKS,
    WILD_AREA_FISHING,
    WILD_AREA_HIDDEN,
    WILD_AREA_BERRY_TREES, // wildEncounters
    WILD_AREA_FLY_MONS,   // wildEncounters
    WILD_AREA_PHENOMENON, // phenomenon
};
// End fogBattle

#define ENCOUNTER_SLOT_CHANCE 5

enum EncounterSlots
{
    ENCOUNTER_SLOT_0,
    ENCOUNTER_SLOT_1,
    ENCOUNTER_SLOT_2,
    ENCOUNTER_SLOT_3,
    ENCOUNTER_SLOT_4,
    ENCOUNTER_SLOT_5,
    ENCOUNTER_SLOT_6,
    ENCOUNTER_SLOT_7,
    ENCOUNTER_SLOT_8,
    ENCOUNTER_SLOT_9,
    ENCOUNTER_SLOT_10,
    ENCOUNTER_SLOT_11,
    ENCOUNTER_SLOT_12,
    ENCOUNTER_SLOT_13,
    ENCOUNTER_SLOT_14,
    ENCOUNTER_SLOT_15,
    ENCOUNTER_SLOT_16,
    ENCOUNTER_SLOT_17,
    ENCOUNTER_SLOT_18,
    ENCOUNTER_SLOT_19,
    ENCOUNTER_SLOT_MAX = ENCOUNTER_SLOT_19,
    ENCOUNTER_SLOT_COUNT,
};

#endif // GUARD_SILICON_WILD_ENCOUNTER_H
