#ifndef GUARD_CONSTANTS_WILD_ENCOUNTER_H
#define GUARD_CONSTANTS_WILD_ENCOUNTER_H

#define LAND_WILD_COUNT     12
#define WATER_WILD_COUNT    5
#define ROCK_WILD_COUNT     5
#define FISH_WILD_COUNT     10
#define HIDDEN_WILD_COUNT   3

#define NUM_ALTERING_CAVE_TABLES 9

#define FISHING_CHAIN_LENGTH_MAX 200
#define FISHING_CHAIN_SHINY_STREAK_MAX 20

// Start fogBattle
enum WildPokemonArea {
    WILD_AREA_LAND,
    WILD_AREA_WATER,
    WILD_AREA_ROCKS,
    WILD_AREA_FISHING,
    WILD_AREA_HIDDEN
};
// End fogBattle
#endif // GUARD_CONSTANTS_WILD_ENCOUNTER_H
