#ifndef GUARD_GIVE_NATIVE_ITEM_H
#define GUARD_GIVE_NATIVE_ITEM_H

void BS_GetPrizeNativeItem(void);

enum
{
    NATIVE_ITEM_GROUP_0,
    NATIVE_ITEM_GROUP_1,
    NATIVE_ITEM_GROUP_2,
    NATIVE_ITEM_GROUP_3,
    NATIVE_ITEM_GROUP_4,
    NATIVE_ITEM_GROUP_5,
};

#endif // GUARD_GIVE_NATIVE_ITEM_H
