#ifndef GUARD_SILICON_BATTLE_STATUS_CRITERIA_H
#define GUARD_SILICON_BATTLE_STATUS_CRITERIA_H

enum SiliconBattleStatuses
{
    BATTLE_STATUS_MEGA_EVOLVE,
    BATTLE_STATUS_DYNAMAX,

    BATTLE_STATUS_BURN,
    BATTLE_STATUS_FREEZE,
    BATTLE_STATUS_PARALYZED,
    BATTLE_STATUS_POISONED,
    BATTLE_STATUS_BADLY_POISONED, // toxic
    BATTLE_STATUS_ASLEEP,

    BATTLE_STATUS_ELECTRIC_TERRAIN,
    BATTLE_STATUS_GRASSY_TERRAIN,
    BATTLE_STATUS_MISTY_TERRAIN,
    BATTLE_STATUS_PSYCHIC_TERRAIN,
    BATTLE_STATUS_HARSH_SUN,
    BATTLE_STATUS_RAIN,
    BATTLE_STATUS_SANDSTORM,
    BATTLE_STATUS_SNOW,
    BATTLE_STATUS_FOG,
    BATTLE_STATUS_VERY_HARSH_SUN,
    BATTLE_STATUS_HEAVY_RAIN,
    BATTLE_STATUS_STRONG_WINDS,
    BATTLE_STATUS_SPIKES,
    BATTLE_STATUS_STEALTH_ROCK,
    BATTLE_STATUS_TOXIC_SPIKES,
    BATTLE_STATUS_STICKY_WEB,
    BATTLE_STATUS_SHARP_STEEL,
    BATTLE_STATUS_MAGIC_ROOM,
    BATTLE_STATUS_WONDER_ROOM,
    BATTLE_STATUS_GRAVITY,
    BATTLE_STATUS_TRICK_ROOM,
    BATTLE_STATUS_TAILWIND,

    #define UNPACK_BATTLE_STATUS_VOLATILES(constants, ...) CAT(BATTLE_STATUS_, constants),
    VOLATILE_DEFINITIONS(UNPACK_BATTLE_STATUS_VOLATILES)
    #undef UNPACK_BATTLE_STATUS_VOLATILES

    BATTLE_STATUS_CENTER_ATTENTION,
    BATTLE_STATUS_MAGIC_COAT,
    BATTLE_STATUS_PROTECTION,
    BATTLE_STATUS_UNDERGROUND,
    BATTLE_STATUS_HIGH_FLIGHT,
    BATTLE_STATUS_UNDERWATER,
    BATTLE_STATUS_IN_SHADOWS,

    NUM_BATTLE_STATUSES
};

struct MaxBattleStatusValues
{
    u8 weatherDuration:4;
    u8 trickRoomDuration:4;
    u8 magicRoomDuration:4;
    u8 wonderRoomDuration:4;
    u8 gravityDuration:4;
    u8 tailwindDuration:4;
};

extern EWRAM_DATA struct MaxBattleStatusValues gRecordedMaxBattleStatusValues;

u32 BattleStatusCriteria_CompileListForBattler(enum BattlerId, enum SiliconBattleStatuses *);
u32 BattleStatusCriteria_GetMaxTotalListItems(void);
const u8 *BattleStatusCriteria_GetFormattedName(enum BattlerId, enum SiliconBattleStatuses);
const u8 *BattleStatusCriteria_GetDescription(enum SiliconBattleStatuses);

#endif // GUARD_SILICON_BATTLE_STATUS_CRITERIA_H
