#ifndef GUARD_SILICON_FRONTIER_ACCESSORS_H
#define GUARD_SILICON_FRONTIER_ACCESSORS_H

u16 SiliconFrontier_GetNumberBattles(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType, enum SiliconFrontierSparringTypes sparringType);
void SiliconFrontier_SetNumberBattles(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType, enum SiliconFrontierSparringTypes sparringType, u32 value);
u16 SiliconFrontier_GetCurrentStreak(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType, enum SiliconFrontierSparringTypes sparringType);
void SiliconFrontier_SetCurrentStreak(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType, enum SiliconFrontierSparringTypes sparringType, u32 value);
u16 SiliconFrontier_GetLongestStreak(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType, enum SiliconFrontierSparringTypes sparringType);
void SiliconFrontier_SetLongestStreak(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType, enum SiliconFrontierSparringTypes sparringType, u32 value);
struct BattleFrontierRecordMon SiliconFrontier_GetLongestStreakPlayerPartyMon(enum SiliconFrontierFacility facility, enum SiliconFrontierSparringTypes sparringType, enum SiliconFrontierChallengeType challengeType, u32 slot);
void SiliconFrontier_SetLongestStreakPlayerPartyMonAttribute(enum SiliconFrontierFacility facility, enum SiliconFrontierSparringTypes sparringType, enum SiliconFrontierChallengeType challengeType, u32 slot, enum MonData attribute, u32 value);
u32 SiliconFrontier_GetLongestStreakPartner(enum SiliconFrontierFacility facility, enum SiliconFrontierSparringTypes sparringType);
void SiliconFrontier_SetLongestStreakPartner(enum SiliconFrontierFacility facility, enum SiliconFrontierSparringTypes sparringType, u32 partner);
u16 SiliconFrontier_GetPlayerFactoryRentalMon(enum SiliconFrontierChallengeType challengeType, u32 slot);
void SiliconFrontier_SetPlayerFactoryRentalMon(enum SiliconFrontierChallengeType challengeType, u32 slot, u32 monId);
u32 SiliconFrontier_GetCurrentPartner(void);
void SiliconFrontier_SetCurrentPartner(u32 currentPartner);
u8 SiliconFrontier_GetRemainingHeals(void);
void SiliconFrontier_SetRemainingHeals(u32 value);
void SiliconFrontier_AllowRecordedBattle(void);
void SiliconFrontier_DisableRecordedBattle(void);
bool32 SiliconFrontier_CanBattleBeRecorded(void);
void SiliconFrontier_SetSelectedPartyMon(u32 saveBlockSlot, u32 partySlot);
u32 SiliconFrontier_GetSelectedPartyMon(u32 saveBlockSlot);
void SiliconFrontier_SetCurrentChallengeFacility(enum SiliconFrontierFacility facility);
void SiliconFrontier_SetCurrentChallengeChallengeType(enum SiliconFrontierChallengeType challengeType);
void SiliconFrontier_SetCurrentChallengeSparringType(enum SiliconFrontierSparringTypes sparringType);
enum SiliconFrontierFacility SiliconFrontier_GetFacilityFromCurrentChallenge(void);
enum SiliconFrontierChallengeType SiliconFrontier_GetTypeFromCurrentChallenge(void);
enum Type SiliconFacility_GetChosenSparringType(void);
enum SiliconFrontierChallengeType SiliconFrontier_GetLastChallengeTypeFromCurrentFacility(void);
void SiliconFrontier_SetLastChallenge(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType);
enum SiliconFrontierChallengeType SiliconFrontier_GetLastChallenge(enum SiliconFrontierFacility facility);
void SiliconFrontier_SetLastChallengeFacility(enum SiliconFrontierFacility facility);
void SiliconFrontier_SetLastChallengeChallengeType(enum SiliconFrontierFacility facility, enum SiliconFrontierChallengeType challengeType);
void SiliconFrontier_SetLastChallengeSparringType(enum SiliconFrontierFacility facility, enum SiliconFrontierSparringTypes sparringType);
enum SiliconFrontierFacility SiliconFrontier_GetFacilityFromLastChallenge(void);
enum SiliconFrontierChallengeType SiliconFrontier_GetTypeFromLastChallenge(enum SiliconFrontierFacility facility);
enum SiliconFrontierSparringTypes SiliconFrontier_GetCurrentChallengeSparringType(void);
enum SiliconFrontierSparringTypes SiliconFrontier_GetLastSparringType(enum SiliconFrontierFacility facility);

#endif // GUARD_SILICON_FRONTIER_ACCESSORS_H
